support: 배포스크립트 Profiles 변경
woowacourse-teams/2023-zipgo pull request #102
Opened 2023-08-01 02:00 UTC by wonyongChoi05

## 📄 Summary
> #100 

## 🙋🏻 More
>

2023-08-01 02:18 UTC, kyY00n approved these changes
고마워용👍🏻

2023-08-01 04:38 UTC, iamjooon2 submitted a review, later dismissed

2023-08-01 09:10 UTC, kyY00n requested changes
dev 프로퍼티 확인 부탁해요 베베 ><

2023-08-01 09:10 UTC, kyY00n commented on backend/deploy.sh
> +-Dspring.profiles.active=dev \
이렇게 변경하고 나면 dev 프로필 사용할텐데
현재 dev 프로필 jpa ddl auto 옵션이 create 이라
이거 의도한게 맞는지 확인 부탁합니다!

2023-08-01 09:45 UTC, parkmuhyeun approved these changes

2023-08-01 10:46 UTC, kyY00n commented
베베 진짜 미안한데 ㅋㅋ.. dev도 osiv 꺼줄수 있어? .. ㅎㅎ흐히핳

2023-08-02 06:07 UTC, kyY00n submitted a review, later dismissed

2023-08-02 06:15 UTC, kyY00n approved these changes

2023-08-02 06:16 UTC, parkmuhyeun approved these changes
완벽.

2023-08-02 06:16 UTC, merged