feat: NavigationBar 컴포넌트 구현
woowacourse-teams/2023-zipgo pull request #111
Opened 2023-08-01 12:08 UTC by ksone02

## 📄 Summary
> close #110

네비게이션 탭 바 컴포넌트를 구현했습니다.
피드백 부탁합니다.

<img width="390" alt="스크린샷 2023-08-01 오후 9 07 00" src="https://github.com/woowacourse-teams/2023-zipgo/assets/72087183/afe9b3c0-a770-4e7a-a815-ff2c80ebb672">

<img width="832" alt="스크린샷 2023-08-01 오후 9 06 48" src="https://github.com/woowacourse-teams/2023-zipgo/assets/72087183/6e957695-bd8c-4ab1-9eab-4edcc0fd3c02">

## 🙋🏻 More
>

2023-08-01 16:15 UTC, HyeryongChoi requested changes

2023-08-01 16:15 UTC, HyeryongChoi commented on frontend/src/components/@common/NavigationBar/NavigationBar.tsx
> +    const [currentItemWidth, setCurrentItemWidth] = useState<number>(0);
이 친구들도 선언 위치를 다른 상태랑 가깝게 두면 코드 탐색이 더 쉬울 것 같아요!
`const [currentIndex, setCurrentIndex] = useState<number>(index);` 바로 다음에요!

2023-08-01 16:15 UTC, HyeryongChoi commented on frontend/src/components/@common/NavigationBar/NavigationBar.tsx
> +    }));
이 메서드들은 부모 컴포넌트에서 사용하는 메서드인가요? 
어떨 때 사용할 것이라고 예상하고 만든 건지 궁금합니다!
예를 들어, 일정 시간이 지나면 다음 탭으로 포커스를 이동시키고 싶을 때..?

2023-08-01 16:15 UTC, HyeryongChoi commented on frontend/src/components/@common/NavigationBar/NavigationBar.tsx
> +          setCurrentItemWidth(childNode.getBoundingClientRect().width);
오오 이렇게 인디케이터의 위치와 너비를 계산하는 건가요 신기하네요😲 배워갑니다

2023-08-01 16:15 UTC, HyeryongChoi commented on frontend/src/types/common/utility.ts
> +export type StyledProps<T> = { [K in keyof T as `$${string & K}`]: T[K] };
👍

2023-08-02 01:14 UTC, n0eyes requested changes

2023-08-02 01:14 UTC, n0eyes commented on frontend/src/components/@common/NavigationBar/NavigationBar.tsx
> +  snapToPrev(): void;
`VoidFunction` 사용하면 좋을 것 같아요!

2023-08-02 01:14 UTC, n0eyes commented on frontend/src/components/@common/NavigationBar/NavigationBar.tsx
> +type PropsWithClicked = StyledProps<{ clicked: boolean }>;
컴포넌트를 사용하는 인터페이스의 느낌이 있는데 `interface`는 어떨까요!?

2023-08-02 01:14 UTC, n0eyes commented on frontend/src/components/@common/NavigationBar/NavigationBar.tsx
> +              }}
핸들러를 분리하는 건 어떨까요~?

2023-08-02 04:29 UTC, ksone02 commented on frontend/src/components/@common/NavigationBar/NavigationBar.tsx
> +  index: number;
넵 반영할게요~

2023-08-02 04:29 UTC, ksone02 commented on frontend/src/components/@common/NavigationBar/NavigationBar.tsx
> +    const [currentItemWidth, setCurrentItemWidth] = useState<number>(0);
아 그렇네요! 수정하겠습니다~

2023-08-02 04:30 UTC, ksone02 commented on frontend/src/components/@common/NavigationBar/NavigationBar.tsx
> +    }));
네네 맞습니다! 자동 포커스나 부모 컴포넌트에서 간단하게 탭 바의 위치를 조절하고 싶을 때 사용하도록 했습니다~

2023-08-02 04:31 UTC, ksone02 commented on frontend/src/components/@common/NavigationBar/NavigationBar.tsx
> +  snapToPrev(): void;
반영하겠습니다~!

2023-08-02 04:31 UTC, ksone02 commented on frontend/src/components/@common/NavigationBar/NavigationBar.tsx
> +type PropsWithClicked = StyledProps<{ clicked: boolean }>;
앗 interface로 통일 하겠습니다!

2023-08-02 04:31 UTC, ksone02 commented on frontend/src/components/@common/NavigationBar/NavigationBar.tsx
> +              }}
아! 좋습니다 반영할게요!

2023-08-02 05:04 UTC, ksone02 commented on frontend/src/components/@common/NavigationBar/NavigationBar.tsx
> +  snapToPrev(): void;
반영하겠습니다~

2023-08-02 05:13 UTC, n0eyes submitted a review, later dismissed

2023-08-02 05:27 UTC, HyeryongChoi submitted a review, later dismissed

2023-08-02 05:44 UTC, n0eyes approved these changes

2023-08-02 06:06 UTC, HyeryongChoi approved these changes

2023-08-02 06:27 UTC, merged