feat: 리뷰 추가, 수정, 삭제 기능 구현
woowacourse-teams/2023-zipgo pull request #115
Opened 2023-08-02 01:48 UTC by HyeryongChoi

## 📄 Summary
> 
### 실행화면

<img src="https://github.com/woowacourse-teams/2023-zipgo/assets/24777828/70e2b0bd-78a5-48c0-9afe-5473c94c4f39" width="300px" alt="리뷰 실행화면" />

### 실행흐름
리뷰 추가: 리뷰 목록 > 리뷰 추가 버튼 클릭 > 별점 선택 페이지(`ReviewStarRating`) > 리뷰 추가 페이지(`ReviewAddition`)
리뷰 수정: 리뷰 목록 > 리뷰 수정 버튼 클릭 > 별점 선택 페이지 > 리뷰 추가 페이지
리뷰 삭제: 리뷰 목록 > 리뷰 삭제 버튼 클릭

### ReviewStarRating 페이지(별점 선택 페이지)
```tsx
  const onClickStar = (selectedRating: number) => {
    navigate(`/pet-foods/${petFoodId}/reviews/write/${selectedRating}/detail/${isEditMode}`, {
      state: { petFoodId, name, imageUrl, reviewDetail },
    });
  };
```
지금은 식품 상세정보에 있는 데이터(`petFoodId, name, imageUrl`)랑, 사용자 리뷰 정보(`reviewDetail`)를 페이지 이동할 때 state에 담아서 전달하고 있습니다! 

식품 상세정보는 나중에 api 요청해서 받아오도록 리팩터링할 예정입니다.
사용자 리뷰 정보도 전달, 전달하지 않고 > 리뷰 추가 페이지에서 리뷰 아이템 하나만 서버에 요청해서 받아오면 어떨까하는데 의견 주세요!

### useReviewForm
```tsx
if (action.type === ACTION_TYPES.SET_ADVERSE_REACTIONS) {
    const NO_ADVERSE_REACTION = '없어요';
    const hasAdverseReaction = state.adverseReactions.includes(action.adverseReaction);
    const hasNoAdverseReaction = state.adverseReactions.includes(NO_ADVERSE_REACTION);
    const isCurrentlyNoAdverseReactionSelected = action.adverseReaction === NO_ADVERSE_REACTION;
    const hasOnlyNoAdverseReaction =
      state.adverseReactions.length === 1 && isCurrentlyNoAdverseReactionSelected;
    const hasOnlyOneAdverseReactionWithoutNo =
      state.adverseReactions.length === 1 && !isCurrentlyNoAdverseReactionSelected;

    // 선택해제 - 이미 선택된 필터칩인 경우
    if (hasAdverseReaction) {
      if (hasOnlyNoAdverseReaction) return state; // 없어요만 선택된 경우 선택 해제 불가
      if (hasOnlyOneAdverseReactionWithoutNo) {
        // 1개만 선택된 상태에서 선택 해제하는 경우
        const filteredAdverseReactionsWithNo = state.adverseReactions
          .filter(item => item !== action.adverseReaction) // 해당 칩 선택 해제
          .concat(NO_ADVERSE_REACTION); // 없어요 추가

        return {
          ...state,
          adverseReactions: filteredAdverseReactionsWithNo,
        };
      }

      return {
        ...state,
        adverseReactions: state.adverseReactions.filter(item => item !== action.adverseReaction),
      };
    }

    // 선택 - '없어요'를 선택한 경우 다른 필터칩 선택 해제 및 '없어요' 선택
    if (isCurrentlyNoAdverseReactionSelected) {
      return { ...state, adverseReactions: [action.adverseReaction] };
    }

    // 선택 - '없어요'를 제외한 다른 필터칩을 선택한 경우(없어요 선택O) '없어요' 선택 해제 및 필터칩 선택
    if (hasNoAdverseReaction) {
      const adverseReactionsWithoutNo = [...state.adverseReactions, action.adverseReaction].filter(
        item => item !== NO_ADVERSE_REACTION,
      );

      return { ...state, adverseReactions: adverseReactionsWithoutNo };
    }

    // 선택 - '없어요'를 제외한 다른 필터칩을 선택한 경우(없어요 선택X) 필터칩 선택
    return { ...state, adverseReactions: [...state.adverseReactions, action.adverseReaction] };
  }
```

실행화면 예시를 보시면 리뷰 등록 폼에서 이상반응은 아래와 같은 로직으로 움직이도록 구현했는데요!
주말에 리팩터링을 하려고 하는데 어떻게 개선하면 좋을지... 의견 주시면 감사하겠습니다!

```
**없어요**
선택O > 다른 필터칩 선택 해제 및 없어요 선택
선택X > ‘없어요’만 선택된 경우 선택 해제 불가

**털이 푸석해요, 먹고 토해요, 눈물이 나요, 몸을 긁어요, 발을 핥아요**
선택O  > 없어요가 선택된 경우, 없어요 선택 해제 및 해당 필터칩 선택
선택X  > 1개만 선택된 상태에서 선택 취소하는 경우 없어요 선택 + 해당 칩 선택 해제
           > 여러개 선택된 상태에서 선택 해제하는 경우 해당 칩 선택 해제
```

### 기타 질문
- 리뷰 추가, 수정할 때 UI를 재사용하려다 보니 `isEditMode`, `rating`을 url 파라미터에 담아서 전달하고 있는데 괜찮을까요..?! 피드백 주세요!

- close #67 

## 🙋🏻 More
### 🕖 예상 작업 소요 시간
> 10시간

### 🕖 실제 작업 소요 시간
> 3일

2023-08-03 05:36 UTC, n0eyes commented
> 없어요
선택O > 다른 필터칩 선택 해제 및 없어요 선택
선택X > ‘없어요’만 선택된 경우 선택 해제 불가

>털이 푸석해요, 먹고 토해요, 눈물이 나요, 몸을 긁어요, 발을 핥아요
선택O  > 없어요가 선택된 경우, 없어요 선택 해제 및 해당 필터칩 선택
선택X  > 1개만 선택된 상태에서 선택 취소하는 경우 없어요 선택 + 해당 칩 선택 해제
           > 여러개 선택된 상태에서 선택 해제하는 경우 해당 칩 선택 해제

`Set` 자료 구조를 활용하면 불필요한 반복문이 줄어들어서 코드가 좀 더 간결해질 것 같아요!

> 식품 상세정보는 나중에 api 요청해서 받아오도록 리팩터링할 예정입니다.
사용자 리뷰 정보도 전달, 전달하지 않고 > 리뷰 추가 페이지에서 리뷰 아이템 하나만 서버에 요청해서 받아오면 어떨까하는데 의견 주세요!

서버에  요청해서 받아오는 의견에 동의합니다! 최대한 캐싱 기능을 활용하면 좋을 것 같아요!
추후 데스크탑 뷰에서 `url`로 직접 이동하는 경우도 대응할 수 있다는 장점도 따라올 것 같습니다~ 😄

2023-08-03 06:20 UTC, ksone02 commented on frontend/src/components/Review/ReviewForm/ReviewForm.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
왜 isEditMode나 reviewDetail, reviewDispatch를 의존하지 않나요?

2023-08-03 06:20 UTC, ksone02 commented on frontend/src/components/Review/ReviewItem/ReviewItem.tsx
> +          <TextButton type="button" aria-label="리뷰 수정" onClick={onClickEditButton}>
Link 말고 onClick을 사용한 이유가 있나요??

2023-08-03 06:56 UTC, HyeryongChoi commented on frontend/src/components/Review/ReviewForm/ReviewForm.tsx
> +      await editReviewMutation.editReview({ reviewId: reviewDetail.reviewId, ...review });
오오 그렇군요 수정하겠습니다~~

2023-08-03 07:00 UTC, n0eyes requested changes

2023-08-03 07:22 UTC, HyeryongChoi commented on frontend/src/components/Review/ReviewForm/ReviewForm.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
리뷰 수정 시 기본 데이터를 넣어주는 로직을 첫 화면이 렌더링된 이후에 1번만 실행하도록 하고싶어서 의존성에 빈배열을 넣어줬습니다! 그런데 별점 클릭 시 다음 페이지로 이동하니까 isEditMode나 reviewDetail, reviewDispatch를 의존성에 추가해도 되겠네요!!! 수정하겠습니다!!!

2023-08-03 07:25 UTC, HyeryongChoi commented on frontend/src/components/Review/ReviewItem/ReviewItem.tsx
> +          <TextButton type="button" aria-label="리뷰 수정" onClick={onClickEditButton}>
Link를 써본적이 없어서여... 공부해보고 적용할게여

2023-08-03 07:26 UTC, n0eyes approved these changes

2023-08-03 07:30 UTC, ksone02 approved these changes

2023-08-03 07:30 UTC, merged

2023-08-06 06:12 UTC, HyeryongChoi commented on frontend/src/pages/ReviewStarRating/ReviewStarRating.tsx
> +        </BackButton>
버튼 태그에 aria-label="뒤로가기"를 추가하면 '뒤로가기 버튼'이라고 읽기 때문에 이미지 alt에는 ""를 넣어줬어요!

2023-08-06 06:13 UTC, HyeryongChoi commented on frontend/src/pages/ReviewStarRating/ReviewStarRating.tsx
> +  };
피드백 감사합니당 그런데 해당 코드는 리팩터링 시 제거할 것 같아여!

2023-08-06 06:13 UTC, HyeryongChoi commented on frontend/src/pages/ReviewAddition/ReviewAddition.tsx
> +  const { petFoodId, name, imageUrl, reviewDetail } = { ...location.state };
오오 좋네요!!