refactor: PrimaryIngredient, Functionality 엔티티 분리
woowacourse-teams/2023-zipgo pull request #167
Opened 2023-08-05 11:20 UTC by wonyongChoi05

## 📄 Summary
> #165 

## 🙋🏻 More
>

2023-08-05 11:43 UTC, parkmuhyeun reviewed
string에서 entity로 수정하느라 고생했어요!
ㅋㅋㅋ 빨간색 보고 머리 뜯는 베베 생각하니 즐겁네요 ？

2023-08-05 11:43 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/auth/application/KakaoOAuthClient.java
> -import static org.springframework.http.HttpMethod.GET;
우리 static도 ide 설정 맞춰야 될 듯ㅋㅋㅋ

2023-08-05 11:43 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/petfood/domain/PetFood.java
> +    private Review review;
얘 이름 Reviews 어떤가여

2023-08-05 11:43 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/petfood/domain/PrimaryIngredient.java
> +        petFood.getPrimaryIngredients().add(this);
직접 꺼내서 추가해주는 것보다 petFood.addPrimaryIngredients()로 추가만 할 수 있도록 해주는 건 어떨까용

2023-08-05 11:43 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/petfood/application/PetFoodQueryService.java
> +//    }
요건 왜 주석처리만 했나여? test break?

2023-08-05 11:46 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/petfood/application/PetFoodQueryService.java
> +//    }
이거 #151 에서 더 자세하게 처리하려고 일단 주석처리 해놨습니다!

2023-08-05 11:47 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/petfood/domain/PrimaryIngredient.java
> +        petFood.getPrimaryIngredients().add(this);
좋습니다!

2023-08-05 11:52 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/petfood/domain/PetFood.java
> +    private Review review;
아 이게 Embedded 타입이어서 Review인지 Reviews인지 헷갈리네요.. 어쩐지 제가 Review로 바꾸니까 테스트에서 Review가 2개가 되서 엄청 헷갈리더라구요 ㅋㅋㅋ

2023-08-05 11:56 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/petfood/domain/PetFood.java
> +    private Review review;
저도 순간 리뷰 도메인이 바꼇나 싶었습니다 ㅋㅋㅋㅋㅋ

2023-08-05 11:59 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/application/KakaoOAuthClient.java
> -import static org.springframework.http.HttpMethod.GET;
이거 static import 설정 맞춰서 바뀐거에용ㅋㅋ

2023-08-05 12:03 UTC, parkmuhyeun submitted a review, later dismissed

2023-08-05 12:04 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/auth/application/KakaoOAuthClient.java
> -import static org.springframework.http.HttpMethod.GET;
아 ㅋㅋㅋㅋ 그러면 베베 reformating 한번 돌려주세요! 지금 한번에 다 잡아버리죠
뒤에 보는사람들껜 죄송합니다ㅎ

2023-08-05 12:40 UTC, wonyongChoi05 commented
> string에서 entity로 수정하느라 고생했어요! ㅋㅋㅋ 빨간색 보고 머리 뜯는 베베 생각하니 즐겁네요 ？

진짜 식겁했음 ㅋㅋㅋㅋㅋㅋㅋㅋ

2023-08-05 12:48 UTC, parkmuhyeun submitted a review, later dismissed
리포맷팅후에 다시 봤는데 import 관련된 건 안 바꿔주는거 같네요
리포맷팅이 import는 안 잡아주는건가..?
아니면 다른 건 다 완벽하다는 것인가..?

그 결과는 

바로... 바로..

바로..

다음 PR에서 확인해보시죠

2023-08-05 12:56 UTC, wonyongChoi05 commented
아 참고로 이번 PR 머지되면 지금 배포된 환경이 바로 뻗어버려서(pet_food dml 변경) 데이터베이스 형상관리 툴 도입되면 머지하는게 좋을 것 같습니다. (최대한 빠른 시일안에 논의하면 좋겠네요!)

2023-08-05 13:31 UTC, iamjooon2 approved these changes

2023-08-05 13:31 UTC, iamjooon2 commented on backend/src/test/resources/data.sql
> +       (2, '[고집] 롤로노아 로지',
롤로노아가 뭔지 검색해봤네요

2023-08-05 13:31 UTC, iamjooon2 commented on backend/src/test/java/zipgo/petfood/domain/ReviewsTest.java
> +                .map(별점 -> zipgo.review.domain.Review.builder().rating(별점).build())
빠이팅입니다

2023-08-05 14:28 UTC, kyY00n requested changes
정말정말 수고했어 베베
우리팀은 대체로 문제를 다른 사람이 해결하는 것 같다 : D.......
일단 질문 몇개 달았으요!

2023-08-05 14:28 UTC, kyY00n commented on backend/src/main/java/zipgo/petfood/domain/Functionality.java
> +    @ManyToOne(fetch = FetchType.LAZY)
ManyToOne, 엔티티 분리만으로도 쿼리가 불편했던 문제는 해결되겠지만
제가 작성했던 API의 근본적인 문제는 해결이 안될 것 같아용.

ex) '다이어트' 기능성을 가진 모든 식품을 조회

위 처럼 기능성으로 식품을 필터링 하려면 기능성도 여러 식품과 관계를 맺을 수 있어야할 것 같습니다.
베베 생각은 어떤가요?

2023-08-05 14:28 UTC, kyY00n commented on backend/src/main/java/zipgo/petfood/domain/PetFood.java
제가 JPA 초보라 좀 헷갈려서 질문드리겠습니당.
참조되는 엔티티에서 이런 식으로 하지 않아도 연관관계가 반영되나요?ㅜ..

```java
public void addPrimaryIngredient(PrimaryIngredient primaryIngredient) {
    this.primaryIngredients.add(primaryIngredient);
    primaryIngredient.changePetFood(this);
}
```

2023-08-05 23:47 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/petfood/domain/Functionality.java
> +    @ManyToOne(fetch = FetchType.LAZY)
로지가 말씀해주신 API의 근본적인 문제가 `'다이어트' 기능성을 가진 모든 식품을 조회` 요 부분이라면 아래의 쿼리로 조회 할 수도 있을 것 같아요!

```java
select pf From PetFood pf join fetch pf.functionality f where f.name = :name
List<PetFood> 다이어트_기능성을_가진_모든_식품_조회(@Param(name) String name);
```

사실 위 내용이 불가능한 쿼리가 아니라서 기능성이 여러 식품과 관계를 맺는다는게 잘 이해가 되지 않네요 ㅠ 로지 생각은 어떤가요??

2023-08-05 23:48 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/petfood/presentation/PetFoodController.java
>          FilterMetadataResponse metadata = buildMetadata();
앗 깜빡하고 삭제하지 못했군요! 현재 feature/#151 브랜치에서 작업은 모두 완료한상황입니다:)! 이 PR 머지되면 rebase하고 요청하겠습니다~!

2023-08-05 23:50 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/petfood/domain/ReviewsTest.java
> +        List<zipgo.review.domain.Review> 리뷰 = 별점_리스트.stream()
이게 다 Reviews를 Review로 바꿔본 제 잘못입니다 ㅠ 다시 원복 해놀게요!

2023-08-05 23:52 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/common/service/QueryServiceTest.java
>  public class QueryServiceTest {
로지 말이 맞습니다! 서비스 테스트들을 최대한 격리해보려고 노력했는데 계속 data.sql이 주입되어서 이것저것 해본 고생의 흔적인 것 같네요 ㅎㅎ... 삭제 해놓겠슴다~!

2023-08-05 23:55 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/brand/domain/fixture/BrandFixture.java
> +    public static Brand 오리젠() {
필터링 기능을 테스트하다 보니 브랜드를 여러 개 생성할 때 최대한 구분하기 쉽고 직관적인걸로 만들어보려다 보니 변수명이 이렇게 되어버렸네요 ㅎㅎ.. 혹시 좋은 네이밍 있나요!?

2023-08-06 04:36 UTC, kyY00n commented on backend/src/main/java/zipgo/petfood/domain/Functionality.java
> +    @ManyToOne(fetch = FetchType.LAZY)
베베말 들으니 그것도 맞네요. 구현의 차이일뿐..!

사실 제가 이런 생각을 하게 된 큰 계기가 따로 있어요. 며칠 전에 노아이즈랑 메타데이터 이야기를 했을 때, 상품마다 가지는 모든 기능성을 주는 개념보다는 우리가 분류한 기능성을 주는 것에 가깝다고 생각했아요.
그래서 우리 서비스가 분류한 기능성들이 있고, 그 분류에 식품이 포함되는 게 맞다고 생각했었고 그래서 이런 코멘트를 달게된 것 같아요😀
어떻게 보면 우리가 처음 만들었던 keyword와 유사한 것 같네요
아무튼 저의 생각은 그렇고, 베베 말고 맞으니 다른 팀원들과 함께 결정하면 좋을것같아요!

2023-08-06 04:44 UTC, kyY00n commented on backend/src/main/java/zipgo/petfood/domain/Functionality.java
> +    @ManyToOne(fetch = FetchType.LAZY)
아 노아이즈랑 얘기한거 자세히 말하자면,프론트엔드에서는 기능성 이름으로 조회하는 건 임시 방편으로 하고 추후엔 메타데이터에 포함된 id 정보로 조회하고 싶어했어요.

2023-08-06 04:50 UTC, kyY00n commented on backend/src/test/java/zipgo/brand/domain/fixture/BrandFixture.java
> +    public static Brand 오리젠() {
으음 인정~ 집사의고민 개발자면 저정돈 알아야하긴 하지

하지만 도메인 지식이 없는 사람 예를 들면 새로운 팀원(?)들이 봤을 때는 헷갈릴수도 있겠네요.
이를 방지할 대안으로는 브랜드1, 2 이런식으로 숫자를 붙이는 등의 방법이 있을 것같아요.
하지만 모두에게 approve 받은 내용이니 반영은 베베 맘입니다!

2023-08-06 06:42 UTC, wonyongChoi05 commented on backend/src/main/resources/application-dev.yml
> +      ddl-auto: create
앗 실수입니다 ㅎㅎ.. 원복해놀게용

2023-08-07 02:31 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/petfood/domain/PetFood.java
네네 맺어지긴 합니다!

2023-08-07 02:53 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/brand/domain/fixture/BrandFixture.java
> +    public static Brand 오리젠() {
저도 저희만 이해할 수 있는 코드보다는 다른 개발자들도 편하게 볼 수 있는 코드가 맞다고 생각해서 `오리젠_식품_브랜드_생성` 이렇게 변경했습니다! 굳이 브랜드 이름을 prefix로 붙인 이유는 아래와 같습니다!

* 식품_브랜드1_생성
  * 실제로 생성하고 해당 브랜드의 데이터를 검증할 때 BrandFixture를 봐야함
  * 1,2,3...과 같은 suffix가 붙음
* 오리젠_식품_브랜드_생성
  * 실제로 생성하면 오리젠 브랜드의 객체라는 것을 바로 판단할 수 있음

2023-08-07 11:30 UTC, kyY00n approved these changes
JPA 공부 열심히 할게용...

2023-08-09 01:37 UTC, parkmuhyeun submitted a review, later dismissed
컨플릭 해결하면 또 어프루브 풀려있겠군... ㅠㅠ

2023-08-09 04:30 UTC, iamjooon2 approved these changes
수고하셨습니다!

2023-08-09 06:38 UTC, parkmuhyeun approved these changes

2023-08-09 06:38 UTC, merged