refactor: 소셜 로그인 개선
woowacourse-teams/2023-zipgo pull request #170
Opened 2023-08-06 10:03 UTC by iamjooon2

## 📄 Summary
> #168 

AuthService if
카카오 인증 정보 사용시 @Value 대신 @ConfigurationProperties을 이용한 KakaoCredentials 사용하도록 변경
카카오 인증 정보 사용시 Secret Key 추가 사용 보안 강화
인터페이스 내 불필요한 접근제어자 제거
패키지 구조 변경

2023-08-06 13:21 UTC, parkmuhyeun reviewed
갈비 폼 미쳤다. 엄청 깔끔해지고 있꾼여 👍🏻👍🏻👍🏻

2023-08-06 13:21 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/auth/application/AuthService.java
> +                .orElseGet(() -> memberRepository.save(oAuthMemberResponse.toMember()));
👍🏻👍🏻

2023-08-06 13:21 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/auth/infra/kakao/KakaoOAuthClient.java
> -import zipgo.auth.application.dto.KakaoTokenResponse;
흠 이거 고쳐지고 있는중이겠지..?

2023-08-06 13:21 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/auth/infra/kakao/KakaoOAuthClient.java
> +            try {
여기 들여쓰기가 안 맞는거 같아여

2023-08-06 13:21 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/common/GlobalExceptionHandler.java
> +            AuthException.ResourceNotFound.class
여러분 이거 계속 늘어나는거 같은데 ㄱㅊ;;??

2023-08-06 13:21 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/common/GlobalExceptionHandler.java
> +    public ResponseEntity<ErrorResponse> handleUnauthorizedException(Exception exception) {
규웃

2023-08-06 13:21 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/auth/support/JwtProviderTest.java
> +    static
개행이 되있네용  근데 여기 static 맞나요?

2023-08-06 14:28 UTC, iamjooon2 commented on backend/src/test/java/zipgo/auth/support/JwtProviderTest.java
> +    static
아니 이게 뭐야;; BearerTokenExtractor 분리했어요

2023-08-06 14:29 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/infra/kakao/KakaoOAuthClient.java
> -import zipgo.auth.application.dto.KakaoTokenResponse;
얍얍
```java
package

import

static import
```
이순서로 맞춰놓음

아니면 내일 날잡고 넷이 모여서 정렬한 다음 바로 develop 브랜치 머지시켜도 될듯?

2023-08-07 02:34 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/common/GlobalExceptionHandler.java
> +            AuthException.ResourceNotFound.class
예외처리 리팩터링 해야할듯!

2023-08-07 02:42 UTC, wonyongChoi05 requested changes
수고했어 갈비!

2023-08-07 02:42 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/auth/support/JwtProviderTest.java
>  @SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
이건 제가 들은 이야기인데요! 실무에서는 SpringBootTest(애플리케이션 내의 모든 빈을 다 띄움 -> 따라서 굳이 필요하지 않은 빈들까지 띄우게 됨)과 DirtiesContext를 자제한다고 하기도 하더라구요! 갈비 생각은 어떤가요?

2023-08-07 02:42 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/auth/support/BearerTokenExtractorTest.java
>      void 요청_헤더의_Bearer_토큰을_추출할_수_있다() {
이거 엣지 케이스로 요청 헤더의 Bearer 토큰을 추출할 수 없을 때 예외를 던져준다면 해당 상황도 테스트 하는건 어떤가요!?

2023-08-07 10:00 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/infra/kakao/KakaoOAuthClient.java
> +            try {
매의 눈 민무 O.O

2023-08-07 10:01 UTC, iamjooon2 commented on backend/src/test/java/zipgo/auth/support/BearerTokenExtractorTest.java
>      void 요청_헤더의_Bearer_토큰을_추출할_수_있다() {
굳 좋습니다~!

2023-08-07 13:47 UTC, iamjooon2 commented on backend/src/test/java/zipgo/auth/support/JwtProviderTest.java
>  @SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
이 테스트에서 사용하는 JwtCredentials와 JwtProvider 모두 빈으로 등록되어있어서, 편하게 가져오려고 `@SpringBootTest` 어노테이션을 사용했는데요
아까 저녁먹으면서 이야기 했듯, 우리 집사의고민 빌드할 때 돌리는 테스트가 그래 오래 걸릴줄은 몰랐네요🫠
직접 JwtProvider 객체를 생성해서 사용하는 방식으로 변경할게요

2023-08-07 13:55 UTC, iamjooon2 commented on backend/src/test/java/zipgo/auth/support/BearerTokenExtractorTest.java
>      void 요청_헤더의_Bearer_토큰을_추출할_수_있다() {
굳 좋습니다~

2023-08-08 00:53 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/auth/support/JwtProviderTest.java
>  @SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
오 좋은 접근이네요! 사실 MockBean을 생각하고 있긴 했지만, 더 좋은 방법같기도 합니다 ㅎㅎ

2023-08-08 11:33 UTC, kyY00n submitted a review, later dismissed
질문 하나 달았으요 늦어서 죄송합니당 ㅎㅎ

2023-08-08 11:33 UTC, kyY00n commented on backend/src/test/resources/application.yml
> +    client-secret: my_secret
근데 저희 진짜 이거예요?? 이거 어떻게 관리중?

2023-08-08 13:05 UTC, iamjooon2 commented on backend/src/test/resources/application.yml
> +    client-secret: my_secret
테스트 패키지에 들어가있는 친구들은 다 가짜입니다ㅋㅋㅋㅋㅋㅋ
진짜는 ⭐️우리들만의 비밀장소⭐️에 있어요

2023-08-08 13:17 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/infra/kakao/dto/KakaoMemberResponse.java
>      }
매의 눈이시군요 로지 O_O
놓치고야 말았습니다

2023-08-08 13:51 UTC, iamjooon2 commented
이젠 보내주겠습니다

2023-08-08 15:21 UTC, iamjooon2 commented
[이젠 보내주겠습니다](https://hyeon9mak.github.io/avoid-dependencies-on-uncontrollable-factors/#%EC%9D%BC%EC%A0%95%EC%9D%80-%EC%A7%80%ED%82%A4%EC%A7%80%EB%A7%8C-%EB%B2%84%EA%B7%B8%EA%B0%80-%EB%A7%8E%EC%9D%80-%EA%B2%83-vs-%EC%9D%BC%EC%A0%95%EC%9D%80-%EB%AA%BB-%EC%A7%80%ED%82%A4%EC%A7%80%EB%A7%8C-%EB%B2%84%EA%B7%B8%EA%B0%80-%EC%97%86%EB%8A%94-%EA%B2%83)

2023-08-09 01:32 UTC, parkmuhyeun submitted a review, later dismissed

2023-08-09 01:32 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/auth/application/AuthService.java
> +    @Transactional
애는 왜 클래스단위에서 메서드단위로 옮겼나용?

2023-08-09 01:32 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/common/config/RestTemplateConfig.java
> +                .build();
굿

2023-08-09 01:34 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/application/AuthService.java
> +    @Transactional
아 어제 구구한테 물어보는 중에 바꾼걸 놓쳤군요.. 이것만 다시 클래스 위로 옮길게요

2023-08-09 01:40 UTC, parkmuhyeun approved these changes
아프라브~

2023-08-09 03:56 UTC, kyY00n approved these changes

2023-08-09 06:39 UTC, wonyongChoi05 submitted a review, later dismissed
수고!!

2023-08-10 03:38 UTC, parkmuhyeun approved these changes

2023-08-10 03:38 UTC, kyY00n approved these changes
수고했어 가비!!

2023-08-10 03:39 UTC, merged