refactor: 리뷰 기능 관련 코드 개선
woowacourse-teams/2023-zipgo pull request #171
Opened 2023-08-06 15:12 UTC by HyeryongChoi

## 📄 Summary
> 
- close #169 

### ReviewStarRating 페이지(별점 선택 페이지)
- [x] 식품 상세정보(`petFoodId, name, imageUrl`) api요청을 통해 받아오도록 수정
- [x] 사용자 리뷰 정보(`reviewId, tastePreference, stoolCondition, adverseReactions, comment`) api요청을 통해 받아오도록 수정
- [x] 사용자가 선택한 별점정보(`rating`) url 파라미터 대신 > `state`로 넘기도록 수정

### useReviewForm
- [x] `Set` 자료구조를 사용하여 리팩터링

### storybook
- [x] useParams 사용을 위한 스토리북 설정: Storybook-addon-react-router-v6, react-router 설치
- [x] msw 사용을 위한 스토리북 설정: msw-storybook-addon 설치

## 🙋🏻 More
리뷰 프로필사진이랑 로그인한 유저가 리뷰작성자인지 확인하는 로직은 api 명세를 다시 이야기 해보고 수정할 예정입니다!

### useLocation
`useLocation`을 이용한 `useValidLocation` 훅을 만들어 타입 단언(`as LocationState`)을 제거하려 하였으나

> useLocation() may be used only in the context of a <Router> component.

`useLocation`은 `<Router>` 컴포넌트의 컨텍스트 안에서 실행되어야 하고 커스텀 훅에서 직접적으로 `useLocation()`을 사용하는 것은 불가능하다고 하여 일단 보류함

### Storybook msw
스토리북에서 msw 설정을 해서 아래와 같이 뜨지만 
<img width="178" alt="image" src="https://github.com/woowacourse-teams/2023-zipgo/assets/24777828/07016b36-d128-4002-a378-be6ee72b8846">

`FoodInfoInReviewForm` 컴포넌트를 스토리북에서 확인한 결과
```tsx
const FoodInfoInReviewForm = (foodInfoInReviewFormProps: FoodInfoInReviewFormProps) => {
  const { petFoodId, rating } = foodInfoInReviewFormProps;
  const { foodData } = useFoodDetailQuery({ petFoodId: String(petFoodId) });

...
}
```
```tsx
export const getFoodDetail = async ({ petFoodId }: GetFoodDetailReq) => {
  const { data } = await client.get<GetFoodDetailRes>(`/pet-foods/${petFoodId}`);

  return data;
};
```

getFoodDetail이 실행되지 않아서 msw handler가 작동하지 않는 듯 합니다..
(getFoodDetail에 console.log를 추가해놓고 로컬에서 실행하면 찍히는데 스토리북에서는 안 찍힘, 네트워크 탭 확인해도 요청내용 없음..!)
원인이 뭘까요..

### 예상 소요시간 및 실제 소요시간
> 예상: 3시간
> 실제: 8시간

2023-08-08 14:18 UTC, n0eyes commented on frontend/src/hooks/review/useReviewForm.ts
> +    return { ...state, adverseReactions: Array.from(adverseReactionsSet) };
혹시 `adverseReactions `를 `Array`로 관리하는 이유가 있을까요!?

2023-08-08 14:18 UTC, n0eyes commented on frontend/src/pages/ReviewStarRating/ReviewStarRating.tsx
> +  const [rating, setRating] = useState(selectedRating);
훅으로 분리해도 좋을 것 같아요!

2023-08-08 14:18 UTC, n0eyes commented on frontend/src/pages/ReviewStarRating/ReviewStarRating.tsx
> +      state: { selectedRating, isEditMode, reviewId },
👍

2023-08-09 07:02 UTC, HyeryongChoi commented on frontend/src/hooks/review/useReviewForm.ts
> +    return { ...state, adverseReactions: Array.from(adverseReactionsSet) };
Array에서 Set으로 바꾸면 api명세를 수정해야해서 일단은 리듀서 안에서만 Set 자료구조를 사용해보았습니다!

2023-08-09 07:10 UTC, HyeryongChoi commented on frontend/src/components/Review/ReviewForm/FoodInfoInReviewForm/FoodInfoInReviewForm.tsx
> +  }
> 해당 라인이 실행되지 않지만 useQuery가 제공하는 error 혹은 isError 프로퍼티가 의미적으로 더 정확할 것 같아요!

동의합니다! 일단 요걸로 반영할게요!
```tsx
if(!foodData) return null 
```

2023-08-09 08:58 UTC, n0eyes commented on frontend/src/hooks/review/useReviewForm.ts
> +    return { ...state, adverseReactions: Array.from(adverseReactionsSet) };
`Set`으로 관리하다가 api에 전달되기 전에 `Array`로 파싱하는 것도 고려해보면 좋을 것 같아요!

2023-08-10 15:47 UTC, n0eyes requested changes

2023-08-12 08:04 UTC, HyeryongChoi commented on frontend/src/pages/ReviewStarRating/ReviewStarRating.tsx
> +    useReviewStarRating(location);
안에 넣어줬더니 `useLocation() may be used only in the context of a <Router> component.` 요런 에러가 떠서 분리했습니다!

2023-08-12 08:19 UTC, wonyongChoi05 commented
베베사료가 만족도 최고긴 하죠 ㅎㅎ

2023-08-12 08:19 UTC, wonyongChoi05 approved these changes

2023-08-12 14:41 UTC, ksone02 requested changes

2023-08-12 14:41 UTC, ksone02 commented on frontend/src/components/Review/ReviewForm/FoodInfoInReviewForm/FoodInfoInReviewForm.tsx
> +  if (!foodData) return null;
null을 리턴해주는 이유가 있나용

2023-08-12 15:19 UTC, HyeryongChoi commented on frontend/src/components/Review/ReviewForm/FoodInfoInReviewForm/FoodInfoInReviewForm.tsx
> +  if (!foodData) return null;
https://github.com/woowacourse-teams/2023-zipgo/pull/171#discussion_r1287153976
요 리뷰를 반영했습니다! 추후

2023-08-13 03:42 UTC, n0eyes approved these changes

2023-08-13 09:40 UTC, ksone02 approved these changes

2023-08-13 09:42 UTC, merged