feat: 식품 리스트 조회 페이징 추가
woowacourse-teams/2023-zipgo pull request #214
Opened 2023-08-09 10:34 UTC by parkmuhyeun

## 📄 Summary
- close: #209 

다음과 같은 파라미터로 요청하고

<img width="618" alt="image" src="https://github.com/woowacourse-teams/2023-zipgo/assets/76938931/f8bf7b00-d2b0-4c78-9398-1a0f6850c223">

- 페이징 사이즈는 첵스랑 20으로 하기로 했는데 프론트에서 주는 값만 바꾸면 되서 변경되도 상관없음.
- 페이징 원리는 해당 로직에 써놓을게요~

다음과 같이 응답

<img width="686" alt="image" src="https://github.com/woowacourse-teams/2023-zipgo/assets/76938931/d16039d0-6101-483b-a397-f261d95f68e4">

## 🙋🏻 More
>

2023-08-09 10:41 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/petfood/domain/repository/PetFoodQueryRepository.java
> +        return petFood.id.lt(lastPetFoodId);
프론트한테서 마지막 펫푸드Id 받아서 그거보다 작은 것들 size만큼 가져감(제일 처음엔 없을테니 null)

<img width="208" alt="image" src="https://github.com/woowacourse-teams/2023-zipgo/assets/76938931/76789b97-be05-40cd-a7f1-e107d89495ff">


참고로
BooleanExpression 자리에 null이 반환되면 조건문에서 자동으로 제거

2023-08-09 11:22 UTC, HyeryongChoi commented on backend/src/main/java/zipgo/petfood/domain/repository/PetFoodQueryRepository.java
> +        return petFood.id.lt(lastPetFoodId);
![confused_dog](https://github.com/woowacourse-teams/2023-zipgo/assets/24777828/6e6347fb-ab72-478d-b1f2-c9ccd0ce9c9d)

2023-08-10 01:19 UTC, kyY00n requested changes
갑자기 바꾸느라 수고하셨습니다 :D
리뷰 조회 때 맛있게 먹겠씁니다

2023-08-10 01:19 UTC, kyY00n commented on backend/src/main/java/zipgo/petfood/application/PetFoodQueryService.java
> +            Pageable pageable
DTO 쓰는 거 어떨까요?

2023-08-10 01:19 UTC, kyY00n commented on backend/src/test/java/zipgo/acceptance/PetFoodAcceptanceTest.java
> +                            fieldWithPath("totalCount").description("전체 식품 개수").type(JsonFieldType.NUMBER),
AHA! 화면 요소이군요... (추측성 OK)

2023-08-10 01:19 UTC, kyY00n commented on backend/src/test/java/zipgo/acceptance/PetFoodAcceptanceTest.java
> +                            parameterWithName("size").description("식품 페이징 사이즈")
논의 즁 ~~
논의 끝 ~~
optional 추가 하고 알려주기로 함

2023-08-10 02:20 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/petfood/presentation/PetFoodController.java
> +            Pageable pageable
size만 받도록 반영했슴둥

2023-08-10 02:34 UTC, kyY00n submitted a review, later dismissed
수고하셨습니다!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!11

2023-08-10 02:34 UTC, kyY00n commented on backend/src/main/java/zipgo/petfood/application/dto/FilterDto.java
> +public record FilterDto(
완 벽..

2023-08-10 03:01 UTC, iamjooon2 submitted a review, later dismissed
고생하셨습니다!

2023-08-10 03:26 UTC, kyY00n approved these changes

2023-08-10 03:32 UTC, iamjooon2 approved these changes

2023-08-10 03:38 UTC, merged