[FEAT] 리뷰 페이지네이션
woowacourse-teams/2023-zipgo pull request #219
Opened 2023-08-10 10:51 UTC by kyY00n

## 📄 Summary
> 리뷰 페이지네이션 했어요

## 🙋🏻 More
> 내가 나인지 콧물인지.

data.sql 때문에 고생 좀 했어여..
앞으로 data.sql에 id 포함해서 추가한다면 꼭 다음을 실행해줘야겠어여..
```
alter table 테이블 alter column 아이디 restart with 그다음수
```

오늘은 기가 빨려고 일단 제출하고 휴식.. 리뷰 반영하며 더 고칠게여

2023-08-10 13:22 UTC, wonyongChoi05 requested changes
로지 수고했어~!! 코드를 잘짜서 별로 남긴게 없네... 근데 로지 커밋하면서 해킹당한듯..? 단위 테스트가 안보여!
++ data.sql이랑은 화해한거지..?

2023-08-10 13:22 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/review/domain/repository/ReviewQueryRepositoryImplTest.java
> +    }
광기....... 로지 많이 화나셨었군요....

2023-08-10 13:22 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/review/domain/repository/ReviewQueryRepositoryImplTest.java
> +
요런 엣지 케이스들도 있을 것 같아요 ㅎㅎ

* 결과가 없을 때 빈 리스트 반환하는지
* cursor가 음수일 때 어떻게 동작하는지

2023-08-10 14:20 UTC, parkmuhyeun reviewed
zzzz 고생했어 원래 테스트가 제일 짜증나는법..
테스트 맨날 짜면서도 느끼는거지만 테스트 어떻게 잘 짬?

2023-08-10 14:20 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/domain/repository/ReviewQueryRepositoryImpl.java
> +public class ReviewQueryRepositoryImpl implements ReviewQueryRepository {
리뷰는 컬렉션들을 비교하는게 없기 때문에 딱히 Querydsl 쓸 필요 없다고 생각했었는데 querydsl로 하신 이유가 있나요?

2023-08-10 14:20 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/domain/repository/ReviewQueryRepositoryImpl.java
> +    public List<Review> findAllByPetFoodId(Long petFoodId, int size, Long cursor) {
cursor가 뭔가여?

2023-08-10 14:20 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/review/domain/repository/ReviewQueryRepositoryImplTest.java
> +                ReviewFixture.극찬_리뷰_생성(memberRepository.save(MemberFixture.식별자_없는_멤버()), 식품),
와우.. 로지 많이 아팠나보네 반복문 어디갔어ㅋㅋㅋㅋㅋㅋ

calm down.. calm down..

2023-08-10 14:20 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/review/presentation/ReviewControllerTest.java
> +                            parameterWithName("lastReviewId").description("이전 페이지의 마지막 리뷰 id").optional()),
👍🏻

2023-08-10 14:20 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/review/presentation/ReviewControllerTest.java
> +                    ReviewFixture.극찬_리뷰_생성(memberRepository.save(MemberFixture.식별자_없는_멤버()), 식품)
zzzzzzzzzzz

2023-08-10 14:48 UTC, kyY00n commented on backend/src/main/java/zipgo/review/domain/repository/ReviewQueryRepositoryImpl.java
> +public class ReviewQueryRepositoryImpl implements ReviewQueryRepository {
@parkmuhyeun 컬렉션을 비교한다는 말을 이해하지 못했습니다
querydsl 사용한건, 제 다음 작업인 필터링과 정렬 기능을 추가 할 때 쿼리가 매우 동적으로 바뀔 것 같았기 때문입니다

2023-08-10 14:51 UTC, kyY00n commented on backend/src/main/java/zipgo/review/domain/repository/ReviewQueryRepositoryImpl.java
> +    public List<Review> findAllByPetFoodId(Long petFoodId, int size, Long cursor) {
변수명 바꿔야겠어요.

2023-08-10 14:51 UTC, kyY00n commented on backend/src/test/java/zipgo/review/domain/repository/ReviewQueryRepositoryImplTest.java
> +                ReviewFixture.극찬_리뷰_생성(memberRepository.save(MemberFixture.식별자_없는_멤버()), 식품),
아직 드래프트인데...ㅜ

2023-08-10 17:11 UTC, kyY00n reviewed
리뷰 포인트입니다!

2023-08-10 17:11 UTC, kyY00n commented on backend/src/main/java/zipgo/review/presentation/ReviewController.java
>      //TODO petFoodId 쿼러파라미터로 변경
이 TODO는 아마, 다음 작업에서 하게 될 것 같습니다.

2023-08-10 17:11 UTC, kyY00n commented on backend/src/test/java/zipgo/common/GlobalExceptionHandlerTest.java
> +        given(reviewController.getReview(any()))
int 모킹이 까다로워서 대상을 바꿨습니다.

2023-08-10 17:11 UTC, kyY00n commented on backend/src/test/java/zipgo/member/domain/fixture/MemberFixture.java
> +        return Member.builder().email(email).profileImgUrl("사진").name("이름").build();
email에 unique 조건이 걸려있어서, 여러 번 save하기 편하게 만들었습니다.

2023-08-10 17:11 UTC, kyY00n commented on backend/src/test/java/zipgo/review/domain/repository/ReviewQueryRepositoryImplTest.java
> +    private PetFoodRepository petFoodRepository;
이런 반복되는 주입코드를, 상속으로 해결하는 팀들도 있던데 다들 어떻게 생각하세요??

2023-08-10 17:11 UTC, kyY00n commented on backend/src/test/java/zipgo/review/domain/repository/ReviewQueryRepositoryImplTest.java
> +
지금봤네요.. ㅎ .... 일단 동작은 이렇게 합니다.
- 결과가 없을 때 빈 리스트를 반환합니다.
- cursor가 음수일 때가 바로 결과가 없을 때입니다.

2023-08-11 07:31 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/domain/repository/ReviewQueryRepositoryImpl.java
> +public class ReviewQueryRepositoryImpl implements ReviewQueryRepository {
여러 타입들이 리스트로 들어와서 비교하는거 말한 것임다.
곧 필터링 작업 들어오니깐 좋을거 같네여 👍🏻👍🏻

2023-08-11 07:46 UTC, parkmuhyeun reviewed
draft하고 pr하니깐 전에 봤던게 뭔지 모르겠어서 풀로 다시 봤읍니다..ㅠㅜ

2023-08-11 07:46 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/application/dto/GetReviewQueryDto.java
> +        Long lastReviewId) {
) 앞에 공백해주실 수 있나요..ㅋㅋㅋㅋ

2023-08-11 07:46 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/presentation/ReviewController.java
>      //TODO petFoodId 쿼러파라미터로 변경
하고 프론트행님덜한테도 고쳐달라 해야 될 듯

2023-08-11 07:46 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/presentation/ReviewController.java
> +        GetReviewQueryDto dto = new GetReviewQueryDto(petFoodId, size, lastReviewId);
reviewQueryDto 어떤가요 dto는 얘가 너무 불쌍한데요..ㅋㅋㅋㅋ

2023-08-11 07:46 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/review/domain/repository/ReviewQueryRepositoryImplTest.java
> +    private PetFoodRepository petFoodRepository;
좋아용 근데 repository 같은 경우 완전 중복되는게 애매하긴하네요.

2023-08-11 08:27 UTC, iamjooon2 approved these changes
로지 테스트가 정말 꼼꼼하네요...! 

야무진 코드 잘 읽었습니다 :D

2023-08-11 08:27 UTC, iamjooon2 commented on backend/src/test/java/zipgo/common/config/QueryDslTestConfig.java
>  @TestConfiguration
또 하나 배워가는군요!

2023-08-11 08:27 UTC, iamjooon2 commented on backend/src/test/java/zipgo/review/domain/repository/ReviewQueryRepositoryImplTest.java
> +        assertThat(조회한_리뷰_아이디).allMatch(id -> id < 커서);
`allMatch( predicate )` 배워갑니다.

2023-08-11 11:12 UTC, kyY00n commented on backend/src/test/java/zipgo/common/config/QueryDslTestConfig.java
>  @TestConfiguration
이건 아기가 해놓은 것입니다

2023-08-11 11:13 UTC, kyY00n commented on backend/src/test/java/zipgo/review/domain/repository/ReviewQueryRepositoryImplTest.java
> +    private PetFoodRepository petFoodRepository;
@parkmuhyeun 주입이 성능을 많이 느리게할까요? 저는 @DataJpaTest 사용시 어차피 빈으로 등록되니 다 넣는것도 나쁘지 않다는 생각이.. 문득 들었습니다 :D..

2023-08-11 11:14 UTC, kyY00n commented on backend/src/test/java/zipgo/review/domain/repository/ReviewQueryRepositoryImplTest.java
> +    private PetFoodRepository petFoodRepository;
@parkmuhyeun `@DataJpaTest` 사용하면 repository들은 전부 뜨잖아요! 그래서 괜찮다고 생각이 들기도 하는데, 주입도 테스트 속도를 많이 느리게 하려나요?

2023-08-11 11:15 UTC, kyY00n commented on backend/src/test/java/zipgo/review/domain/repository/ReviewQueryRepositoryImplTest.java
> +        assertThat(조회한_리뷰_아이디).allMatch(id -> id < 커서);
헉 고마워요 저는 가비한테 배움의 자세를 배웠..

2023-08-12 02:53 UTC, wonyongChoi05 submitted a review, later dismissed
로지 너무 수고했어! PR을 너무 늦게봐줬넹 ㅠ 간단하게 몇 개 더 남겨봤는데 일단 어푸룹은 해뒀어! 반영은 맘대루~

2023-08-12 02:53 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/application/ReviewQueryService.java
> +        return GetReviewsResponse.from(reviews);
Querydsl 자체가 JPA 확잠 모듈이긴 하지만, 꽤나 외부 환경적으로 종속되는 설정들이 많기도 해서요.. 로지가 그런걸 감안해도 Querydsl의 효율이 더 잘 나올 것 같으면 조회 관련 쿼리를 QuerydslRepository쪽으로 옮기는 것도 정말 좋을 것 같아요. 코드가 엄청 깔끔해지니까 ㅎㅎ;

2023-08-12 02:53 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/common/config/QueryDslTestConfig.java
>  @TestConfiguration
ㄷㄷ;; 로지 빡고수

2023-08-12 02:53 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/member/domain/fixture/MemberFixture.java
> +        return Member.builder().email(email).profileImgUrl("사진").name("이름").build();
센스~ 굿!!!

2023-08-12 02:53 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/review/domain/repository/ReviewQueryRepositoryImplTest.java
> +    private PetFoodRepository petFoodRepository;
개인적으로 그런 방식도 좋을 것 같긴 한데, 레포지토리단에 한하긴 하더라도 동작방식이 너무 SpringBootTest 같은 느낌이 드는건 어쩔수 없네요 ㅠ 그리고 Querydsl 레파지토리를 별도의 컴포넌트로 분리한다면 이것도 빈으로 등록해줘야 할텐데, RepositoryTest를 만들어서 상속하는건 필요하지 않은 빈들도 꽤나 많이 등록될 것 같아요!(물론 성능상으로 안쓴 것 보단 느려지긴 하겠지만 얼마나 느린지는 잘 모름다! 당당^^)

2023-08-12 04:07 UTC, kyY00n commented on backend/src/main/java/zipgo/review/application/ReviewQueryService.java
> +        return GetReviewsResponse.from(reviews);
@parkmuhyeun 그게, 실은 저도 베베 말처럼 QueryRepository라는 걸 만든 이상 조회관련한 모든 쿼리가 다 QueryRepository에 있는게 맞지 않나? 라는 생각이 들더라구요..
다만 JpaRepository의 find~ 메서드를 무조건 막자니 그것도 비효율적인 것 같아서 고민이었어요. 일단은 이 pr에서는  여기까지 하고 다로 이슈를 파서 하는게 좋을 것 같기도 해요.

2023-08-12 04:08 UTC, kyY00n commented on backend/src/test/java/zipgo/review/domain/repository/ReviewQueryRepositoryImplTest.java
> +    private PetFoodRepository petFoodRepository;
ㅋㅋㅋ이해했습니다! 저도 설득하기에 충분한 근거가 없으니 주입 상속에 대한 이야기는 차차 더 해보시죠.

2023-08-13 09:00 UTC, parkmuhyeun approved these changes

2023-08-13 09:01 UTC, iamjooon2 approved these changes

2023-08-13 09:02 UTC, merged