[BE] 반려동물 도메인 모델 작성
woowacourse-teams/2023-zipgo pull request #220
Opened 2023-08-10 13:55 UTC by iamjooon2

## 📄 Summary
>  #203 

일단 사용자당 하나의 할 반려동물만 등록할 수 있기에, Member와의 연관관계는 1:1로 설정했습니다

## 🙋🏻 More
>

2023-08-10 14:08 UTC, wonyongChoi05 requested changes
수고했어 갈비! 간단하게 남겼으니 확인해줘~

2023-08-10 14:08 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/member/domain/Member.java
>      private String profileImgUrl;
s3 받으면 이미지 도메인 분리하나요!? 그리고 프로필 이미지는 option 아닐까요??

2023-08-10 14:08 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/pet/domain/Pet.java
> +    @JoinColumn(nullable = false)
어노테이션 순서!

2023-08-10 14:21 UTC, iamjooon2 commented on backend/src/main/java/zipgo/member/domain/Member.java
>      private String profileImgUrl;
s3 받은 후 함께 고려해보죠🫠
프로필 이미지는 카카오 로그인시 필수동의 항목이라 nullable = false로 해두었습니다~

2023-08-10 14:26 UTC, iamjooon2 commented on backend/src/main/java/zipgo/pet/domain/AgeGroup.java
> +                .filter(it -> it.start <= age && age < it.end)
AgeGroup을 age로 사용하면 더 헷갈리지 않을까요?

필드는 쉬운 단어를 쓰고싶어서 start, end를 사용했는데, 지금보니 잘 안읽히네요
각각 lowerBound, upperBound로 변경해둘게요

2023-08-10 14:27 UTC, iamjooon2 commented on backend/src/main/java/zipgo/pet/domain/AgeGroup.java
> +                .filter(it -> it.start <= age && age < it.end)
ageGroup으로 변경할게요~!

필드는 쉬운 단어를 쓰고싶어서 start, end를 사용했는데, 지금보니 잘 안읽히네요
각각 lowerBound, upperBound로 변경해둘게요

2023-08-10 14:30 UTC, parkmuhyeun reviewed
고생해따이 갈비쿤~

2023-08-10 14:30 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/pet/domain/AgeGroup.java
> +    ;
마지막에 콤마 지우고 ;로 끝내주십쇼.. 뭔가 불편하네요 ㅋㅋㅋㅋ

2023-08-10 14:30 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/pet/domain/BreedsSize.java
> +    ;
ditto

2023-08-10 14:30 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/pet/domain/Gender.java
> +    ;
ditto

2023-08-10 14:32 UTC, iamjooon2 commented on backend/src/main/java/zipgo/pet/domain/Gender.java
> +    FEMALE,
만들면서 생각난건데, 중성화 추가하면 좋을 것 같아요

2023-08-10 14:41 UTC, iamjooon2 commented on backend/src/main/java/zipgo/pet/domain/AgeGroup.java
> +    ;
이게 처음 보면 이해 못하실 수도 있는데요
Enum에 새로운 요소 추가하는 경우, 위같은 구조가 훨씬 간편하게 추가할 수 있어서 위와 같이 작성해요

우선 위 AgeGroup에 SOMETHING이라는 상수를 추가한다고 가정할 때,

그냥 끝내게 되면, 먼저 NONE; 으로 마우스 포인터를 가져다댄 후, <- 키를 눌러서 왼쪽으로 한 칸 이동한 후, ,를 붙인 다음 Enter를 치고, SOMETHING을 입력하는 식으로 작성할 것 같아요!

그런데 위 구조를 사용하면, SENIOR,으로 마우스 포인터를 가져다댄 후, 바로 Enter를 치고 SOMETHING을 입력할 수 있기 때문에, 해야할 일이 줄어들어서 저는 위 구조를 사용해요!
추가적으로 저는 command + D 단축키도 라인을 복사할 때 많이 사용하는데, 해당 단축키를 사용할 때에도 위 구조가 훨씬 편하기 때문에 위 구조를 사용한답니다~

2023-08-10 16:47 UTC, kyY00n commented on backend/src/main/java/zipgo/member/domain/Member.java
>      private String profileImgUrl;
저는 카카오 로그인은 하나의 수단일 뿐이라고 생각하는데,
카카오에서 가져온다고 해서 필수로 해야하나 싶어요

2023-08-10 16:50 UTC, kyY00n commented on backend/src/main/java/zipgo/pet/domain/AgeGroup.java
> +    private final int upperBound;
조금 헷갈려요!
이상, 미만 이 잘 드러나는 이름으로 바꿔보는거는.. 어떨까요?
greaterThan / lessThanOrEqual

2023-08-10 16:54 UTC, kyY00n commented on backend/src/main/java/zipgo/pet/domain/Pet.java
> +    private Integer age;
우리 나이 숫자가 아니라 생년으로 가지고 있기로 했던 것 같은데 그냥 나이로 둔 이유가 있나요?

2023-08-10 16:56 UTC, kyY00n commented on backend/src/main/java/zipgo/pet/domain/Pet.java
> +    private Integer age;
이건 상상인데
만~약에 2023년에 등록한 동물 프로필 정보가 50년 후에도 남아있다면 이 아이 연령대는 어떻게 표기해야할까요..?

2023-08-11 06:42 UTC, iamjooon2 commented on backend/src/main/java/zipgo/member/domain/Member.java
>      private String profileImgUrl;
음~ 좋아요 외부 인프라에 우리 도메인이 의존하고 있는 셈이네요
같이 반영해서 올릴게요~!

2023-08-11 07:07 UTC, iamjooon2 commented on backend/src/main/java/zipgo/pet/domain/Pet.java
> +    private Integer age;
생년으로 변경했어요~!

애매한 부분인 것 같아요ㅠ 그렇다고 Integer.MAX_VALUE 같은 값을 넣는 것은 더 아닌 것 같구요
이건 50년 뒤의 집사의고민 개발자가 고민할 부분이라고 생각하고 남겨뒀답니다 하하...

2023-08-12 04:26 UTC, kyY00n requested changes
ㅜㅜ 어프루브 하러 왔는데 .. 놀라서 질문

2023-08-12 04:26 UTC, kyY00n commented on backend/src/main/java/zipgo/pet/domain/Breeds.java
> +public class Breeds {
@iamjooon2 저 미처 저번에는 보지 못해서ㅜ 너무 다르게 생각했던 부분이라 질문합니다. Breeds 를 embeddable로 구현한 이유가 궁금해요.
제 생각엔 Breeds 는 엔티티가 되어야할것 같아서요.

이렇게 되면 견종으로 부터 연결된 것들을 찾고, 집계하는 연산들이 어렵지 않을까요?

2023-08-12 04:26 UTC, kyY00n commented on backend/src/test/java/zipgo/pet/domain/AgeGroupTest.java
> +    @ParameterizedTest(name = "한 살 이상 일곱 살 미만은 ADULT다. 입력 = {0}")
👍🏻

2023-08-12 04:31 UTC, iamjooon2 commented on backend/src/main/java/zipgo/pet/domain/Breeds.java
> +public class Breeds {
이거 게속 고민했던 부분이고 커밋로그 보면 실제로 엔티티로 뺐다가 다시 넣었다가 하고있었어요ㅠㅠ

반영할게용~

2023-08-12 04:31 UTC, kyY00n commented on backend/src/main/java/zipgo/pet/domain/Breeds.java
> +public class Breeds {
전 breed Size도 마찬가지로 생각해용.
breedSize라는 이름처럼 breed 에 속하는 것이 아니라 PetSize라는 별도의 도메인이 있어야 될 것 같아요.
왜냐하면 소/대/형견 이라는 개념은 견종에 포함되는 것이 아니기 때문인데요. (그렇기 때문에 믹스견은 입력을 받는거죵)
소/대/형견 이라는 분류 중 어디에 속해있느냐를 Breeds가 관계의 주인이 되어 가지고 있는게 적절할 것 같습니다.

(소/대/형견 으로도 필터링 해야할 기능이 벌써 있기도 하고요..)

2023-08-12 04:32 UTC, kyY00n commented on backend/src/main/java/zipgo/pet/domain/Breeds.java
> +public class Breeds {
@iamjooon2 한번 더 확인해주세여!! ㅋㅋㅋㅋ

2023-08-12 14:09 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/pet/domain/AgeGroup.java
> +    ;
제 개인적인 의견으로 이거 저도 좀 불편하긴 한데, 뭔가 List에서도 마지막 요소 뒤에 ,(콤마) 안 붙이고 select(요소,요소,)이렇게 적지도 않듯이(물론 지원 자체를 안하긴 하지만) enum도 일관성있게 가져가는게 낫지 않을까요? 특히 AgeGroup이라는 Enum에 얼마나 더 많은 요소가 추가될지도 잘 모르겠어요. 만약에 앞으로 나이대가 2개 이상만 추가되도 납득 가능할 것 같은데, 그게 아니라면 가독성을 좀 더 중시하는게 좋지 않을까요?

2023-08-12 14:09 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/pet/domain/Pet.java
> +    private Integer age;
> 이건 상상인데 만~약에 2023년에 등록한 동물 프로필 정보가 50년 후에도 남아있다면 이 아이 연령대는 어떻게 표기해야할까요..?

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 로지 너 N이야??

2023-08-12 14:31 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/pet/domain/AgeGroup.java
> +    ;
얘가 딱히 많지도 않고 앞으로 많이 추가될 거 같지도 않아서 전 가독성이 더 좋을거 같긴 합니닷.
근데 의견일뿐이니 반영은 자유임당

2023-08-12 14:33 UTC, parkmuhyeun approved these changes

2023-08-12 16:03 UTC, iamjooon2 commented on backend/src/main/java/zipgo/pet/domain/AgeGroup.java
> +    ;
@wonyongChoi05 저렇게 작성한 이유를 적은 것이고, 이 AgeGroup 말고도 다른 모든 Enum들을 위와 같이 작성했어요
저도 개인적인 의견 달자면, 저는 가독성이 나쁘다고 느끼지 못했어요
오히려 위처럼 작성한 코드를 더 많이 접해서, `자바 Enum 사용할 때 일반적인 코드 스타일이구나`라고 여기고 있었어요

그리고 코드 보시면 알겠지만 이미 반영되어있어요~

2023-08-12 16:04 UTC, iamjooon2 commented on backend/src/main/java/zipgo/pet/domain/AgeGroup.java
> +    ;
@wonyongChoi05  저렇게 작성한 이유를 적은 것이고, 이 AgeGroup 말고도 다른 모든 Enum들을 위와 같이 작성했어요
저도 개인적인 의견 달자면, 오히려 위처럼 작성한 코드를 더 많이 접했고, `자바 Enum 사용할 때 일반적인 코드 스타일이구나`라고 여기고 있었어요. 덕분에 가독성이 안좋거나 불편함은 전혀 느끼지 못했구요.

그리고 코드 보시면 알겠지만 이미 반영되어있답니다 하하...

2023-08-12 16:30 UTC, iamjooon2 commented on backend/src/main/java/zipgo/pet/domain/AgeGroup.java
> +    ;
@wonyongChoi05  저렇게 작성한 이유를 적은 것이고, 이 AgeGroup 말고도 다른 모든 Enum들을 위와 같이 작성했어요
저도 개인적인 의견 달자면, 오히려 위처럼 작성한 코드를 더 많이 접했고, `자바 Enum 사용할 때 일반적인 코드 스타일이구나`라고 여기고 있었어요. 덕분에 가독성이 안좋다던지, 불편하다는 것은 전혀 느끼지 못했구요.


그리고 이미 반영되어있답니다 하하...

2023-08-12 16:33 UTC, iamjooon2 commented on backend/src/main/java/zipgo/pet/domain/AgeGroup.java
> +    ;
@wonyongChoi05 단순히 저렇게 작성한 이유를 적은 것이고, 이 AgeGroup 말고도 다른 모든 Enum들을 위와 같이 작성했어요
저도 개인적인 의견 달자면, 오히려 위처럼 작성한 코드를 더 많이 접했고, `자바 Enum 사용할 때 일반적인 코드 스타일이구나`라고 여기고 있었어요. 덕분에 가독성이 안좋다던지, 불편하다는 것은 전혀 느끼지 못했구요.

그리고 이미 반영되어있답니다 하하...

2023-08-12 16:56 UTC, kyY00n requested changes
졸린데 죄송합니다.. 진짜 딱하나만 더 고쳐주세요ㅜㅜ ㅋㅋ.ㅋ 쿠ㅜㅜ쿠ㅜ

2023-08-12 17:56 UTC, kyY00n approved these changes
굳!! 빠르네요 가비

2023-08-13 07:29 UTC, parkmuhyeun approved these changes

2023-08-13 10:09 UTC, wonyongChoi05 approved these changes

2023-08-13 10:12 UTC, merged