feat: 무한스크롤 적용
woowacourse-teams/2023-zipgo pull request #228
Opened 2023-08-11 04:36 UTC by HyeryongChoi

## 📄 Summary
식품목록 조회 시, 커서 기반 페이지네이션으로 무한스크롤 기능을 구현합니다.

### 커서 기반 페이지네이션
이전에 로드한 데이터 중 마지막 데이터 Id(cursor, 고유한 식별자)를 서버에 전달하여 그 이후부터 일정 개수의 데이터를 가져오는 방식입니다.

### useInfiniteQuery
- `getNextPageParam`: 서버에서 보내준 totalCount값과 현재 foodList의 길이를 비교해서 마지막 페이지라면 `null`을 반환하고 마지막 페이지가 아니라면 다음 요청의 파라미터 값인 마지막 식품의 id(`foodList.at(-1).id`)를 반환하도록 구현할 예정입니다.
- `hasNextPage`: 현재 페이지가 마지막페이지인지 여부를 확인합니다.
- `isFetchingNextPage`: 사용자가 스크롤을 다시 위로 올렸다가 내렸을 때 데이터 요청 도중 중복으로 데이터를 요청하는 문제를 해결하기 위해 데이터 요청 상태를 확인합니다.

### IntersectionObserver
무한스크롤 구현 시, 다음 페이지 데이터 호출 시점을 판단하기 위해 사용할 예정입니다.

- ViewPort에 Target요소가 포함 & `hasNextPage`가 `true` & `isFetchingNextPage`가 `false`인 경우 다음 페이지의 데이터를 호출합니다.

**Scroll event를 감지하는 방법**으로도 무한스크롤을 구현할 수 있지만 이 방식은 스크롤 위치가 바뀔 때마다 불필요한 이벤트가 발생하기 때문에 스크롤 이벤트 리스너가 빈번하게 호출되어 성능이 저하될 수 있는 문제가 있습니다. 또한 원하는 시점에 정확하게 이벤트를 제어하고 처리하는 것이 어려울 수 있습니다. 이런 문제들을 고려하여 **IntersectionObserver**를 사용하여 구현하려고합니다.

### 🙋🏻 More

## ❗️도움❗️

```tsx
// src/hooks/food.ts

export const useInfiniteFoodListScroll = () => {
  const queriesForPaging = useValidQueryString<KeywordForPaging>(['lastPetFoodId', 'size']);
  const queriesForFiltering = useValidQueryString<KeywordEn>([
    'nutritionStandards',
    'mainIngredients',
    'brands',
    'functionalities',
  ]);
  const queries = { ...queriesForPaging, ...queriesForFiltering };

  const { foodList, fetchNextPage, hasNextPage, isFetchingNextPage, refetch } =
    useFoodListInfiniteQuery(queries);

  const executeFoodListInfiniteQuery = useCallback(
    (entries: IntersectionObserverEntry[]) => {
      entries.forEach(entry => {
        const canLoadMore = entry.isIntersecting && hasNextPage && !isFetchingNextPage;

        if (canLoadMore) fetchNextPage();
      });
    },
    [hasNextPage, isFetchingNextPage, fetchNextPage],
  );

  const targetRef = useRef(null);

  useEffect(() => {
    const observer = new IntersectionObserver(executeFoodListInfiniteQuery, { threshold: 0.1 });

    if (targetRef.current) observer.observe(targetRef.current);

    return () => observer.disconnect();
  }, [executeFoodListInfiniteQuery]);

  // useEffect(() => {
  //   // refetch();
  // }, [Object.values(queries)]);

  return { foodList, hasNextPage, refetch, targetRef };
};
```
위 훅은 Landing페이지에서 사용합니다.
```tsx
const Landing = () => {
  const { foodList, hasNextPage, targetRef } = useInfiniteFoodListScroll();

  if (!foodList) return null;
...
}
```
첫화면에서는 무한스크롤이 잘 되는데 말이죠....
필터 적용 시 refetch해오도록 하고싶어서 아래 코드를 추가했는데요... api요청이 무한대로 가는 문제가 있습니다........ 
요거 질문하고 싶어서 일단 주석처리하고 push 했어요....
```tsx
 useEffect(() => {
   refetch();
 }, [Object.values(queries)]);
```

2023-08-11 04:42 UTC, ksone02 commented on frontend/src/hooks/food.ts
> +  const { foodList, fetchNextPage, hasNextPage, isFetchingNextPage, refetch } =
여기서 remove 메서드를 꺼내올 수 있는데, 현재 페이징 된 모든 리스트들을 클리어 해주는 역할을 해줘요. 필터를 적용하게 되면 모든 리스트를 초기화 하고 새로 필터링 된 리스트를 불러오는 작업이기 때문에

remove() 후에 refetch()를 해주는 게 좋아요

2023-08-12 14:37 UTC, ksone02 requested changes

2023-08-12 14:37 UTC, ksone02 commented on frontend/src/hooks/query/food.ts
> +        currentFoodListRes.petFoods.length >= currentFoodListRes.totalCount ||
이 부분 isLastPage를 두가지 조건으로 OR로 묶었는데, 혹시 설명 한번만 부탁드려도 될까요??

2023-08-12 14:37 UTC, ksone02 commented on frontend/src/hooks/food.ts
> +  const queriesString = Object.values(queries).join();
오,, 그냥 string으로 만들어서 이 값의 변화를 감지하게 만드는 방법도 있겠네요 👍

2023-08-12 14:52 UTC, HyeryongChoi commented on frontend/src/pages/Landing/Landing.tsx
> +            aria-label={hasNextPage ? '' : '모든 식품 목록을 불러왔습니다'}
무한스크롤로 동작하기 때문에 해당 타겟에 포커싱이 안 갈거라고 생각했어요!

2023-08-12 15:15 UTC, HyeryongChoi commented on frontend/src/hooks/query/food.ts
> +        currentFoodListRes.petFoods.length >= currentFoodListRes.totalCount ||
덕분에 조건문이 잘못되어있었던 걸 수정할 수 있었습니다 ㅎㅎㅎ
```tsx
      const isLastPage =
        allFoodListRes.flatMap(foodListRes => foodListRes.petFoods).length >=
          lastFoodListRes.totalCount || lastFoodListRes.petFoods.length < SIZE_PER_PAGE;
```
위와 같이 수정했습니다.

첫번째는 지금까지 응답받은 모든 식품의 수와 서버에서 응답받은 totalCount를 비교한 것이고
두번째는 마지막에 응답받은 식품의 수가 페이지당 받기로한 식품의 수보다 작은 경우(20개를 받기로 했는데 20개가 모자라서 10개만 보내준 경우)입니다!

2023-08-13 07:58 UTC, n0eyes approved these changes

2023-08-13 09:40 UTC, ksone02 approved these changes

2023-08-13 09:43 UTC, merged