feat: 에러 페이지 구현
woowacourse-teams/2023-zipgo pull request #267
Opened 2023-08-15 18:42 UTC by ksone02

## 📄 Summary
> close #265 

잘못된 url 접속시 뜨는 에러페이지를 만들었습니다.

![스크린샷 2023-08-16 오전 3 41 30](https://github.com/woowacourse-teams/2023-zipgo/assets/72087183/afe14c20-0259-4a44-b7be-6498d966bbfc)

## 🙋🏻 More
>

2023-08-16 00:44 UTC, HyeryongChoi commented on frontend/src/components/@common/Button/Button.tsx
>          $disabled={disabled}
`disabled={disabled}` 추가해주세여~~ 스타일만 disabled가 적용돼서 disabled 버튼인데도 클릭이 되더라고여

2023-08-16 00:45 UTC, HyeryongChoi commented on frontend/src/components/@common/Button/Button.tsx
>          $disabled={disabled}
`disabled={disabled}` 추가해주세여~~ 스타일만 disabled가 적용돼서 disabled 버튼인데도 클릭이 되더라고여

2023-08-16 00:46 UTC, HyeryongChoi requested changes

2023-08-16 00:46 UTC, HyeryongChoi commented on frontend/src/components/@common/Button/Button.tsx
>          $disabled={disabled}
`disabled={disabled}` 추가해주세여~~ 스타일만 disabled가 적용돼서 disabled 버튼인데도 클릭이 되더라고여

2023-08-16 01:10 UTC, wonyongChoi05 commented
와 완전 잘만들어따!

2023-08-16 02:26 UTC, ksone02 commented on frontend/src/components/@common/Button/Button.tsx
>          $disabled={disabled}
헉 그래요?? 알겠습니다~~

2023-08-17 01:24 UTC, HyeryongChoi commented on frontend/src/components/@common/Button/Button.tsx
>          $disabled={disabled}
이거 근데 내가 반영함!! ㅎㅎ

2023-08-17 01:24 UTC, HyeryongChoi submitted a review, later dismissed

2023-08-17 01:31 UTC, n0eyes submitted a review, later dismissed

2023-08-17 05:28 UTC, wonyongChoi05 approved these changes

2023-08-17 05:44 UTC, HyeryongChoi approved these changes

2023-08-17 05:54 UTC, merged