refactor: QueryRepository 엔티티 반환 로직 DTO로 변경
woowacourse-teams/2023-zipgo pull request #351
Opened 2023-08-21 09:42 UTC by wonyongChoi05

## 📄 Summary
> #350 

## 🙋🏻 More
>

2023-08-22 12:47 UTC, kyY00n requested changes
확인 ㄱ ㄱ

2023-08-22 12:47 UTC, kyY00n commented on backend/src/test/java/zipgo/petfood/application/PetFoodQueryServiceTest.java
>          }
이거 지운 이유가 궁금합니다!
밑에 기능성도 마찬가지요

2023-08-22 12:47 UTC, kyY00n commented on backend/src/test/java/zipgo/petfood/infra/persist/PetFoodQueryRepositoryTest.java
> +//package zipgo.petfood.infra.persist;
이건 왜 주석이 되어있나요!?

2023-08-25 10:43 UTC, parkmuhyeun approved these changes
확인이요~~~

2023-08-26 17:40 UTC, iamjooon2 approved these changes

2023-09-12 08:15 UTC, closed without merging