feat: 사용자 정보 확인시 이메일 및 반려동물 정보를 추가로 반환
woowacourse-teams/2023-zipgo pull request #354
Opened 2023-08-22 09:27 UTC by iamjooon2

## 📄 Summary
>  #352 

## 🙋🏻 More
> 
Controller가 무거워지는데... 싶다가도
우리가 Service에서 DTO가 아닌 도메인을 반환하기로 한 이유중 하나가 재사용성이라는 걸 떠올리며 납득

2023-08-22 10:41 UTC, wonyongChoi05 approved these changes
굿굿

2023-08-22 12:43 UTC, kyY00n requested changes
하나만 수정해줘용 ㅎ ....

2023-08-22 12:43 UTC, kyY00n commented on backend/src/test/java/zipgo/pet/domain/fixture/PetFixture.java
> +                .owner(MemberFixture.식별자_있는_멤버())
영속화 되지 않은 엔티티를 사용하는게 ... 마음에 살짝 걸리는데 ㅎㅎ

2023-08-22 13:29 UTC, iamjooon2 commented on backend/src/test/java/zipgo/pet/domain/fixture/PetFixture.java
> +                .owner(MemberFixture.식별자_있는_멤버())
RestDocs에서 자꾸 id Number인데 null들어온다고 해서 넣어준 놈이에요
id 데이터타입을 명시 안해주는 걸로 변경!

2023-08-22 14:34 UTC, wonyongChoi05 submitted a review, later dismissed

2023-08-25 10:49 UTC, parkmuhyeun approved these changes
테스트까지 꼼꼼히했네 굳굳

2023-08-25 10:49 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/review/application/ReviewQueryServiceTest.java
> +import static zipgo.pet.domain.fixture.PetFixture.*;
애 왜 와일드카드 됐누?

2023-08-26 10:53 UTC, kyY00n commented on backend/src/test/java/zipgo/pet/domain/fixture/PetFixture.java
> +                .owner(MemberFixture.식별자_있는_멤버())
영속화하지 않을 이유는?
문서 내용을 바꿀 정도인지 궁금합니다

2023-08-26 14:02 UTC, iamjooon2 commented on backend/src/test/java/zipgo/pet/domain/fixture/PetFixture.java
> +                .owner(MemberFixture.식별자_있는_멤버())
저 Fixture를 사용하던 곳이 @SpringBootTest를 이용해 인수테스트를 하던 PetControllerTest가 아닌
@WebMVcTest를 사용하던 AuthControllerTest이기 때문인데요
Repository를 스프링 빈으로부터 주입받을 수 없어서
id값을 얻기 위해 Repository의 구현체를 만들면서까지 테스트 하는 것 보다는
다른 모든 API에서 Number 타입으로 받는 id의 검증을 없애는 것이 더 낫다고 생각했기 때문입니다

2023-08-26 14:04 UTC, iamjooon2 commented on backend/src/test/java/zipgo/pet/domain/fixture/PetFixture.java
> +                .owner(MemberFixture.식별자_있는_멤버())
저 Fixture를 사용하던 곳이 https://github.com/SpringBootTest를 이용해 인수테스트를 하던 PetControllerTest가 아닌
@WebMVcTest를 사용하던 AuthControllerTest이기 때문인데요
Repository를 스프링 빈으로부터 주입받을 수 없어서
id값을 얻기 위해 Repository의 구현체를 만들면서까지 테스트 하는 것 보다는
다른 모든 API에서 Number 타입으로 받는 id의 검증을 없애는 것이 비용면에서 더 낫다고 생각했습니다

혹시 놓친 것이 있을까요?

2023-08-26 14:05 UTC, iamjooon2 commented on backend/src/test/java/zipgo/pet/domain/fixture/PetFixture.java
> +                .owner(MemberFixture.식별자_있는_멤버())
저 Fixture를 사용하던 곳이 @SpringBootTest를 이용해 인수테스트를 하던 PetControllerTest가 아닌
@WebMvcTest를 사용하던 AuthControllerTest이기 때문인데요
Repository를 스프링 빈으로부터 주입받을 수 없어서
id값을 얻기 위해 Repository의 구현체를 만들면서까지 테스트 하는 것 보다는
다른 모든 API에서 Number 타입으로 받는 id의 검증을 없애는 것이 비용면에서 더 낫다고 생각했습니다

요걸 생각하신게 맞나요?

2023-08-26 15:09 UTC, kyY00n commented on backend/src/test/java/zipgo/pet/domain/fixture/PetFixture.java
> +                .owner(MemberFixture.식별자_있는_멤버())
아~그렇군요.. 이해했습니다.
제가 코드를 제대로 보지 않은 탓이었네요!! :(
mock repository를 사용하는 경우에는 부수효과도 당연히 없겠군요~
친절한 설명 감사합니다 가비!

2023-08-26 15:11 UTC, kyY00n approved these changes
확인 했어요!
설명 감사합니다ㅎㅎ

2023-08-26 19:44 UTC, merged