refactor: 리뷰 정보 요약 조회 리팩터링
woowacourse-teams/2023-zipgo pull request #356
Opened 2023-08-22 14:33 UTC by wonyongChoi05

## 📄 Summary
> #355 

## 🙋🏻 More
> 서비스 코드가 복잡하고 가독성이 좋지 않은 것 같아서 리팩터링 좀 해봤습니다!

2023-08-23 15:23 UTC, iamjooon2 submitted a review, later dismissed

2023-08-25 11:11 UTC, parkmuhyeun reviewed
제꺼 리팩토링 해주시느라 고생많으십니다.. ㅋㅋㅋㅋ

저도 하려고 이슈 만들어 놨었읍니다
- #301

2023-08-25 11:11 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/infra/persist/ReviewQueryRepositoryImpl.java
> +    public List<SummaryElement> getReviewRatingsAverageDistribution(Long petFoodId) {
이 아래꺼 다 봤는데 이렇게 되면

서비스에 있는 getReviewsSummary 한번 호출하면 db에 접근 엄청 많이 하는거 아닌가여
어차피 리뷰 통계성이라 리뷰 다 필요할텐데 리뷰 한번에 다 꺼내놓고 하는게 더 효율성 좋지않나용

2023-08-25 11:36 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/infra/persist/ReviewQueryRepositoryImpl.java
> +    public List<SummaryElement> getReviewRatingsAverageDistribution(Long petFoodId) {
일단 효율은 기존보다 안좋을 수 있는데 이렇게 쓰면 장점이 있습니다.
## 장점
***
1. ReviewQueryService에서 PetFoodQueryRepository에 대한 의존성이 사라진다.
2. 처음부터 모든 데이터를 불러오지 않고, 필요한 데이터만 따로 불러올 수 있다.(프론트와 협의 시)
3. Query로 처리할 수 있는 로직은 Query로 처리하게 되므로 애플리케이션 로직보다 빠르게 연산하는 부분도 존재한다.
4. Rating이라는 Enum이 존재하지 않는 지금 Repository로 책임을 위임하면 하드코딩 + 반복되는 로직을 제거할 수 있다.
5. 기존의 findPetFoodWithReviewsByPetFoodId(Long petFoodId)는 위험한 쿼리다.(fetch join + outer join + where = 까딱했다간 조회만 하는데 데이터가 삭제될 수도 있음 -> 물론 CQS 도입해서 그럴 확률은 적지만 정책이나 아키텍쳐가 변경된다면 위험할 수 있는 쿼리)
6. 서비스 레이어 가독성이 짱이된다.

## 단점
***
1. 쿼리가 1번 -> 4번으로 늘어난다.

2023-08-25 11:51 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/infra/persist/ReviewQueryRepositoryImpl.java
> +    public List<SummaryElement> getReviewRatingsAverageDistribution(Long petFoodId) {
음.. 이렇게 해도 큰 상관은 없지만 전 장점이 딱히 잘 와닿진 않는 것 같아용
1. 어차피 다른 repo(ReviewQueryRepoImpl) 의존성이 추가 됐을거고 review 같은 경우 petfood에 종속되있는 친구라 있어도 이상하게 없다고 생각
2. 지금은 리뷰의 모든 데이터 불러오고 있어서 관계가 없을거 같다.
3. 이건 현재 어떤 걸 말하는진 모르겠고
4. Rating Enum 만들어서 제거 가능
5. 조회만하는데 어떻게 삭제 가능한지 잘 모르겠음(transactional only read)
6. 지금은 레포 레이어 가독성이 안 좋아짐

2023-08-25 11:58 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/infra/persist/ReviewQueryRepositoryImpl.java
> +    public List<SummaryElement> getReviewRatingsAverageDistribution(Long petFoodId) {
하 근데 제가 생각해도 쿼리 1 -> 8번은 좀 극단적이긴 한 것 같네요;; 좀 더 생각 해보겠슴다

2023-08-25 12:03 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/infra/persist/ReviewQueryRepositoryImpl.java
> +    public List<SummaryElement> getReviewRatingsAverageDistribution(Long petFoodId) {
아닙니다.. 제꺼 리팩터링 대신해주셔서 오히려 제가 감사하네요... 🙇‍♂️

2023-08-26 03:47 UTC, kyY00n requested changes
늦어서 죄송합니다🫠🫠
질문이 좀 있어서 빨강 걸어뒀어요🫡

2023-08-26 03:47 UTC, kyY00n commented on backend/src/main/java/zipgo/review/infra/persist/ReviewQueryRepositoryImpl.java
> +                .collect(Collectors.groupingBy(
static import 😉

2023-08-26 03:47 UTC, kyY00n commented on backend/src/main/java/zipgo/review/infra/persist/ReviewQueryRepositoryImpl.java
> +    public List<SummaryElement> getReviewRatingsAverageDistribution(Long petFoodId) {
이야깃거리 추가합니다 😆

1. petFoodRepository 의존성 문제를 꼭 쿼리를 사용하는 방법으로만 해결할수 있는 것인가?
2. 해당 기능의 애플리케이션 연산이 DB연산보다 정말 느린가? 느리다면 어느 정도로 고려해야하는가? (쿼리 갯수를 늘리는 것이 더 나은 일인지)

2023-08-26 03:47 UTC, kyY00n commented on backend/src/main/java/zipgo/review/infra/persist/ReviewQueryRepositoryImpl.java
> +    public List<SummaryElement> getReviewRatingsAverageDistribution(Long petFoodId) {
5번은 금시초문이라 제가 학습을 해야할거같은데.. 어떤 키워드로 찾아봐야할까요🥹

2023-08-26 03:47 UTC, kyY00n commented on backend/src/test/java/zipgo/review/infra/persist/ReviewQueryRepositoryImplTest.java
> +            리뷰_여러개_생성(식품);
저는 베베가 지금의 assertion을 작성하게 된 이유가 궁금해요
제 생각엔 여기서 봐야하는 게 값을 올바르게 계산하는지인 것 같거든요. 테스트할 데이터로 실제로 베베가 집계를 해보고 올바른 값이 나오는지를 비교해야하지 않을까요..?

2023-08-26 07:28 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/infra/persist/ReviewQueryRepositoryImpl.java
> +    public List<SummaryElement> getReviewRatingsAverageDistribution(Long petFoodId) {
"Hibernate에서 fetch join에 on절을 지원하지 않는 이유" 등의 키워드로 검색하시면 나올 것 같네요 아래는 제가 봤던 자료들입니다~

* https://docs.jboss.org/hibernate/orm/3.3/reference/en/html/queryhql.html#queryhql-joins
* https://www.inflearn.com/questions/15876/fetch-join-%EC%8B%9C-%EB%B3%84%EC%B9%AD%EA%B4%80%EB%A0%A8-%EC%A7%88%EB%AC%B8%EC%9E%85%EB%8B%88%EB%8B%A4
* https://developer-nyong.tistory.com/62#article-3-2-2--fetch-join%EA%B3%BC-where%EC%A0%88%EC%9D%98-%ED%95%A8%EC%A0%95-%EA%B7%B8%EB%A6%AC%EA%B3%A0-outer-join

2023-08-26 07:40 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/review/infra/persist/ReviewQueryRepositoryImplTest.java
> +            리뷰_여러개_생성(식품);
식품을 생성하고 해당 식품에 대한 리뷰를 여러개 생성한 후 실제로 레파지토리의 메서드를 테스트하긴 했는데, 이건 올바른 테스트가 아닌지 궁금합니다!

++ 실제로 여러 데이터들을 종합/집계 후 반환하는 로직에 대한 테스트 코드는 ReviewQueryServiceTest에 있긴 합니다.

2023-08-26 11:08 UTC, kyY00n commented on backend/src/main/java/zipgo/review/infra/persist/ReviewQueryRepositoryImpl.java
> +    public List<SummaryElement> getReviewRatingsAverageDistribution(Long petFoodId) {
jpa의 엔티티와 데이터베이스의 실제 데이터의 일관성에 대해서는 한 번도 생각해본적 없는데.. 감동적이군여..
아직 다 읽진 않았는데 좋은 인사이트 감사합니다ㅜ😍

2023-08-26 11:10 UTC, kyY00n commented on backend/src/main/java/zipgo/review/infra/persist/ReviewQueryRepositoryImpl.java
> +    public List<SummaryElement> getReviewRatingsAverageDistribution(Long petFoodId) {
와 이거 진짜 무섭네요 ㄷ ㄷ
<img width="737" alt="image" src="https://github.com/woowacourse-teams/2023-zipgo/assets/61582017/debcd8c0-853f-417a-bbb2-d1c66f733921">

2023-08-26 11:14 UTC, kyY00n commented on backend/src/test/java/zipgo/review/infra/persist/ReviewQueryRepositoryImplTest.java
> +            리뷰_여러개_생성(식품);
저 자세한 구현은 안 보고 쓴 코멘트였는데 ㅎㅎ.
`getReviewAdverseReactionAverageDistribution` 라는 인터페이스를 봤을 때는 평균 분포를 제대로 가져오는 것까지 리포지토리 책임이라고 생각해요.
그래서 리포지토리 테스트에 해당 로직 테스트가 있어야 제대로 검증된 기능이라고 볼 수 있을 것 같슴다

2023-08-27 12:00 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/infra/persist/ReviewQueryRepositoryImpl.java
> +    public List<SummaryElement> getReviewRatingsAverageDistribution(Long petFoodId) {
오 너무 맛있네요..👍🏻 조만간 저 부분 강의 다시 들어야겠꾼여

2023-08-27 12:05 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/infra/persist/ReviewQueryRepositoryImpl.java
> +    public List<SummaryElement> getReviewRatingsAverageDistribution(Long petFoodId) {
근데 우리 쿼리에 fetch join은 review에 걸려있고 where은 petFood에 걸려있어서 상관 없는거 아닌가여

2023-08-27 15:14 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/infra/persist/ReviewQueryRepositoryImpl.java
> +    public List<SummaryElement> getReviewRatingsAverageDistribution(Long petFoodId) {
그렇긴 하죠.. 사실 지금 당장 문제가 있는것들을 말한 건 아니고 먼가 위험할 것 같은(will) 부분들 위주로 적은거라 약간 비약이 있긴해요 ㅋㅋㅋㅋ

2023-09-01 06:19 UTC, closed without merging