refactor: 반려동물 정보 등록, 수정 관련 리팩터링
woowacourse-teams/2023-zipgo pull request #360
Opened 2023-08-23 17:09 UTC by HyeryongChoi

## 📄 Summary
> 
[반려동물 정보 등록, 수정 기능](https://github.com/woowacourse-teams/2023-zipgo/pull/264) 관련하여 리팩터링을 진행했습니다.

- [x] PetProfileProvider -> PetAdditionProvider 함수명 변경
- [x] PetProfileOutletContextProps -> PetAdditionOutletContextProps 타입명 변경
- [x] 반려동물 등록 전체적인 구조 변경
- [x] 반려동물 수정 페이지 -> PetProfileEditionForm 컴포넌트 분리
- [x] usePetProfileEdition 훅 추가

## 🙋🏻 More
>
- 예상 / 실제 작업 소요 시간: 4시간 /  6시간
- close #359

2023-08-24 07:26 UTC, n0eyes requested changes
전체적으로 반복되는 부분은 한 번만 코멘드 남겼어요!
고생하셨습니다 👍

2023-08-24 07:26 UTC, n0eyes commented on frontend/src/components/PetProfile/PetProfileEditionForm/PetProfileEditionForm.tsx
> +                      onClick={() => onChangePetSize(size)}
핸들러 함수는 따로 분리하면 어떨까요??

2023-08-24 07:26 UTC, n0eyes commented on frontend/src/context/petProfile/PetAdditionContext.tsx
> +export const PetAdditionProvider = ({ children }: { children: ReactNode }) => {
`PropsWithChildren`이란 타입도 있어요!

2023-08-24 07:26 UTC, n0eyes commented on frontend/src/hooks/petProfile/usePetProfileAddition.ts
> +      });
`mutation`구조를 수정하고 `onSuccess` , `onError` 라이프사이클을 활용해보면 어떨까요? 
현재는 너무 명령적인 것 같아요!

```tsx
localStorage.setItem('userInfo', JSON.stringify({ ...userInfo, hasPet: true }));
```
위 부분도 유저 정보 조회를 `invalidate`시키는 것으로 대체할 수 있을 것 같아요!

2023-08-24 07:26 UTC, n0eyes commented on frontend/src/hooks/petProfile/usePetProfileAddition.ts
> +    navigate(routerPath.home());
`useEasyNavigate`의 `goHome` 함수를 사용하면 좋을 것 같아요!

2023-08-24 07:26 UTC, n0eyes commented on frontend/src/hooks/petProfile/usePetProfileEdition.ts
> +    if (!isValidName(petName)) setIsValidNameInput(false);
```suggestion
    setIsValidNameInput(isValidName(petName));
```
은 어떤가요!?

2023-09-11 05:50 UTC, wonyongChoi05 approved these changes
별론데!??

2023-09-11 06:35 UTC, ksone02 approved these changes
lgtm

2023-09-11 09:00 UTC, n0eyes approved these changes
고생하셨습니다!

2023-09-11 11:30 UTC, merged