feat: admin 페이지 추가
woowacourse-teams/2023-zipgo pull request #372
Opened 2023-08-31 09:47 UTC by parkmuhyeun

## 📄 Summary
> 

## 🙋🏻 More
>

2023-09-01 06:25 UTC, wonyongChoi05 submitted a review, later dismissed
너무 고생했다 민무야~~ 근데 PetFood 스키마가 변경되서 내꺼 머지되면 코드 깨질 것 같은데 ㄱㅊ? 일단 어푸룹은 해줄게

2023-09-01 07:18 UTC, iamjooon2 reviewed
민무 어드민 정말 고생했디!
뷰는 렉이 너무 걸려서 못보겠넴ㅋㅋㅋ 
빠르게 남겨보았슴 =3

2023-09-01 07:18 UTC, iamjooon2 commented on backend/src/main/java/zipgo/admin/presentation/AdminController.java
> +    ResponseEntity<List<BrandSelectResponse>> getBrands() {
이번 PR 통해서

1. 어드민 홈(View)
2. 브랜드 조회
3. 브랜드 생성 
4. 반려동물 식품 생성

이렇게 4개의 기능이 추가된 것 같은데요

1, 2번의 어드민 홈, 브랜드 조회는 어드민 컨트롤러에 있고
3,4번의 브랜드 생성, 식품 생성은 각각의 도메인 컨트롤러에 위치시킨 이유가 궁금합니다!

2023-09-06 09:50 UTC, wonyongChoi05 approved these changes

2023-09-06 11:14 UTC, iamjooon2 requested changes
차라리 Admin에 view만 남기는 건 어떰?

2023-09-06 23:57 UTC, kyY00n commented
appplication-local1 은 무엇인가용?

2023-09-07 00:03 UTC, kyY00n commented on backend/src/main/java/zipgo/admin/presentation/AdminController.java
> +    ResponseEntity<List<BrandSelectResponse>> getBrands() {
22.. 개인적으로는 도메인 컨트롤러보다 어드민 컴트롤러에 넣는게 더 나은 것 같아요. 어드민 기능은 애플리케이션 기능과는 권한을 다르게 관리거나 분리 될 가능성이 높은 것 같기 때문입니다..!

2023-09-07 01:30 UTC, kyY00n requested changes
수고했습니다 :D
누구보다 빠르게 남들과는 다르게(?) 개발하는 무민~~

2023-09-07 01:30 UTC, kyY00n commented on backend/src/test/java/zipgo/image/application/ImageServiceTest.java
> +        when(imageClient.upload(any(), any(), any()))
✅ 전에 제가 꼼꼼히 보지 못했었는데, 이 테스트는 아쉽네요.
ImageClient보다는 S3Client나 S3Uploader를 모킹하면 좋았을 것 같군요

2023-09-07 01:30 UTC, kyY00n commented on backend/src/test/java/zipgo/image/presentaion/ImageControllerTest.java
> +        when(imageService.save(사진_파일, ImageDirectoryUrl.PET_DIRECTORY))
👍🏻

2023-09-07 01:30 UTC, kyY00n commented on backend/src/test/java/zipgo/petfood/application/FunctionalityServiceTest.java
> +    void createFunctionality() {
왜 한글이 아니지.... 설마 ...... 코파일럿이 혼자 한 일은 아니겠죠

2023-09-07 01:30 UTC, kyY00n commented on backend/src/test/java/zipgo/petfood/application/PetFoodServiceTest.java
> +        Assertions.assertDoesNotThrow(() -> byId);
static import 를 할 수 있을 것 같아요

2023-09-07 01:30 UTC, kyY00n commented on backend/src/test/java/zipgo/petfood/application/PetFoodServiceTest.java
> +        Long petFoodId = petFoodService.createPetFood(식품_생성_요청, "imageUrl");
완전 사소한건데ㅋㅋㅋㅋ 이미지 경로를 request랑 같이 given에 두면 좋을거같아요!!!

```suggestion
String 식품_이미지_경로 = "imageUrl";

//when
Long petFoodId = petFoodService.createPetFood(식품_생성_요청, 식품_이미지_경로);
```

2023-09-07 01:30 UTC, kyY00n commented on backend/src/test/java/zipgo/petfood/presentation/PrimaryIngredientControllerTest.java
> +            var content = objectMapper.writeValueAsString(닭고기_주원료_요청);
질문) RestAssured body 메서드에 자바 객체를 넣어도 되는 걸로 알고 있는데 objectMapper 사용한 이유가 있나요?

2023-09-07 01:30 UTC, kyY00n commented on backend/src/test/java/zipgo/petfood/presentation/PrimaryIngredientControllerTest.java
> +        }
코드에도 bdd 스타일이 잘 보이게 써보는건 어때요?? (사소해서 적용안해도 됩니다)
```suggestion
var 응답 = 요청_준비.when()
                                .post("/primary-ingredients");
                                
응답.then()
        .assertThat().statusCode(CREATED.value());
```

2023-09-07 01:30 UTC, kyY00n commented on backend/src/main/resources/templates/admin/home.html
> +        console.log(selectedFunctionalities);
지워도 좋을 것 같아요!

2023-09-07 01:30 UTC, kyY00n commented on backend/src/main/java/zipgo/petfood/application/PetFoodService.java
> +    private final BrandQueryService brandQueryService;
질문) 리포지토리가 아닌 서비스를 사용한 이유!?

2023-09-07 02:00 UTC, iamjooon2 commented on backend/src/main/resources/templates/admin/home.html
> +        console.log(selectedFunctionalities);
대박이다 로지

2023-09-08 05:47 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/petfood/application/PetFoodService.java
> +        return petFoodRepository.save(petFood).getId();
해당 서비스에서 transactional 애노테이션을 빼자는 건가용?

2023-09-08 05:48 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/admin/presentation/AdminController.java
> +    ResponseEntity<List<BrandSelectResponse>> getBrands() {
각 뷰에 해당하는 dto로 반환해주기 때문에 admin에 종속될거라 생각해 admin 패키지에 넣도록 하겠씁니다~

2023-09-08 07:04 UTC, parkmuhyeun commented
> appplication-local1 은 무엇인가용?

아 ㅋㅋ 제 로컬 전용 yml인데 실수로 들어갔네요

2023-09-08 07:13 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/image/infrastructure/aws/s3/S3PetImageClient.java
> +    public String upload(String name, MultipartFile file, String directory) {
캬.. 꼼꼼하다 꼼꼼해

2023-09-08 07:15 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/petfood/application/FunctionalityServiceTest.java
> +    void createFunctionality() {
제가 코파일럿이나 쓰는 사람으로 보이나요 ㅡㅅㅡ?

한글로 적기 귀찮아서 메서드명 그대로 적었습니다

2023-09-08 07:27 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/petfood/presentation/PrimaryIngredientControllerTest.java
> +            var content = objectMapper.writeValueAsString(닭고기_주원료_요청);
코드를 오랜만에 짜서 까먹었습니다 헷..

2023-09-08 07:32 UTC, parkmuhyeun commented
이번에 보기 힘든 커밋이였을텐데 날카롭고 꼼꼼한 피드백 준 로지에게 무한 감사드림다 🙌

2023-09-08 07:37 UTC, kyY00n approved these changes
IGO 고생하셨습니다 최고~~~

2023-09-08 07:42 UTC, iamjooon2 approved these changes

2023-09-08 08:29 UTC, merged

2023-09-08 08:33 UTC, iamjooon2 commented on backend/src/main/java/zipgo/petfood/application/PetFoodService.java
> +        return petFoodRepository.save(petFood).getId();
트랜잭션을 거는 이유는 한 작업단위로 묶어둬서 중간에 에러터지면 DB에 반영되지 않고 롤백시키기 위함인데
레파지토리에 트랜잭션 이미 걸려있고, 서비스단에서 한 작업단위로 묶을 필요는 없다고 생각했습니당

2023-09-08 08:33 UTC, iamjooon2 commented on backend/src/main/java/zipgo/petfood/application/PetFoodService.java
> +        return petFoodRepository.save(petFood).getId();
트랜잭션을 거는 이유는 한 작업단위로 묶어둬서 중간에 에러터지면 DB에 반영되지 않고 롤백시키기 위함인데
레파지토리에 트랜잭션 이미 걸려있고, 서비스단에서 한 작업단위로 묶을 필요는 없다고 생각했습니당
필요하면 그떄 걸어도 되니까요!

개인 의견이니 남겨둡니다