refactor: 리뷰 쿼리 서비스 리팩터링
woowacourse-teams/2023-zipgo pull request #378
Opened 2023-09-05 09:30 UTC by wonyongChoi05

## 📄 Summary
> 도메인 변경 없이 쿼리 서비스만 개선했습니다

## 🙋🏻 More
>

2023-09-06 09:34 UTC, parkmuhyeun submitted a review, later dismissed
하도 많이 고쳐서 이 부분 달인됐네ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-09-06 12:52 UTC, iamjooon2 requested changes
톰캣 컨트리뷰터님 고생하셨습니다

2023-09-06 12:52 UTC, iamjooon2 commented on backend/src/main/java/zipgo/review/domain/type/TastePreference.java
> +    private static final Integer PERCENTAGE = 100;
1. 개행
2. 박싱 -> 언박싱
3. 필드보다 위로!

2023-09-06 12:52 UTC, iamjooon2 commented on backend/src/main/java/zipgo/review/domain/type/StoolCondition.java
> +    private static final Integer PERCENTAGE = 100;
얘두 언박싱!

2023-09-06 12:52 UTC, iamjooon2 commented on backend/src/main/java/zipgo/review/presentation/dto/response/type/RatingInfoResponse.java
> +    public static RatingInfoResponse of(Integer name, int percentage) {
name 대신 rating 어떰

2023-09-06 23:37 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/domain/type/TastePreference.java
> +    private static final Integer PERCENTAGE = 100;
보통 상수는 박싱 타입 사용하지 않나요??

2023-09-07 00:55 UTC, iamjooon2 commented on backend/src/main/java/zipgo/review/domain/type/TastePreference.java
> +    private static final Integer PERCENTAGE = 100;
test

2023-09-07 01:32 UTC, iamjooon2 commented on backend/src/main/java/zipgo/review/domain/type/TastePreference.java
> +    private static final Integer PERCENTAGE = 100;
저는 처음듣습니다!

2023-09-07 02:31 UTC, kyY00n requested changes
베베 수고했어요! 호호 줄였는데도 양이 많네요
고생했을 베베에게 감사합니다
(리뷰한 나자신도.. 조금은 수고했다)

2023-09-07 02:31 UTC, kyY00n commented on backend/src/main/java/zipgo/review/application/ReviewQueryService.java
> +import zipgo.review.presentation.dto.response.type.TastePreferenceResponse;
질문) 조회 서비스는 presentation 의존성이 있어도 괜찮은가요? 그렇다면 이유가 무엇인지..!? (PetFood 조회 서비스도 그렇게 되어있는 것을 지금 확인했습니다ㅠ)

2023-09-07 02:31 UTC, kyY00n commented on backend/src/main/java/zipgo/review/domain/type/AdverseReactionType.java
> +    public static AdverseReactionType from(String adverseReactionType) {
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 와 .... 이거 왜이렇게 돼있었죠 베베 굳..👍🏻

2023-09-07 02:31 UTC, kyY00n commented on backend/src/main/java/zipgo/review/domain/type/AdverseReactionType.java
> +    public static int getDistributionPercentage(long total, long count) {
질문) 이 기능이 왜 이 클래스에 존재해야하는지 알려주세요..!!

2023-09-07 02:31 UTC, kyY00n commented on backend/src/main/java/zipgo/petfood/domain/Reviews.java
> +        return TastePreference.getDistributionPercentage(reviews.size(), count);
여기서 보니까 getDistributionPercentage가 왜 각 클래스 안에 있어야하는지 더 궁금증이..?!
모두 공통로직이라고 생각하는데, Reviews로 옮기는 건 불가능할까요?

2023-09-07 02:31 UTC, kyY00n commented on backend/src/main/java/zipgo/petfood/domain/Reviews.java
> +                .flatMap(review -> review.getAdverseReactions().stream())
👍🏻

2023-09-07 02:31 UTC, kyY00n commented on backend/src/main/java/zipgo/review/application/ReviewQueryService.java
> +        List<RatingInfoResponse> ratingInfoResponses = IntStream.rangeClosed(1, 5)
```suggestion
List<RatingInfoResponse> ratingInfoResponses = IntStream.rangeClosed(MIN_RATING, MAX_RATING)
```
상수로 빼주는 건 어떨까요? 원래 저는 이런거 잘 못챙기는 편인데
이 경우에는 가독성이 많이 높아질것 같아서 제안합니당~

2023-09-07 02:31 UTC, kyY00n commented on backend/src/main/java/zipgo/petfood/domain/Reviews.java
> +    public int getStoolsConditionPercentage(String stoolCondition) {
```suggestion
public int getStoolsConditionPercentage(StoolCondition stoolCondition) {
```
질문) 메서드 사용자를 고려한다면 이렇게 매개변수를 제한해주는 게 좋다고 생각하는데, 베베가 이렇게 구현한 이유가 궁금합니다!

2023-09-07 02:31 UTC, kyY00n commented on backend/src/test/java/zipgo/petfood/domain/ReviewsTest.java
> +    private static Stream<Arguments> 별점과_평균_리스트_만들기() {
감사합니다 👍🏻

2023-09-07 02:31 UTC, kyY00n commented on backend/src/test/java/zipgo/review/application/ReviewQueryServiceTest.java
RIP🙏🏻 (잘가!)

2023-09-07 02:31 UTC, kyY00n commented on backend/src/test/java/zipgo/review/domain/repository/ReviewQueryRepositoryImplTest.java
> +;
이거 삭제하면 좋을 것 같네용

2023-09-07 10:21 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/domain/type/TastePreference.java
> +    private static final Integer PERCENTAGE = 100;
잘못된 정보였던걸로 ㅋㅋ

2023-09-07 10:39 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/application/ReviewQueryService.java
> +import zipgo.review.presentation.dto.response.type.TastePreferenceResponse;
맞습니다.. 이게 패키지마다 뒤죽박죽 섞여있어서 일단 review 도메인은 이렇게 처리했었는데 이왕 하는김에 다 분리 해놓겠습니다~

2023-09-07 10:42 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/domain/type/AdverseReactionType.java
> +    public static int getDistributionPercentage(long total, long count) {
단순히 AdverseReactionType이라는 Enum 클래스에 대한 정보라고 생각해서 저기에서 반환하도록 했는데, 지금 보니 외부에서 주입 받은 값으로만 값을 계산해서 반환해주네요! Reviews에서 처리하면 중복 메서드도 제거되고 더 적합할 것 같습니다.

2023-09-07 10:42 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/petfood/domain/Reviews.java
> +        return TastePreference.getDistributionPercentage(reviews.size(), count);
https://github.com/woowacourse-teams/2023-zipgo/pull/378#discussion_r1318423607

2023-09-07 10:51 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/application/ReviewQueryService.java
> +        List<RatingInfoResponse> ratingInfoResponses = IntStream.rangeClosed(1, 5)
제가 도메인을 이해한 상태에서 작성해서 그런지 1과 5가 무엇을 뜻하는지 모르는 사람들의 입장에서는 생각하지 못했네요 ㅠ 꼼꼼하게 봐주셔서 감사합니다~

2023-09-07 10:52 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/petfood/domain/Reviews.java
> +    public int getStoolsConditionPercentage(String stoolCondition) {
오.. 사실 enum으로 받는 생각을 못하고 있었는데.. 어쩐지 계속 .name()함수를 사용하게 되더라구요.. 반영하겠습니다!

2023-09-07 10:57 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/review/domain/repository/ReviewQueryRepositoryImplTest.java
> +;
와 이걸 본다고??

2023-09-07 16:13 UTC, kyY00n approved these changes
👍🏻🚀🚀🚀🚀🚀🚀🚀🚀

2023-09-07 19:40 UTC, iamjooon2 approved these changes

2023-09-08 01:06 UTC, merged