feat: 반려동물 여러마리 등록 기능 추가
woowacourse-teams/2023-zipgo pull request #398
Opened 2023-09-13 13:04 UTC by HyeryongChoi

## 📄 Summary
> 
![image](https://github.com/woowacourse-teams/2023-zipgo/assets/24777828/00b9cb65-6af7-475a-b4e5-0c0cd3e3bee6)

### ✨ Describe

### ✅ Tasks

- [x] 반려동물 정보 등록, 수정, 삭제 시 헤더 프로필 업데이트
- [x] 반려동물 정보 수정 버튼 클릭 시 헤더 프로필 업데이트X
- [x] 리뷰 등록 시 petId도 함께 전달하도록 수정
- [x] Dockerfile 스토리북 배포 설정
- [x] 로그인 시 사용자의 반려동물 프로필이 헤더에 즉시 적용되도록 설정

### 🕖 예상/식제 작업 소요 시간

1시간/2시간

## 🙋🏻 More
> 

- close #396

2023-09-14 02:19 UTC, iamjooon2 submitted a review, later dismissed
고생 많으셨습니다!

2023-09-14 02:19 UTC, iamjooon2 commented on frontend/Dockerfile
>  CMD ["nginx", "-g", "daemon off;"]
매의 눈 O_O

2023-09-14 02:19 UTC, iamjooon2 commented on frontend/src/components/PetProfile/PetList.tsx
> +    <AddButtonText>우리 아이 등록하기</AddButtonText>
견주 마음을 잘 아는 첵스

2023-09-14 02:19 UTC, iamjooon2 commented on frontend/src/components/PetProfile/PetListBottomSheet.tsx
> +  &::-webkit-scrollbar {
스크롤바를 없애주셨군요!

2023-09-14 07:09 UTC, ksone02 approved these changes

2023-09-14 07:09 UTC, ksone02 commented on frontend/src/components/PetProfile/PetItem.tsx
> +        onClick={e => e.stopPropagation()}
stopPropagation은 왜해주셨나요

2023-09-14 07:41 UTC, n0eyes requested changes
고생하셨어요! 코멘트 한번 확인 부탁드려요!

2023-09-14 07:41 UTC, n0eyes commented on frontend/src/hooks/query/auth.ts
> +      if (selectedPet && newestPet) updatePetProfile(selectedPet);
```suggestion
      if (selectedPet) updatePetProfile(selectedPet);
      else if (newestPet) updatePetProfile(newestPet);
```

중복된 컨디션을 제거해 봤습니다!

2023-09-14 07:41 UTC, n0eyes commented on frontend/src/hooks/query/petProfile.ts
> +      });
```tsx
const data = useQuery({
    queryKey: ['zipgoLocalStorageKey'],
    queryFn: () => zipgoLocalStorage.getPetProfile(),
  });

```
이런식으로 `zipgoLocalStorage` 데이터도 전역상태로 만들어서 사용하면 훨씬 선언적으로 사용할 수 있을 것 같아요!

2023-09-14 07:41 UTC, n0eyes commented on frontend/src/hooks/query/review.ts
> +  const navigate = useNavigate();
`useEasyNavigate`도 `navigate` 제공해요! 서운합니다 😭

2023-09-14 07:43 UTC, HyeryongChoi commented on frontend/src/hooks/query/petProfile.ts
> +      });
오 좋네요!! 변경이 많을 것 같아서 다음에 새로 이슈 생성 후 반영하겠습니당 좋은 코멘트 감사행요👍

2023-09-14 07:43 UTC, HyeryongChoi commented on frontend/src/hooks/query/review.ts
> +  const navigate = useNavigate();
ㅎㅎ👍

2023-09-14 07:43 UTC, n0eyes approved these changes

2023-09-14 07:43 UTC, ksone02 approved these changes

2023-09-14 07:44 UTC, merged

2023-09-15 04:35 UTC, HyeryongChoi commented on frontend/src/components/PetProfile/PetItem.tsx
> +        onClick={e => e.stopPropagation()}
현재 프로필 펫A인 상태에서
펫B의 정보를 수정하기 위해 수정(삭제)버튼을 클릭 했을 때 > 클릭 이벤트가 전파 > 헤더의 프로필이 펫B로 변경
위와 같은 문제가 있어서 이벤트 전파를 막아주었습니다!

수정(삭제)버튼을 클릭했는데 펫 프로필이 바뀌면 안되니까요~~~