refactor: 펫푸드 패키지 리팩터링
woowacourse-teams/2023-zipgo pull request #401
Opened 2023-09-14 06:06 UTC by parkmuhyeun

## 📄 Summary
- #397 

### 리팩터링 한 것은 다음과 같습니다.
- convertStringsToCollection
  - 후에 , 로 들어오는 request에 사용할 수 있는 메서드 같아 util로 분리했습니다.
- 현재 저희 서비스에서 dto 반환과 엔티티 반환이 섞여있는거 같아서 dto로 반환으로 바꿔줌
- 메서드 순서대로 배치
- Fetch join 가장 많은 데이터를 가지는 자식 쪽으로 변경(후에 추가 된다고 할 때 주원료가 가장 많아질거라 판단)
- 주원료, 기능성 Name에 unique 제약조건 추가
- 주원료, 기능성 가져오는 쿼리 변경
- ... 등등

궁금한거 있으면  커멘트 주세요!

그리고 하나 상의 해보면 좋을게 

현재 나라 기준은 펫푸드에 필드로 가지고있어서 id가 없어서 filteresponse에 id를 하드코딩으로 넣어주고 있더라구요.
어떻게 하면 좋을지 상의해보면 좋을 것 같아요.

## 🙋🏻 More
> 우선 펫푸드 패키지 프로덕션 코드 리팩터링 했고 테스트코드 리팩터링은 일단 상의가 필요할 것 같아요. @Transactional 제거하는거 부터 해서 데이터 저장하는거 등..

2023-09-14 07:24 UTC, kyY00n requested changes
수고했어 무민 !!!! 할일을 찾아서 하는 개발자 굿~
중간에 테스트 하나 주석처리 돼있어서 그거만 고쳐줭!

2023-09-14 07:24 UTC, kyY00n commented on backend/src/main/java/zipgo/petfood/presentation/PetFoodController.java
> +                StringUtils.convertStringsToCollection(brands),
static import 할 수 있을 것 같아요

2023-09-14 07:24 UTC, kyY00n commented on backend/src/test/java/zipgo/common/util/StringUtilsTest.java
> +class StringUtilsTest {
👍🏻

2023-09-14 07:24 UTC, kyY00n commented on backend/src/test/java/zipgo/petfood/application/PetFoodQueryServiceTest.java
>              );
원복하면 좋을 것 같아요!

2023-09-14 07:24 UTC, kyY00n commented on backend/src/test/java/zipgo/petfood/application/PetFoodQueryServiceTest.java
>              );
👀

2023-09-14 07:24 UTC, kyY00n commented on backend/src/test/java/zipgo/petfood/domain/fixture/FunctionalityFixture.java
> +    public static Functionality 기능성_짱짱짱() {
아 ㅋㅋㅋㅋㅋㅋㅋㅋ ㅜㅜ

2023-09-14 07:24 UTC, kyY00n commented on backend/src/main/java/zipgo/petfood/dto/response/FilterResponse.java
> +                //TODO 하드 코딩 생각
하드코딩 스레드 ⬇️

2023-09-14 09:08 UTC, wonyongChoi05 requested changes
수고했으 민무~ 센스 좋았따 ㅋㅋ
테스트 코드 삭제한 부분하고 컨벤션 정도만 봐줘

2023-09-14 09:08 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/petfood/domain/repository/PrimaryIngredientRepository.java
> +        return findById(id).orElseThrow(() -> new PrimaryIngredientNotFoundException(id));
한 칸 띄워쓰는거 어떤가요?

2023-09-14 09:08 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/petfood/domain/PrimaryIngredient.java
> +    @Column(unique = true, nullable = false)
nullable 좋네요 👍🏻👍🏻

2023-09-14 09:08 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/common/util/StringUtils.java
> +            return Arrays.asList(decodedValues.split(","));
`,`는 separator로 분리하는건 어떤가용?

2023-09-14 09:08 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/petfood/dto/response/FilterResponse.java
> +                functionalities.stream().map(FunctionalityResponse::from).toList(),
요거 스트림 밑으로 개행

2023-09-14 09:08 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/petfood/infra/persist/PetFoodQueryRepositoryImpl.java
> +                .fetchJoin()
센스 굿👍🏻 저희 default_batch_fetch_size가 지금 20인데 1000까지 늘려도 무방할 것 같아요.

2023-09-14 09:08 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/petfood/infra/persist/PetFoodQueryRepositoryImpl.java
> +                .join(petFood.petFoodPrimaryIngredients, petFoodPrimaryIngredient)
+ fetchJoin()

2023-09-14 09:08 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/common/util/StringUtils.java
> +    public static List<String> convertStringsToCollection(String values) {
기존에 메서드 시그니처 예외 붙어있던거 없어져서 좋네요 ㅎㅎ

2023-09-14 09:08 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/petfood/application/PetFoodQueryServiceTest.java
>              );
ㄴ 22

2023-09-14 09:08 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/petfood/application/PetFoodQueryServiceTest.java
> -                            .isEqualTo(List.of("튼튼"))
👁👁

2023-09-14 09:08 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/petfood/application/PetFoodQueryServiceTest.java
> -                            .isEqualTo(List.of("튼튼"))
👁👁

2023-09-14 16:16 UTC, iamjooon2 commented on backend/src/test/java/zipgo/petfood/application/PetFoodQueryServiceTest.java
>              );
집고 귀엽다

2023-09-15 04:38 UTC, iamjooon2 approved these changes

2023-09-15 06:38 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/petfood/application/PetFoodQueryServiceTest.java
>              );
😅

2023-09-15 08:54 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/petfood/dto/response/FilterResponse.java
> +                //TODO 하드 코딩 생각
새로 pr 파서 엔티티 분리작업 하겠습니다~

2023-09-16 15:05 UTC, iamjooon2 approved these changes
👍

2023-09-17 00:23 UTC, kyY00n approved these changes

2023-09-18 04:04 UTC, wonyongChoi05 approved these changes

2023-09-18 04:36 UTC, merged