fix: 리뷰 메타데이터 믹스견 중복 수정
woowacourse-teams/2023-zipgo pull request #418
Opened 2023-09-18 06:56 UTC by iamjooon2

## 📄 Summary
> #417 

## 🙋🏻 More
> 

[사용자의 반려견이 믹스견일시, 견종 크기를 구분하지 않고 필터링 하도록 수정](https://github.com/woowacourse-teams/2023-zipgo/commit/6f775639bccdcee82a8002436e8a38ad5c6f09c3)
[리뷰 메타데이터 믹스견 중복 해결](https://github.com/woowacourse-teams/2023-zipgo/commit/7ce4ec686007007a2a9ffc0057ffa070f8742442)

믹스견의 견종 크기 구분취소 로직은 다음과 같음
1) 믹스견의 식별자를 가지고 옴
2) 요청받은 견종 식별자가 믹스견 식별자에 포함되는지 확인
2-1) 맞다면 dto내 견종 식별자를 믹스견으로 변경
2-2) 아니라면 패스

2023-09-19 00:52 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/application/ReviewQueryService.java
> +        }
이쪽부분이 이해가 잘 안되여 믹스브리드아이디들을 찾아서 다시 리퀘스트에 넣는건가요??

2023-09-19 00:53 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/application/ReviewQueryService.java
> +    private boolean isMixedBreed(List<Long> requestIds, List<Long> mixBreedIds) {
id에 너무 종속적인거 같은데 어떻게 제거를 못할까여

2023-09-19 00:57 UTC, iamjooon2 commented on backend/src/main/java/zipgo/review/application/ReviewQueryService.java
> +        }
예 정확합니다

2023-09-19 04:57 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/application/ReviewQueryService.java
> +    private boolean isMixedBreed(List<Long> requestIds, List<Long> mixBreedIds) {
+isEmpty()

2023-09-19 08:37 UTC, kyY00n submitted a review, later dismissed

2023-09-19 08:47 UTC, iamjooon2 commented on backend/src/main/java/zipgo/review/application/ReviewQueryService.java
> +        }
`isMixedBreed()` -> `isRequestContainMixBreed()`로 변경하였음

2023-09-19 08:47 UTC, iamjooon2 commented on backend/src/main/java/zipgo/review/application/ReviewQueryService.java
> +    private boolean isMixedBreed(List<Long> requestIds, List<Long> mixBreedIds) {
1. 협의 완료
2. isEmpty() 부정형으로 사용하도록 바꿈

2023-09-20 04:18 UTC, wonyongChoi05 requested changes
갈비 수고했어~~ 👍🏻👍🏻

2023-09-20 04:18 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/pet/dto/response/BreedResponses.java
> +                        .map(breed -> new BreedResponse(breed.getId(), breed.getName()))
new Response -> Response.of()

2023-09-20 04:18 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/application/ReviewQueryService.java
> +        if (!requestIds.isEmpty() && requestIds.get(0) == MIXED_BREED_ID) {
0이 뭔가요? 매직넘버 같습니다만..

2023-09-20 04:18 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/application/ReviewQueryService.java
> +        if (!requestIds.isEmpty() && mixBreedIds.contains(requestIds.get(0))) {
ditto

2023-09-20 04:18 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/application/ReviewQueryService.java
>          List<Long> reviewIds = reviews.stream().map(FindReviewsQueryResponse::id).toList();
개행

2023-09-20 04:18 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/application/ReviewQueryService.java
>      }
findAll -> DTO 변환 생각해보시죠

2023-09-20 04:45 UTC, iamjooon2 commented on backend/src/main/java/zipgo/pet/dto/response/BreedResponses.java
> +                        .map(breed -> new BreedResponse(breed.getId(), breed.getName()))
BreedResponse가 inner class라서, 굳이 정적팩터리 메서드를 만들어야 할까? 생각했습니다

2023-09-20 04:45 UTC, iamjooon2 commented on backend/src/main/java/zipgo/review/application/ReviewQueryService.java
> +        if (!requestIds.isEmpty() && requestIds.get(0) == MIXED_BREED_ID) {
반영하겠슴둥

2023-09-20 04:45 UTC, iamjooon2 commented on backend/src/main/java/zipgo/review/application/ReviewQueryService.java
> +        if (!requestIds.isEmpty() && mixBreedIds.contains(requestIds.get(0))) {
ditto

2023-09-20 04:49 UTC, iamjooon2 commented on backend/src/main/java/zipgo/review/application/ReviewQueryService.java
>          List<Long> reviewIds = reviews.stream().map(FindReviewsQueryResponse::id).toList();
stream 말하는거죠?

2023-09-20 04:52 UTC, iamjooon2 commented on backend/src/main/java/zipgo/review/application/ReviewQueryService.java
>      }
쿼리 최적화를 위해 인덱스와 씨름하고있는 지금, 저도 조인 한번 한번이 마음에 걸리긴 합니다만...

이 PR의 작업단위는 아니라고 생각합니다.
쿼리 개선은 ReviewQueryService의 다른 메서드들과 함께 작업하시죠.

2023-09-20 05:05 UTC, iamjooon2 commented on backend/src/main/java/zipgo/pet/dto/response/BreedResponses.java
> +                        .map(breed -> new BreedResponse(breed.getId(), breed.getName()))
컨벤션을 따르겠습니다

2023-09-20 05:16 UTC, parkmuhyeun approved these changes
gogo

2023-09-20 05:18 UTC, wonyongChoi05 approved these changes
굳!

2023-09-20 05:23 UTC, merged