refactor: Toast 사용 방법 리팩터링 / 강아지 터치 이스터에그 수정
woowacourse-teams/2023-zipgo pull request #428
Opened 2023-09-20 08:05 UTC by ksone02

## 📄 Summary
> close #425 

ToastContext를 만들어서 Router에 ToastProvider를 심었습니다.
이후 useToast에서 toast 함수를 호출해서 toast를 생성하면 토스트를 손쉽게 사용할 수 있습니다.

## 🙋🏻 More
> 이스터에그도 수정했어요
<img width="284" alt="스크린샷 2023-09-20 오후 4 59 45" src="https://github.com/woowacourse-teams/2023-zipgo/assets/72087183/ad4a45d5-b3b6-4b57-bb97-d44cb76cb5c9">

#### 추가로..

```typescript
  const toast = (content: ToastContent, option?: ToastOption) =>
    dispatchToast(content, mergeOptions(Type.INFO, option));

  toast.success = createToastByType(Type.SUCCESS);
  toast.info = createToastByType(Type.INFO);
  toast.warning = createToastByType(Type.WARNING);

  const memoizedValue = useMemo(
    () => ({
      toast,
      currentToast: toastStates,
    }),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [toastStates], // toast가 원래 들어가야 하는데 그러면 useCallback이 권장됨
  );
```

여기가 너무 킹받는 모먼트인데.. toast를 useCallback으로 감싸면 .sucess, .info와 같이 필드 추가가 안되더라구요
그래서 그냥 불편하지만 useCallback으로 안감싸고 사용했습니다..

2023-09-20 08:48 UTC, n0eyes requested changes
고생하셨어요!

코멘트 확인 부탁드릴게요 😄

2023-09-20 08:48 UTC, n0eyes commented on frontend/src/context/Toast/ToastContext.tsx
> +    }
```suggestion
        currentToast.current =  currentToast.current.filter((toast)=> toast.option.toastId !== toasId)
    
    setToastStates(currentToast.current);

      timers.current.delete(toastId);
```

`filter`를 사용하는건 어떨까요!?

2023-09-20 08:48 UTC, n0eyes commented on frontend/src/context/Toast/ToastContext.tsx
> +    dispatchToast(content, mergeOptions(Type.INFO, option));
`toast`를 그대로 호출하는 방식이 따로 필요한 이유가 있을까요~?

없다면 객체나 클래스 인스턴스로 변경한다면 `useCallback` 이슈도 해결될 것 같아요!

2023-09-20 08:48 UTC, n0eyes commented on frontend/src/context/Toast/ToastContext.tsx
> +const ToastProvider = (props: PropsWithChildren<ToastProviderProps>) => {
사용하는 `props`가 없다면 `PropsWithChildren`만 사용해도 좋을 것 같아요!

2023-09-20 08:48 UTC, n0eyes commented on frontend/src/context/Toast/ToastContext.tsx
> +  };
중복되는 타입을 분리하면 어떨까요~?

2023-09-20 08:48 UTC, n0eyes commented on frontend/src/context/Toast/ToastContext.tsx
> +});
`createToastByType` 함수를 사용하여 중복을 제거할 수 없을까요!?

2023-09-20 08:48 UTC, n0eyes commented on frontend/src/context/Toast/ToastContext.tsx
> +const tempToast = (content: ToastContent, option?: ToastOption): ToastInterface => ({
`initialToast` 네이밍은 어떻게 생각하세요!?

2023-09-20 10:21 UTC, ksone02 commented on frontend/src/context/Toast/ToastContext.tsx
> +    dispatchToast(content, mergeOptions(Type.INFO, option));
그냥 욕심입니다.. ㅎㅎ 욕심 포기했습니다..

2023-09-20 12:05 UTC, HyeryongChoi submitted a review, later dismissed
질문 몇개 달았어요😄 고생하셨습니다🐕

2023-09-20 12:05 UTC, HyeryongChoi commented on frontend/src/context/Toast/ToastContext.tsx
> +    }, 4500);
이 시간은 무슨 기준으로 설정한 건지 궁금해요~

2023-09-21 02:24 UTC, ksone02 commented on frontend/src/context/Toast/ToastContext.tsx
> +ToastContext.displayName = 'Toast';
<img width="147" alt="스크린샷 2023-09-21 오전 11 23 51" src="https://github.com/woowacourse-teams/2023-zipgo/assets/72087183/ace6bfa6-0e2c-47aa-9454-7b24f4390f50">

개발자 도구에서 이렇게 보이게 할 수 있습니당

2023-09-21 02:24 UTC, ksone02 commented on frontend/src/context/Toast/ToastContext.tsx
> +    }, 4500);
기준은 딱히 없고 4.5초 뒤에 사라지게 하면 자연스럽더라구요~

2023-09-21 02:24 UTC, ksone02 commented on frontend/src/context/Toast/ToastContext.tsx
> +    }
굳굳 반영했습니다!

2023-09-21 02:25 UTC, ksone02 commented on frontend/src/context/Toast/ToastContext.tsx
> +const tempToast = (content: ToastContent, option?: ToastOption): ToastInterface => ({
앗 네이밍 고친다는걸 그냥 올렸네요 바꿨습니다!

2023-09-22 05:53 UTC, n0eyes approved these changes
고생하셨습니다!

2023-09-22 05:54 UTC, HyeryongChoi approved these changes

2023-09-22 05:54 UTC, merged