feat: refresh token 적용
woowacourse-teams/2023-zipgo pull request #447
Opened 2023-09-26 06:13 UTC by iamjooon2

## 📄 Summary
> #384 

주요 변경사항
- refresh token 적용
- 로그아웃 API 적용

## 🙋🏻 More
> 

대략적인 플로우는 다음과 같습니다...!

![image](https://github.com/woowacourse-teams/2023-zipgo/assets/73161212/d0077daf-bf65-4230-a112-8020f44a53bb)

2023-09-28 14:01 UTC, wonyongChoi05 requested changes
오우오우 갈비 너무 수고했어~~ 코드가 너무 깔끔해서 별로 남길 게 없넹ㅋㅋ 저번에 라이브로 했던 피드백 기억 안날까봐 조금 달아놨어 추석 잘 쉬고 오시게~ 풍가위(풍성한 한가위) 보내~~

2023-09-28 14:01 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/auth/support/RefreshTokenCookieProvider.java
> +        this.expireLength = jwtCredentials.getRefreshTokenExpireLength();
요거 @Value 빈으로 바로 바인딩 안되나여?

2023-09-28 14:30 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/application/AuthService.java
> +        RefreshToken savedRefreshToken = refreshTokenRepository.getByToken(token);
파라미터로 받는 토큰이 refreshToken이 된다면 필요할 예정

2023-09-28 14:32 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/dto/TokenDto.java
> +        );
저는 개행이 있는게 오히려 깔끔하더라구요
new 키워드 바로 밑에 들어갈 파라미터들이 눈에 확 들어오는 느낌

우리 컨벤션으로 정한게 없으니까 이야기 같이 나눠보죠

2023-09-28 14:33 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/dto/AccessTokenResponse.java
> +        );
ditto

2023-09-28 14:37 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/support/RefreshTokenCookieProvider.java
> +        this.expireLength = jwtCredentials.getRefreshTokenExpireLength();
필드가 하나라 @Value로 사용할 수도 있겠지만 하드코딩 하는 느낌이 들고
JwtCredentials를 사용하는 게 인증 관련 정보들 중 refreshToken의 유효기간이다~로 읽혀서 이 방법을 선택했어요

테스트시에도 jwtCredential 임의로 생성해서 주입해줄 수 있고요~

2023-09-28 14:46 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/domain/RefreshToken.java
> +    @Include
<img width="553" alt="image" src="https://github.com/woowacourse-teams/2023-zipgo/assets/73161212/40f7e2c1-c0fa-467a-a477-7ce4bd6b2cdd">

이 친구 찾는 거 맞나요?

2023-09-28 14:49 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/domain/RefreshToken.java
> +    @Include
조금 더 구체적으로 남겨주셨으면 좋겠어요ㅠ 어떤 의미인지 파악하기 어렵네요

2023-09-28 14:58 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/dto/TokenDto.java
> +        );
코드 보니까 셋 다 한줄로 쓰고 저만 이렇게 쓰네요ㅋㅋ

바꿔서 올릴게요~

2023-09-30 06:06 UTC, kyY00n commented on backend/src/main/java/zipgo/auth/application/AuthService.java
> +        return jwtProvider.createAccessToken(memberId.toString());
저라면 2요
회원아이디를 애플리케이션 전역에서 Long으로 다루고 있기 때문 인데요

제 의견이 다소 공감이 어려울 수 있을 것 같아 예를 들자면
만약 타입이 따로 있었다면 다음과 같이 있는게
String으로 변환한 인자를 넣는 것보다 사용성이 좋을 것이 분명하기 때문입니다.
책임과 역할도 분명히 이 메서드의 것이고요.

```java
public String createAccessToken(MemberId memberId) 
```

지금은 MemberId라는 타입입 없으니 Long을 사용하는 것이 맞겠지만요..

2023-09-30 06:08 UTC, kyY00n commented on backend/src/main/java/zipgo/auth/domain/RefreshToken.java
> +    @Include
그러게 베베야 맵다 매워

2023-09-30 06:55 UTC, kyY00n approved these changes
궁금한 거 코멘트 남겼어요! 수고했어 가비 :D

2023-09-30 06:55 UTC, kyY00n commented on backend/src/main/java/zipgo/auth/domain/RefreshToken.java
> +public class RefreshToken extends BaseTimeEntity {
이건 모두의 이해를 위한 질문!
리프레시토큰을 기존 테이블의 컬럼으로 추가하지 않고 분리한 이유는 무엇인가요? 😃

2023-09-30 06:55 UTC, kyY00n commented on backend/src/main/java/zipgo/auth/support/RefreshTokenCookieProvider.java
> +        return ResponseCookie.from(REFRESH_TOKEN, LOGOUT_COOKIE_VALUE)
로그아웃을 이렇게 구현하셨군요 가비👍🏻
로그아웃 쿠키를 아예 없애는 방법도 있었을 것 같은데, 이렇게 한 이유가 궁금합니다!
(단순 질문)

2023-09-30 06:55 UTC, kyY00n commented on backend/src/test/java/zipgo/auth/domain/repository/RefreshTokenRepositoryTest.java
> +        refreshTokenRepository.save(new RefreshToken(1L, "집고의 비밀 토큰"));
개귀엽다 ㅋㅋㅋㅋ

.   ·  *
˚ .
:¨·.·¨:
`·. 집고의 비밀 토큰-★°*ﾟ

2023-09-30 06:55 UTC, kyY00n commented on backend/src/test/resources/application.yml
> +  refresh-token-expire-length: 9999999999999
이거는 어떤 뜻일까용? 무한대??

2023-09-30 15:30 UTC, parkmuhyeun reviewed
고생했으 갈비~ 👍🏻👍🏻

refreshToken DB에 저장하는거 같은데 쌓인거 삭제 관련된 내용은 없는거 같아서 어떻게 할 생각인지 궁금합니당

2023-09-30 15:30 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/auth/application/AuthService.java
> +        return jwtProvider.createAccessToken(memberId.toString());
1, 2 관점에서 고민해봤는데 1로 하게 되어 String으로 오게되면 만약 정책이 바뀌어도 잘못 사용할 가능성이 있어보이네요.

예를 들어, memberId를 payload로 사용하다가 accessToken payload를 email로 바꾸게 되면 밖에서 넘어오는 값을 모두 email로 바꿔줘야 됩니다. 근데 실수로 하나라도 놓치게 되면, String으로 받고 있는 경우에는 코드 상에서는 드러나지 않아 나중에 운영시점에 버그로 발견될 것 같습니당. 하지만, 만약 안에서 바꾸게 되면 모든 부분에서 컴파일 에러가 발생해서 방지할 수 있을 것 같아요.

그래서 저두 2번이 좀 더 좋아보이네여

2023-09-30 15:30 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/auth/presentation/AuthController.java
> +    @PostMapping("/log-out")
위에서 로그인도 "/login"인데
"/logout"으로 해도 될 것 같아여

2023-09-30 15:30 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/auth/presentation/AuthController.java
> +    public ResponseEntity<Void> logOut(@Auth AuthCredentials authCredentials) {
메서드 이름도!

2023-09-30 15:30 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/common/config/JwtCredentials.java
> +    private final long refreshTokenExpireLength;
length가 뭔가 길이라고 해석되는거 같아서 다음 중에 어떤가요!?
"expiryPeriod"
"expiryTerm"
"expiryTime"

2023-09-30 15:30 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/auth/application/AuthServiceMockTest.java
> +class AuthServiceMockTest {
얘 컨테이너 띄울 필요가 없지 않나여
@SpringbootTest 제거하고 @ExtendWith(MockitoExtension.class)으로 대체 후
- @MockBean -> @Mock
- @Autowired -> @InjectMocks

2023-09-30 15:59 UTC, iamjooon2 commented on backend/src/test/resources/application.yml
> +  refresh-token-expire-length: 9999999999999
테스트용이라 별 의미 없습니다

2023-09-30 16:03 UTC, iamjooon2 commented on backend/src/main/java/zipgo/common/config/JwtCredentials.java
> +    private final long refreshTokenExpireLength;
꼼꼼 굳

2023-09-30 16:10 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/domain/RefreshToken.java
> +public class RefreshToken extends BaseTimeEntity {
기존 테이블의 칼럼으로 들어가면 레디스 등의 토큰 전용 DB 적용하여 따로 뺴는 상황에
버려지는 열이 하나 생기는 셈일 것 같습니다

2023-09-30 16:19 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/support/RefreshTokenCookieProvider.java
> +        return ResponseCookie.from(REFRESH_TOKEN, LOGOUT_COOKIE_VALUE)
`null이 아닌 공백 문자열을 사용한 이유`가 맞나요...?

자바시작하고 null이란친구가 많이 괴롭혀서 되도록이면 null 대신 공백문자열 쓰는 편입니다

2023-10-01 01:02 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/auth/domain/RefreshToken.java
> +    @Include
ㅠㅠ Include 말한거에요...

2023-10-01 12:34 UTC, iamjooon2 commented on backend/src/test/resources/application.yml
> +  refresh-token-expire-length: 9999999999999
실제 토큰 만료기한은 엑세스토큰 - 30분
리프레시토큰 - 일주일

로 생각중입니다

2023-10-01 12:36 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/support/RefreshTokenCookieProvider.java
> +        return ResponseCookie.from(REFRESH_TOKEN, LOGOUT_COOKIE_VALUE)
아 서버에서 아예 지우는 건.... 레퍼런스 찾아봐도 위에 언급한 null밖에 없드라구요

2023-10-01 12:38 UTC, iamjooon2 commented on backend/src/test/java/zipgo/auth/application/AuthServiceMockTest.java
> +class AuthServiceMockTest {
@parkmuhyeun 남길 곳이 없어서 여기 남겨요

만료된 토큰 지우는 건, 리프레시토큰까지 만료되서 재로그인 하는 과정에서 해당 회원의 memberId를 가진 토큰을 지우도록 추가했어요
[요 부분이에요](https://github.com/woowacourse-teams/2023-zipgo/pull/447/files#diff-a1cc32ba3aa315da85c3e5265f9a952f27826eff00dcd8132a49899af560147eR38)

2023-10-02 10:58 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/auth/application/AuthServiceMockTest.java
> +class AuthServiceMockTest {
재 로그인 할 때 지우는군여

2023-10-02 10:59 UTC, parkmuhyeun approved these changes

2023-10-02 11:33 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/application/AuthService.java
> +        return jwtProvider.createAccessToken(memberId.toString());
2번으로 바꾸어서 올렸슴니다

2023-10-02 12:07 UTC, kyY00n commented on backend/src/main/java/zipgo/auth/domain/RefreshToken.java
> +public class RefreshToken extends BaseTimeEntity {
좋습니다 👍🏻

2023-10-02 12:07 UTC, kyY00n commented on backend/src/main/java/zipgo/auth/support/RefreshTokenCookieProvider.java
> +        return ResponseCookie.from(REFRESH_TOKEN, LOGOUT_COOKIE_VALUE)
좋습니다! 참고한 레퍼런스를 PR에 추가해주시면 더 좋을 것 같습니다 👍🏻

2023-10-02 12:08 UTC, kyY00n commented on backend/src/test/resources/application.yml
> +  refresh-token-expire-length: 9999999999999
맞네요 테스트!! 패키지를 잘못 봤어요 ㅎㅎ

2023-10-02 12:08 UTC, kyY00n approved these changes
수고하셨습니당 ☀️

2023-10-02 13:15 UTC, parkmuhyeun approved these changes

2023-10-02 13:48 UTC, wonyongChoi05 approved these changes

2023-10-02 14:34 UTC, merged