feat: 메인페이지 하단 '사료 선택 도움말 배너' 추가
woowacourse-teams/2023-zipgo pull request #458
Opened 2023-10-03 07:02 UTC by HyeryongChoi

## 📄 Summary
우리 서비스에서 고민한 부분이 잘 전달 되도록 UI/UX를 개선하기 위해
[사료 선택 도움말 페이지 링크](https://translucent-mallet-426.notion.site/dae305b85c8146399d7de6a0e74b773d?pvs=4)로 이동시키는 사료 선택 도움말 배너를 구현하였습니다.

### 실행화면
https://github.com/woowacourse-teams/2023-zipgo/assets/24777828/13f05bc8-8701-4ba0-89d0-7c922cb567c4

## 🙋🏻 More
> 노션 페이지 링크 내용도 한번 확인해주세요~~ 저희 깃헙 위키에 있는 서비스 소개를 참고하여 작성했습니다.

- close #457

2023-10-03 07:08 UTC, iamjooon2 commented on frontend/src/assets/svg/with_pet_icon.svg
사진 귀엽네요

2023-10-04 04:37 UTC, ksone02 submitted a review, later dismissed
오 짱이뻐요! 굳굳

2023-10-04 07:09 UTC, n0eyes requested changes
너무 이쁜데요~!?

간단한 코멘트만 확인 부탁드려요!

2023-10-04 09:52 UTC, ksone02 approved these changes

2023-10-04 10:17 UTC, n0eyes commented on frontend/src/components/FoodSelectionGuideBanner/FoodSelectionGuideBanner.tsx
> +      >
딱히 이점은.. 없는데요 ㅎㅎ
외부 이동도 가능하고 통일성을 위해 좋지 않을까 했습니다 😄

2023-10-04 16:00 UTC, HyeryongChoi commented on frontend/src/components/FoodSelectionGuideBanner/FoodSelectionGuideBanner.tsx
> +      >
그럼 a태그로 사용해도 괜찮을까요? 리액트 페이지가 아닌 외부 페이지로의 이동은 a태그 사용이 좀더 의미에 맞는 것 같아서요~!!@!

2023-10-05 01:21 UTC, n0eyes approved these changes

2023-10-05 01:38 UTC, merged