feat: 식품 상세 조회 API
woowacourse-teams/2023-zipgo pull request #80
Opened 2023-07-27 08:32 UTC by kyY00n

## 📄 Summary
> 

- closes: #59 

## 🙋🏻 More
> 일단 올립니다. 리뷰 포인트는 코멘트 남겨놓을게요!

2023-07-27 08:34 UTC, kyY00n commented on backend/src/main/java/zipgo/petfood/presentation/PetFoodController.java
> +        double ratingAverage = reviewService.calculateRatingAverage(foundPetFood);
이거에 대한 의견을 나눠보시죠

2023-07-27 08:35 UTC, kyY00n commented on backend/src/main/java/zipgo/petfood/presentation/dto/GetPetFoodResponse.java
> +    }
요 두 record 분리할까요? 다른 곳에서도 사용할 가능성을 생각해봐주셨으면.

2023-07-27 08:37 UTC, kyY00n commented on backend/src/test/java/zipgo/petfood/application/PetFoodServiceTest.java
> +        PetFood 키워드가_없는_식품 = petFoodRepository.save(키워드_없이_식품_초기화(브랜드_조회하기()));
아니 Entity 이런식으로 계속 만드는게 너무 지쳤어요

2023-07-27 08:43 UTC, kyY00n reviewed
음.. 알려주세요

2023-07-27 09:30 UTC, wonyongChoi05 requested changes
수고했어 로지~~ 간단하게 남겨봤으~

2023-07-27 09:30 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/petfood/presentation/dto/GetPetFoodResponse.java
> +    }
이거 분리하는게 좋지 않을까요? 도메인 자체가 분리되어있어서 외부에서 충분히 사용할 가능성이 있을 것 같아요!

2023-07-27 09:30 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/acceptance/PetFoodAcceptanceTest.java
> +                            fieldWithPath("brand.hasResidentVet").description("상주 수의사 존재 여부")
요거 DTO로 받는게 가독성 측면에서 낫지 않나용??

2023-07-27 09:30 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/petfood/application/PetFoodServiceTest.java
> +        // then
요거 // when, then 어때용??

2023-07-27 09:30 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/petfood/presentation/GlobalExceptionHandler.java
>  @Log4j2
요거 순서!

2023-07-27 09:30 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/petfood/exception/PetFoodException.java
> +            super(String.format("아이디가 %d 인 상품을 찾을 수 없습니다.", id));
요거 static import!

2023-07-27 09:30 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/petfood/domain/StringArrayConverter.java
> +        return String.join(SPLIT_CHAR, attribute);
String.join static import!

2023-07-27 09:30 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/petfood/application/PetFoodService.java
>          Keyword keyword = keywordRepository.findByName(keywordName)
이거 서비스에서 던질 수도 있지만, repository의 default 메소드 쓰면 getById처럼 사용할 수 있습니다!

example

```java
default Keyword getById(Long id) {
    return findById(id)
               .orElseThrow(() -> new KeywordException.NotFound(keywordName);
}
```

2023-07-27 09:30 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/petfood/application/PetFoodServiceUnitTest.java
> +                .willReturn(Optional.of(아이디가_있는_식품));
Optional static import!

2023-07-27 09:30 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/review/application/ReviewServiceTest.java
> +                .stoolCondition(StoolCondition.SOFT_MOIST)
static import!

2023-07-27 09:30 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/acceptance/PetFoodAcceptanceTest.java
> +                    .contentType(ContentType.JSON)
ContentType static import!

2023-07-27 09:30 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/application/ReviewService.java
> +        int sumOfRatings = reviews.stream().mapToInt(review -> review.getRatings()).sum();
이거 이렇게도 쓸 수 있을뜻!?

```java
return review.stream()
    .mapToInt(Review::getRatings)
    .average()
    .getAsDouble();
```

++ stream() 밑으로는 한 칸씩 개행하는거 어때??

2023-07-27 09:30 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/review/application/ReviewServiceTest.java
> +                .stoolCondition(StoolCondition.SOFT_MOIST)
static import!

2023-07-27 09:30 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/review/application/ReviewServiceTest.java
> +        Member 회원 = memberRepository.save(Member.builder().build()); // todo: 멤버 필수 필드 추가
tmi긴한데 todo 대문자로 쓰면 색이 다르게 나옵니다!!!

2023-07-27 09:30 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/petfood/application/PetFoodServiceTest.java
> +        Keyword 다이어트_키워드 = keywordRepository.findByName("diet").orElseThrow();
이거 orElseThrow에 아무것도 안쓴 이유가 있나용??

2023-07-27 09:30 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/petfood/domain/HasStandard.java
> +
이거 mistake~~

2023-07-27 12:44 UTC, shin-mallang reviewed
아까 말한것만 잠깐 남기고 갑니당~
집고 화이팅 🚀

2023-07-27 12:44 UTC, shin-mallang commented on backend/src/main/java/zipgo/petfood/presentation/PetFoodController.java
> +        double ratingAverage = reviewService.calculateRatingAverage(foundPetFood);
아까 잠깐 얘기한거 적고 가자면,
1. 우선 기능 개발이 우선이라 생각해서, 이렇게 구현하고 넘어가는 것도 좋다고 생각하고, 현재 딱히 문제되는 부분은 없다고 생각해!
2. 그러나 이런 식으로 계속 코드를 작성한다면, Service에서 반환된 객체를 컨트롤러에서 사용하는 경우 [OSIV](https://ttl-blog.tistory.com/183)로 인해 문제가 생길 수 있어. 
  - 부가 설명을 하자면, 스프링 부트에서는 OSIV를 기본적으로 true로 설정하지만, 이후 커넥션 낭비등을 최소화하기 위해 OSIV 옵션을 끊다면 그때 Lazy Loading 문제가 발생할 수 있어. 이런 경우를 대비하고자, 조회를 위한 객체를 QueryService에서 바로 반환하는 것이 좋다고 생각해.  추가적으로 이렇게 함으로써, 비즈니스 로직(명령)에는 아무런 영향 없이, 조회 성능을 극대화할 수도 있고.

간단한 예시는 다음과 같을 거 같아.
```java
@Service
@Transactional
@RequiredArgumentConstructor
public class PetFoodService {

    private final PetFoodRepository petFoodRepository;
    
    pubic Long create() {
    } 

    pubic void update() {
    } 

    pubic void delete() {
    } 
}
```


```java
@Service
@Transactional(readOnly=true)
@RequiredArgumentConstructor
public class PetFoodService {

    private final PetFoodQueryRepository petFoodQueryRepository;
    
    public GetPetFoodsResponse getPetFoods(String keyword) {
           return petFoodQueryRepository.getPetFoods(keyword);
    }

    public GetPetFoodResponse getPetFood(Long id) {
           return petFoodQueryRepository.getPetFood(id);
    }
}

```

2023-07-27 12:44 UTC, shin-mallang commented on backend/src/test/java/zipgo/petfood/application/PetFoodServiceTest.java
> +        PetFood 키워드가_없는_식품 = petFoodRepository.save(키워드_없이_식품_초기화(브랜드_조회하기()));
땡벌 땡벌

2023-07-27 13:16 UTC, parkmuhyeun reviewed
캠퍼스에서 생각해놓고 집에가서 적을려했는데 베베가 이미 다 적어놨네용

꼼꼼한 테스트 굿굿
전체적으로 보면서 static 부분 추가해주면 좋을 것 같네여

고생하셨슴다~

2023-07-27 13:16 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/petfood/presentation/dto/GetPetFoodResponse.java
> +    }
ㅇㅇ 브랜드dto는 충분히 다른데서 쓰일 듯

2023-07-27 13:16 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/application/ReviewService.java
> +public class ReviewService {
이거 나랑 컨플릭트 나겠다.....힣

2023-07-27 13:16 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/acceptance/PetFoodAcceptanceTest.java
> +                    .assertThat().statusCode(HttpStatus.OK.value());
여기도 static!

2023-07-27 13:16 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/acceptance/PetFoodAcceptanceTest.java
> +                    .pathParam("id", 1000000000000232323L)
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-07-27 13:16 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/acceptance/PetFoodAcceptanceTest.java
> +                    .assertThat().statusCode(HttpStatus.NOT_FOUND.value());
ditto

2023-07-27 13:16 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/petfood/application/PetFoodServiceTest.java
> +        PetFood 키워드가_없는_식품 = petFoodRepository.save(키워드_없이_식품_초기화(브랜드_조회하기()));
기다리다 지쳤어요~ 땡벌! 땡벌!

2023-07-27 13:16 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/petfood/application/PetFoodServiceTest.java
> +        // then
밑에는 그렇게 해놓은거 보니 둘 중 하나로 통일하죵

2023-07-27 13:16 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/petfood/domain/repository/PetFoodRepositoryTest.java
> +    @ParameterizedTest
꼼꼼한 테스트 굿~ 👍🏻👍🏻👍🏻

2023-07-27 14:49 UTC, iamjooon2 reviewed
어후 처음 보는 것들도 꽤있네요
코멘트 달 게 컨벤션밖에 없네요

시간 되면 같이 페어프로그래밍 하시죠. 고생많으셨습니다

2023-07-27 14:49 UTC, iamjooon2 commented on backend/src/main/java/zipgo/petfood/presentation/GlobalExceptionHandler.java
>  public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {
적을 곳이 마땅치 않아서 여기다가 적는데
Common 패키지로 이동하는 건 어떰?

2023-07-27 14:49 UTC, iamjooon2 commented on backend/src/main/java/zipgo/petfood/presentation/dto/GetPetFoodResponse.java
> +    }
Ditto

2023-07-27 14:49 UTC, iamjooon2 commented on backend/src/test/java/zipgo/petfood/application/PetFoodServiceUnitTest.java
> +        Assertions.assertThat(조회된_식품).isEqualTo(아이디가_있는_식품);
static import 할 수 있을 것 같아용

2023-07-27 14:49 UTC, iamjooon2 commented on backend/src/test/java/zipgo/petfood/application/PetFoodServiceUnitTest.java
> +        AssertionsForClassTypes.assertThatThrownBy(() -> petFoodService.getPetFoodBy(존재하지_않는_아이디))
여기두 static import

2023-07-27 15:17 UTC, kyY00n commented on backend/src/main/java/zipgo/petfood/application/PetFoodService.java
>          Keyword keyword = keywordRepository.findByName(keywordName)
정말 좋은 것 같아요
이런 예외처리는 리포지토리 역할인 것 같아 찝찝했었는데, 해결책 감사합니다~👍🏻

2023-07-27 15:18 UTC, kyY00n commented on backend/src/test/java/zipgo/review/application/ReviewServiceTest.java
> +                .stoolCondition(StoolCondition.SOFT_MOIST)
빌더.. 도요?????

2023-07-27 15:21 UTC, kyY00n commented on backend/src/test/java/zipgo/review/application/ReviewServiceTest.java
> +        Member 회원 = memberRepository.save(Member.builder().build()); // todo: 멤버 필수 필드 추가
전 소문자도 잘 되는뎁쇼 ㅇㅅaㅇ

2023-07-27 15:30 UTC, kyY00n commented on backend/src/main/java/zipgo/review/application/ReviewService.java
> +        int sumOfRatings = reviews.stream().mapToInt(review -> review.getRatings()).sum();
너무 좋당 ~ ✔️

2023-07-27 15:32 UTC, kyY00n commented on backend/src/main/java/zipgo/review/application/ReviewService.java
> +public class ReviewService {
ㅋㅋㅋㅋㅋㅋㅋ

2023-07-27 15:33 UTC, kyY00n commented on backend/src/test/java/zipgo/acceptance/PetFoodAcceptanceTest.java
> +                    .pathParam("id", 1000000000000232323L)
이걸 .. 해야했을까?

2023-07-27 15:33 UTC, kyY00n commented on backend/src/test/java/zipgo/acceptance/PetFoodAcceptanceTest.java
> +                    .assertThat().statusCode(HttpStatus.NOT_FOUND.value());
ㄱㅅ요

2023-07-27 15:33 UTC, kyY00n commented on backend/src/test/java/zipgo/petfood/domain/repository/PetFoodRepositoryTest.java
> +    @ParameterizedTest
감사합니다 선생님..

2023-07-27 15:38 UTC, kyY00n commented on backend/src/test/java/zipgo/acceptance/PetFoodAcceptanceTest.java
> +                            fieldWithPath("brand.hasResidentVet").description("상주 수의사 존재 여부")
무슨 이야기인지 한번만 다시 설명해줄 수 있어?..🙏🏻
+) 혹시나 하고 말씀드리자면 이 부분은 단언문이 아니라 api 문서화 코드입니다

2023-07-27 15:51 UTC, kyY00n commented on backend/src/main/java/zipgo/petfood/presentation/dto/GetPetFoodResponse.java
> +    }
(전달!) 이런 의견도 있습니다.
여러분 알고계시겠지만 저는 다시금 기억하고자.. 기록해봅니다. 📝
---

클린아키텍처에는 이런 내용이 나옵니다.
> 진짜 코드 중복과 잠깐 중복하는 것처럼 보이는 우발적 중복을 구분해야 한다. 서로 성격이 많이 다른 액터들이 같은 모듈을 공유한다면, 한 액터가 모듈을 변경했을 때 다른 액터가 영향을 받는다.

이 DTO가 뷰에 대응하는 조회 정보라면, 우리가 이야기하는 재사용 DTO와는 성격이 다를 수 있다고 볼 수 있습니다.
화면(뷰)은 변경이 잦은 영역이므로 이 DTO도 변경될 가능성이 높아요.
따라서 이 뷰의 변화만으로도 DTO를 공유하는 액터들은 영향받을 수 있습니다.
그러므로, 이 DTO는 잠깐은 중복인 것처럼 보이는 우발적 중복이라 보고 그대로 둘 수 있습니다.

따라서 이 레코드를 이 안에서만 사용하도록 하고, 분리하지 않는 것이 좋을 수 있습니다.

2023-07-27 15:57 UTC, iamjooon2 commented
다시봐도 테스트 명품이다

2023-07-27 16:04 UTC, parkmuhyeun submitted a review, later dismissed

2023-07-27 17:52 UTC, kyY00n commented on backend/src/main/java/zipgo/petfood/domain/PetFood.java
> +    }
도메인에 메시지를 던지도록 리팩터링했습니다.

2023-07-27 17:55 UTC, kyY00n commented on backend/src/test/java/zipgo/petfood/domain/repository/PetFoodRepositoryTest.java
> +    void 기능성이_null이면_빈_리스트로_가져온다() {
null 값이 Converter에서 바뀌는 분기를 테스트하기 위해서 추가했어요
<img width="728" alt="image" src="https://github.com/woowacourse-teams/2023-zipgo/assets/61582017/1ab0bb76-d4f5-4435-9af2-b5a4803ccfdb">

2023-07-27 23:54 UTC, shin-mallang commented on backend/src/main/java/zipgo/petfood/presentation/dto/GetPetFoodResponse.java
> +    }
나도 우발적 중복이라 생각해서 분리 안 할듯요~

2023-07-28 00:58 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/review/application/ReviewServiceTest.java
> +        Member 회원 = memberRepository.save(Member.builder().build()); // todo: 멤버 필수 필드 추가
헉.... 그건 몰랐다...

2023-07-28 01:55 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/petfood/presentation/dto/GetPetFoodResponse.java
> +    }
> ## (전달!) 이런 의견도 있습니다.
> 여러분 알고계시겠지만 저는 다시금 기억하고자.. 기록해봅니다. 📝
> 클린아키텍처에는 이런 내용이 나옵니다.
> 
> > 진짜 코드 중복과 잠깐 중복하는 것처럼 보이는 우발적 중복을 구분해야 한다. 서로 성격이 많이 다른 액터들이 같은 모듈을 공유한다면, 한 액터가 모듈을 변경했을 때 다른 액터가 영향을 받는다.
> 
> 이 DTO가 뷰에 대응하는 조회 정보라면, 우리가 이야기하는 재사용 DTO와는 성격이 다를 수 있다고 볼 수 있습니다. 화면(뷰)은 변경이 잦은 영역이므로 이 DTO도 변경될 가능성이 높아요. 따라서 이 뷰의 변화만으로도 DTO를 공유하는 액터들은 영향받을 수 있습니다. 그러므로, 이 DTO는 잠깐은 중복인 것처럼 보이는 우발적 중복이라 보고 그대로 둘 수 있습니다.
> 
> 따라서 이 레코드를 이 안에서만 사용하도록 하고, 분리하지 않는 것이 좋을 수 있습니다.

처음 알았습니다만...?

2023-07-28 01:55 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/petfood/application/PetFoodServiceTest.java
> +        PetFood 키워드가_없는_식품 = petFoodRepository.save(키워드_없이_식품_초기화(브랜드_조회하기()));
sql ㅋㅋㅋ?

2023-07-28 01:56 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/acceptance/PetFoodAcceptanceTest.java
> +                            fieldWithPath("brand.hasResidentVet").description("상주 수의사 존재 여부")
앗 그러면 제가 잘못 단 코멘트군요 ㅠ

2023-07-28 01:59 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/petfood/application/PetFoodServiceTest.java
> +        Keyword 다이어트_키워드 = keywordRepository.findByName("diet").orElseThrow();
저는 이런경우에 Optional 값을 최대한 받으려고 하지 않는 것 같아요!(findByName -> getByName) 저는 orElseThrow인데 왜 아무것도 안던지지!?라는 생각이 좀 들었던 것 같아요 ㅎㅎ

2023-07-28 06:33 UTC, kyY00n commented on backend/src/test/java/zipgo/petfood/application/PetFoodServiceTest.java
> +        Keyword 다이어트_키워드 = keywordRepository.findByName("diet").orElseThrow();
리팩토링 진행할게요 ~!!

2023-07-28 06:51 UTC, parkmuhyeun reviewed
내 코드를 보는 건지 로지꺼를 보는 건지 헷갈리네요ㅋㅋ

2023-07-28 06:51 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/petfood/presentation/PetFoodController.java
>          PetFood foundPetFood = petFoodService.getPetFoodBy(id);
그때 말랑꺼 듣고 controller로 domain 안 내놓고 service에서 dto 만들어서 주는거 아니였나요?

2023-07-28 06:51 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/domain/Review.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true, callSuper = false)
callSuper가 뭐죠

2023-07-28 06:51 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/petfood/application/PetFoodServiceTest.java
>                  .isInstanceOf(KeywordException.NotFound.class);
static ㅋ

근데 없으면 헷갈릴거 같긴한데 없애지말까요? 여러분들의  생각은?

2023-07-28 06:51 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/review/fixture/ReviewFixture.java
> +                .tastePreference(TastePreference.EATS_VERY_WELL)
static ㅋ

2023-07-28 06:51 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/review/fixture/ReviewFixture.java
> +                .tastePreference(TastePreference.EATS_VERY_WELL)
제 코드지만 로지꺼에 있으니 로지가 해주셈요

2023-07-28 07:04 UTC, kyY00n commented on backend/src/main/java/zipgo/petfood/presentation/PetFoodController.java
>          PetFood foundPetFood = petFoodService.getPetFoodBy(id);
일단 하고 서브 태스크로 가져가고 싶어서요~

2023-07-28 07:12 UTC, kyY00n commented on backend/src/main/java/zipgo/review/domain/Review.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true, callSuper = false)
지금 BaseTimeEntity를 상속하고 있는데, BaseTimeEntity의 필드를 사용하고 싶을 때 callSuper 를 true로 설정한다고 해요.
우리는 Review의 id만을 사용하므로 false로 설정돼야해요. 궁금하시면 [프로젝트롬복](https://projectlombok.org/features/EqualsAndHashCode) 참조!

사실 callSuper의 기본값은 false 이긴하나, 컴파일 할 때 다음과 같이 superclass를 호출하지 않는 것에 대해 워닝이 뜨고 있어요.
<img width="1031" alt="image" src="https://github.com/woowacourse-teams/2023-zipgo/assets/61582017/e49aef25-22e0-4de1-b8a6-8f10958c0ee5">
그래서 워닝에 있는 권고와 같이 명시를 해주고, 워닝이 더이상 뜨지 않게 해줬습니다 ㅎㅎ

2023-07-28 07:42 UTC, kyY00n commented on backend/src/test/java/zipgo/petfood/application/PetFoodServiceTest.java
>                  .isInstanceOf(KeywordException.NotFound.class);
전 일단 안하겠습니다.

2023-07-28 07:44 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/petfood/presentation/PetFoodController.java
>          PetFood foundPetFood = petFoodService.getPetFoodBy(id);
확인이요~

2023-07-28 07:44 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/petfood/application/PetFoodServiceTest.java
>                  .isInstanceOf(KeywordException.NotFound.class);
확인이요

2023-07-28 07:44 UTC, parkmuhyeun approved these changes

2023-07-28 09:22 UTC, parkmuhyeun approved these changes
제 똥 치워주시느라 늘 고생이 많습니다^^7

2023-07-28 09:48 UTC, iamjooon2 approved these changes
LGTM

2023-07-28 09:51 UTC, merged

2023-07-28 12:48 UTC, iamjooon2 commented on backend/src/main/java/zipgo/petfood/presentation/dto/GetPetFoodResponse.java
> +    }
또 배워갑니다