feat: 리뷰목록 조회 기능 추가
woowacourse-teams/2023-zipgo pull request #81
Opened 2023-07-27 13:34 UTC by HyeryongChoi

## 📄 Summary
- close #68 
### ReviewList 컴포넌트 UI
<img width="394" alt="image" src="https://github.com/woowacourse-teams/2023-zipgo/assets/24777828/cdec3030-e7ac-43d4-8780-11bbd9618b44">

### StarRatingDisplay 컴포넌트 UI
<img width="930" alt="image" src="https://github.com/woowacourse-teams/2023-zipgo/assets/24777828/3a5c7385-94f1-41f1-ac33-ac16b7c3a70f">

### ✅ Tasks
- [x] 리뷰 목록을 확인할 수 있다.
- [x] 리뷰 아이템을 확인할 수 있다.
  - 기호성, 대변상태, 이상반응을 확인할 수 있다.
  - 텍스트리뷰를 확인할 수 있다.
  - 더보기 버튼으로 가려진 리뷰를 확인할 수 있다.

## 🙋🏻 More
### 🕖 예상 작업 소요 시간

> 5시간
> 7/28까지 해볼게용

### 🕖 실제 작업 소요 시간

> 20시간

2023-07-28 01:08 UTC, n0eyes requested changes

2023-07-28 01:08 UTC, n0eyes commented on frontend/src/components/@common/StarRating/StarRatingDisplay/StartRatingDisplay.tsx
> +        return <Star size={size} key={index} src={imageUrl} alt="" />;
`alt` 속성을 뺀 이유가 있을까요~?

2023-07-28 01:08 UTC, n0eyes commented on frontend/src/components/Review/Reviews.tsx/ReviewList.tsx
> +}
api 요청을 해당 컴포넌트 내부에서 하는건 어떨까요?

아래와 같은 장점을 얻을 수 있을 것 같아요 😄
- 의존성 제거 > 재사용성 증가
- `Suspense`를 통해 로딩 관심사 분리 및 로딩 UI 적용 용이
- `ErrorBoundary`를 통해 에러 관심사 분리 및 에러 UI 적용 용이

2023-07-28 01:11 UTC, n0eyes requested changes

2023-07-28 01:11 UTC, n0eyes commented on frontend/src/components/Review/Reviews.tsx/ReviewList.tsx
> +import { styled } from 'styled-components';
폴더명 수정 부탁드려요!!

2023-07-28 01:30 UTC, HyeryongChoi commented on frontend/src/components/@common/StarRating/StarRatingDisplay/StartRatingDisplay.tsx
> +        return <Star size={size} key={index} src={imageUrl} alt="" />;
ㅎㅎㅎ 수정했습니다

2023-07-29 09:06 UTC, HyeryongChoi commented
api 요청을 해당 `ReviewList`컴포넌트 내부에서 하는 방향으로 수정하였습니다! 
- 컴포넌트 내부에서 현재 url의 파라미터 값을 사용하여 api 요청을 하기 때문에 스토리북에서는 해당 파라미터 값을 가져올 수 없어 리뷰 목록에 대한 스토리북은 삭제했습니다.

```tsx
const ReviewList = () => {
  const { petFoodId } = useValidParams(['petFoodId']);
  const { reviewList } = useReviewListQuery({ petFoodId });

  if (!reviewList) throw new Error('리뷰 목록을 불러오지 못했습니다.');

  return (
    ...
  );
};
```

### useValidParams
```tsx
export const useValidParams = (payload: string[]): Readonly<Params<string>> => {
  const params = useParams();
  const validParams = payload.reduce((acc, key) => {
    if (key in params) {
      if (params[key] === undefined) throw new Error('Invaild Params');

      return { ...acc, [key]: params[key] };
    }

    throw new Error(`Param '${key}' not found`);
  }, {});

  return validParams;
};
```
React Router의 `useParams` 훅을 사용하여 URL의 파라미터를 가져와서 **유효한 파라미터**(`undefined`가 아닌 파라미터)만을 추려내는 커스텀 훅인 `useValidParams`를 정의하였습니다.

2023-07-30 07:51 UTC, n0eyes requested changes

2023-07-30 07:51 UTC, n0eyes commented on frontend/src/hooks/@common/useValidParams.ts
> +export const useValidParams = (payload: string[]): Readonly<Params<string>> => {
`payload` 파라미터명도 좋지만 명확함을 위해 `paramKeyArr`와 같은 네이밍은 어떨까요~?

2023-07-30 07:51 UTC, n0eyes commented on frontend/src/hooks/@common/useValidParams.ts
> +export const useValidParams = (payload: string[]): Readonly<Params<string>> => {
현재 사용하는 쪽에서 반환값의 타입이 편리하게 추론되지 않는 것 같아요!

다음과 같이 제네릭을 활용하면 어떨까요?

```tsx
export const useValidParams = <T extends string>(paramKeyArr: T[]): Params<T> => { }
```

2023-07-30 07:51 UTC, n0eyes commented on frontend/src/hooks/@common/useValidParams.ts
> +      if (params[key] === undefined) throw new Error('Invaild Params');
`Invalid` 오타 있어요 😆

code spell checker 와 같은 익스텐션을 활용해도 좋을 것 같아요~

2023-07-30 07:55 UTC, n0eyes requested changes

2023-07-30 07:55 UTC, n0eyes commented on frontend/src/hooks/@common/useValidParams.ts
> +  }, {});
`early return`을 통해 블록을 줄여보는 것은 어떨까요!?

```tsx
    if (!(key in params)) {
      throw new Error(`Param '${key}' not found`);
    }

    if (!params[key]) {
      throw new Error('Invaild Params');
    }

    return { ...acc, [key]: params[key] };
```

2023-07-30 08:28 UTC, HyeryongChoi commented on frontend/src/hooks/@common/useValidParams.ts
> +export const useValidParams = (payload: string[]): Readonly<Params<string>> => {
`paramKeys`는 어떤가요?!

2023-07-30 08:50 UTC, HyeryongChoi commented on frontend/src/hooks/@common/useValidParams.ts
> +export const useValidParams = (payload: string[]): Readonly<Params<string>> => {
```tsx
  const params = useValidParams(['petFoodId']);
```
`params`의 타입 추론 결과를 보면 아래와 같습니다!
> 현재 사용하는 쪽에서 반환값의 타입이 편리하게 추론되지 않는 것 같아요!

1번과 같은 경우가 '반환값의 타입이 편리하게 추론되지 않는 상황'인 것인지 궁금해요!

### 1. 기존
<img width="382" alt="image" src="https://github.com/woowacourse-teams/2023-zipgo/assets/24777828/8b240cb1-76b3-4994-9c25-dbcb33d89b00">

### 2. 제네릭을 활용한 경우
<img width="426" alt="image" src="https://github.com/woowacourse-teams/2023-zipgo/assets/24777828/29b7b39b-c24a-47e1-a857-cd704f3250c3">

2023-07-30 17:32 UTC, n0eyes approved these changes
고생하셨습니다 😁

2023-07-30 17:32 UTC, n0eyes commented on frontend/src/hooks/@common/useValidParams.ts
> +export const useValidParams = (payload: string[]): Readonly<Params<string>> => {
첫 번째 경우는 인덱스 시그니쳐에 `string` 타입이 사용되고
두 번째 경우는 인덱스 시그니쳐에 `string literal` 타입이 사용되고 있어요!

따라서 사용하는 쪽에서 다음과 같이 사용하는 경우
```tsx
  const params = useValidParams(['petFoodId']);
```
첫 번째는 객체의 키 값이 구체적으로 추론되지 않아요

두 번째는 다음과 같이 구체적으로 추론돼요!
<img width="488" alt="image" src="https://github.com/woowacourse-teams/2023-zipgo/assets/79056677/32cf8a21-01ab-4364-b3d7-3fbcd3fac0dd">

2023-07-31 05:28 UTC, ksone02 commented on frontend/src/styles/globalStyle.ts
> +    font-family: Pretandard, sans-serif;
👍

2023-07-31 05:44 UTC, HyeryongChoi commented on frontend/src/constants/review.ts
> +export const TASTE_PREFERENCES = [
```tsx
import { ADVERSE_REACTIONS, STOOL_CONDITIONS, TASTE_PREFERENCES } from '@/constants/review';

type TastePreference = (typeof TASTE_PREFERENCES)[number];
type StoolCondition = (typeof STOOL_CONDITIONS)[number];
type AdverseReaction = (typeof ADVERSE_REACTIONS)[number];

type Review = {
  id: number;
  profileImageUrl?: string;
  reviewerName: string;
  rating: number;
  date: string;
  comment: string;
  tastePreference: TastePreference;
  stoolCondition: StoolCondition;
  adverseReactions: AdverseReaction[];
};

export type { Review };
```

넵 리액션과 관련된 상수들을 이용해서 타입을 지정해주었어요!

2023-07-31 05:47 UTC, ksone02 approved these changes

2023-07-31 05:53 UTC, merged