feat: 리뷰 생성 기능 구현
woowacourse-teams/2023-zipgo pull request #86
Opened 2023-07-28 10:00 UTC by parkmuhyeun

## 📄 Summary
-  close: #63 

## 🙋🏻 More
> 컨플릭트가 많이 뜰거 같아서 무서워요..

![image](https://github.com/woowacourse-teams/2023-zipgo/assets/76938931/65681b17-e9d6-4538-9050-a692f1395257)

2023-07-28 10:13 UTC, iamjooon2 submitted a review, later dismissed
LGTM

2023-07-28 10:13 UTC, iamjooon2 commented on backend/src/main/java/zipgo/member/domain/repository/MemberRepository.java
> +    default Member getById(Long id) {
저희 앞으로 서비스에서 처리 안하구 레파지토리에서 default 만들어서 사용하는건가유

2023-07-28 10:13 UTC, iamjooon2 commented on backend/src/test/java/zipgo/review/application/ReviewServiceTest.java
> +                "어쩔 TV",
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-07-28 10:13 UTC, iamjooon2 commented on backend/src/main/java/zipgo/review/dto/request/CreateReviewRequest.java
> +        @Max(5)
와 `@Valid`에 이런 것도 있네

2023-07-28 10:13 UTC, iamjooon2 commented on backend/src/test/java/zipgo/review/presentation/ReviewControllerTest.java
> +            //TODO 여기도 갈비씨가 member pr 날려주면 리팩토링 할 듯
😉

2023-07-28 11:53 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/member/domain/repository/MemberRepository.java
> +    default Member getById(Long id) {
맞져 이렇게 안하면 서비스마다 만들어줘야되는데 repo에 하면 재사용할 수 있슴둥

2023-07-28 14:55 UTC, wonyongChoi05 requested changes
코드 너무 잘 짜셔서 별거 남기지 못했네요 ㅠ 화이팅!

2023-07-28 14:55 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/domain/Review.java
> +                .map(adverseReaction -> AdverseReaction.builder().name(adverseReaction).build())
이거 빌더 가독성이 떨어지는 것 같아요! name 생성자만 오버로드 해서 사용하는거 어떤가요??

2023-07-28 14:55 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/domain/StoolCondition.java
> +        return Arrays.stream(values())
values().stream 안되나용?

2023-07-28 14:55 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/domain/StoolCondition.java
>  public enum StoolCondition {
이거 enum 클래스인데 domain/type/StoolCondition 어떤가요!?

2023-07-28 14:55 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/dto/request/CreateReviewRequest.java
> +        String comment,
개행

2023-07-28 14:55 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/dto/request/CreateReviewRequest.java
> +        List<String> adverseReactions
개행

2023-07-28 14:55 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/dto/response/GetReviewsResponse.java
>                  review.getCreatedAt().format(DateTimeFormatter.ofPattern("yyyy-MM-dd")),
static import

2023-07-28 14:55 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/presentation/ReviewController.java
> +            Long memberId,
memberId 어떻게 받는거죠...?

2023-07-28 14:55 UTC, wonyongChoi05 commented on backend/src/test/java/zipgo/review/application/ReviewServiceTest.java
> +        //then
// when, then

2023-07-28 14:55 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/dto/request/CreateReviewRequest.java
> +                        .tastePreference(TastePreference.from(tastePreference()))
```java
TastePreference.valueOf(tastePreference()))
```

위와 같은 문법으로도 컨버팅이 되는거 아셨나요!? 만약 알고 있었다면 정적 팩토리 메서드로 분리한 이유를 알려주세요!

2023-07-28 14:59 UTC, iamjooon2 commented on backend/src/main/java/zipgo/review/domain/StoolCondition.java
> +        return Arrays.stream(values())
컬렉션 아니라 배열 반환해서 안되지 않음?

2023-07-28 14:59 UTC, iamjooon2 commented on backend/src/main/java/zipgo/review/domain/StoolCondition.java
> +        return Arrays.stream(values())
컬렉션 아니라 배열 반환해서 안되지 않나용?

2023-07-28 15:41 UTC, kyY00n requested changes
수고했어요👍🏻 충돌 해결하시고 api 테스트 한번 리팩터링부탁드려요
제가 처음에 Api 응답 하나에 대한 문서가 생성되는걸 API 문서가 생성되는 것처럼 변수명을 지어서 수정해놓았거든요, 의미 다시 확인하시고 변수명이나 메서드명 같은거 정리해주시면 감사하겠습니다🥹👏🏻

2023-07-29 08:01 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/domain/StoolCondition.java
> +        return Arrays.stream(values())
values는 배열인디용

2023-07-29 08:07 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/dto/request/CreateReviewRequest.java
> +        List<String> adverseReactions
어디부분? 28번째 29번째 사이?

2023-07-29 08:08 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/dto/request/CreateReviewRequest.java
> +        String comment,
이거 애노테이션 없는데도 띄움?

2023-07-29 08:10 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/presentation/ReviewController.java
> +            Long memberId,
갈비씨가 resolver로 id 준다는디요

2023-07-29 08:19 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/dto/request/CreateReviewRequest.java
> +                        .tastePreference(TastePreference.from(tastePreference()))
valueOf는 Enum의 value이름들을 기반으로 작동하는데
지금은 필드값인 description으로 하고있슴당

2023-07-29 08:21 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/dto/request/CreateReviewRequest.java
> +        public Review toEntity(Member member, PetFood petFood) {
보통 requestDto 정보를 엔티티에 채워넣어 만들기떄문에 요런식으로 편하게 제공하려고 썻습니당

2023-07-29 08:22 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/exception/StoolConditionException.java
> +            super("배변 상태를 찾을 수 없습니다.");
좋아용 사실 에러메시지 적을 떄도 뭔가 말이 찝찝했씁니다.

2023-07-29 08:45 UTC, kyY00n commented on backend/src/main/java/zipgo/review/dto/request/CreateReviewRequest.java
> +        public Review toEntity(Member member, PetFood petFood) {
옹 좋은것같아요 😀😀👍🏻

2023-07-29 08:48 UTC, kyY00n submitted a review, later dismissed
질문 답변까지 감사합니다👍🏻👍🏻 수고했어요 남은기능도 가보자고🚀

2023-07-29 09:09 UTC, wonyongChoi05 approved these changes

2023-07-29 11:05 UTC, kyY00n approved these changes
수고하셨습니당👍🏻👍🏻

2023-07-29 13:21 UTC, iamjooon2 commented on backend/src/main/java/zipgo/review/presentation/ReviewController.java
> +            Long memberId,
얍얍

2023-07-29 13:29 UTC, iamjooon2 approved these changes
고생 많으셨습니다 민무!

2023-07-29 13:49 UTC, merged