feat: 소셜 로그인 구현
woowacourse-teams/2023-zipgo pull request #87
Opened 2023-07-29 13:36 UTC by iamjooon2

## 📄 Summary
> #60 소셜로그인 

사실상 첫 PR이네요

로그인은 일단 액세스 토큰만 주고, 유효기간을 엄청 길게하는 방식으로 만들면 될 것 같아요
추후에 리프레시 토큰을 추가하든가 하면 될 것 같아요

좀 이르게 올리는 감이 없지않은데.. 혼자 고민하는 것보다 리뷰 받으며 만들어 가는게 훨씬 낫다고 생각했습니다

놓친게 많을 것 같은데 꼼꼼하게 봐주세용

## 🙋🏻 More
> 
Jacoco에 테스트 제외하도록 추가한 놈들이 있습니다

```java
                    '*.*Dto',
                    '*.*Interceptor',
                    '*.*ArgumentResolver',
                    '*.AuthController',
```
AuthControllerTest는 월요일에 같이 작성한 후 삭제하도록 할게용.

컨플릭트 무섭다....

2023-07-29 13:38 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/application/AuthService.java
> +public class AuthService {
CQRS 나눠야 할까 하다가 일단 AuthService는 냅두고 MemberService를 사용하는 식으로 만들어두었슴

2023-07-29 13:40 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/presentation/AuthController.java
> +    public ResponseEntity<AuthResponse> getMemberDetail(@Auth AuthDto authDto) {
이거 memberId 하나 들어가있는데 다른 게 추가 될 수도 있을까...? 해서 일단 Dto로 감싸서 보내도록 만들었음 @parkmuhyeun

2023-07-29 13:42 UTC, iamjooon2 commented on backend/src/main/java/zipgo/member/domain/repository/MemberRepository.java
> +                .orElseThrow(IllegalArgumentException::new);
뭐야이거

2023-07-30 06:41 UTC, wonyongChoi05 requested changes
가비 수고했어~! 처음하는데도 너무 잘해준 것 같아서 다행이네! 간단하게 남겼으니 읽어봐줘~~

2023-07-30 06:41 UTC, wonyongChoi05 commented on backend/build.gradle
> +    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
jwt관련 의존성들은 모두 붙여 써주는게 읽기 좋을 것 같아요!

2023-07-30 06:41 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/auth/KakaoOAuthResponse.java
> +@NoArgsConstructor
어노테이션 컨벤션 못들으신 것 같아서 말씀드리자면 피라미드 형식으로 작성해주시면 됩니다!(젤 밑이 젤 긴 어노테이션!)

2023-07-30 06:41 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/auth/application/AuthService.java
> +        OAuthResponse oAuthResponse = oAuthClient.getMemberDetail(accessToken);
지금 고민할 문제는 아닐 수도 있지만, 좋은 설계를 위해 제 생각을 말씀드려 볼게요!

이거 만약에 OAuthClient가 꽤 오래 걸리는 작업이라고 가정했을 때 한 트랜잭션이 계속 붙잡고 있으면 db 커넥션이 마를 수도 있지 않을까요? 만약 그렇다면 oauthClient를 의존하는건 transaction을 건 service의 역할이 맞을까요?

2023-07-30 06:41 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/auth/application/AuthService.java
> +        }
이거 람다로 묶을 수 있을 것 같아요!

2023-07-30 06:41 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/auth/presentation/BearerTokenExtractor.java
> +    private static final String BEARER_REGEX = "^Bearer [A-Za-z0-9-_=]+\\.[A-Za-z0-9-_=]+\\.?[A-Za-z0-9-_.+/=]*$";
이게 어떤 정규식인지 변수명으로 표현해주면 좋을 것 같아요!

2023-07-30 06:41 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/auth/presentation/BearerTokenExtractor.java
> +package zipgo.auth.presentation;
presentation 계층의 역할이 맞나요!?

2023-07-30 06:41 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/auth/util/JwtProvider.java
> +            @Value("${jwt.expire-length}") long validityInMilliseconds
ConfigurationPropertiesScan에 대해서 알아보시면 좋을 것 같아요! 개발자가 문자열 하드코딩 하는 것 보다 자바언어로 쓰는게 좋겠죠!?(JPA도 그래서 쓰니 ㅎㅎㅎ)

2023-07-30 06:41 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/auth/util/JwtProvider.java
> +package zipgo.auth.util;
컴포넌트 객체가 util 패키지에 있는거 괜찮다고 생각하시나요?

2023-07-30 06:41 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/member/application/MemberCommandService.java
> +@Transactional(readOnly = true)
command 서비스인데 readOnly...? 실수죵??
+ 관습적으론 Command 서비스는 그냥 MemberService라고 쓰기도 한답니다!

2023-07-30 06:41 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/auth/application/KakaoOAuthClient.java
> +        MultiValueMap<String, String> body = createRequestBodyWithAuthCode(authCode);
카카오 OAuth header Midea type이 특이하게 APPLICATION_FORM_URLENCODED을 지원해서 위 자료구조를 택하셨나요? 그게 아니라면 requestDto를 만들어서 요청하셔도 될 것 같다는 생각이 드네요, RestTemplate을 쓰기도 하시니!

2023-07-30 06:41 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/auth/presentation/AuthController.java
> +        return ResponseEntity.ok(new TokenResponse(token));
TokenResponseDto는 정팩메 안쓰시나요?

2023-07-30 06:41 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/auth/presentation/AuthController.java
> +    public ResponseEntity<TokenResponse> login(@RequestParam("code") String authCode) {
백엔드가 callbackurl 받기로 했나요?

2023-07-30 06:41 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/common/config/AppConfig.java
> +public class AppConfig {
resttemplate configurer인데 네이밍이 AppConfig인 이유가 있나요?

2023-07-30 06:41 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/common/config/AppConfig.java
> +        return new RestTemplate();
이거 빈으로 등록하신 이유가 뭔지 궁금하네요! 지금 보니까 그냥 new RestTemplate만 하는데, 그냥 상수로 쓸 수도 있을 것 같아서요~

2023-07-30 07:15 UTC, kyY00n requested changes
소셜로그인 처음 해본다고 하셨는데 진짜 큰 작업 스타트를 멋지게 끊어주셨네요 :D
이제 가비는 집고 소셜로그인에 한해서는 가장 잘 아는 분이 되신겁니다!!
가비쌤 앞으로도 많이 알려주세요~! 수고했어요👍🏻

(작업 더 하실것 같아서 request changes로 갑니다ㅋㅋㅋ)

+) 서비스 테스트 대부분 모킹을 이용하셨는데 가비는 모킹을 이용한 단위테스트가 스터빙 없는 단위테스트보다 우선되어야한다고 생각하는지 궁금하네요!! 월요일에 같이 얘기 나눠보아요 :D

2023-07-30 07:15 UTC, kyY00n commented on backend/src/test/java/zipgo/auth/application/KakaoOAuthClientTest.java
> +        when(restTemplate.exchange(KAKAO_USER_INFO_URI, GET, request, KakaoOAuthResponse.class))
위와 마찬가지 입니다 :D 
가비가 원하는대로 리팩터링 해주시면 좋을 것 같아요!

2023-07-30 07:15 UTC, kyY00n commented on backend/src/test/java/zipgo/auth/util/JwtProviderTest.java
> +    @DisplayName("올바른 토큰 정보로 payload를 조회한다.")
온점 붙이려고 displayname 사용하신건가요? ㅋㅋㅋ

2023-07-30 07:15 UTC, kyY00n commented on backend/src/test/java/zipgo/auth/util/JwtProviderTest.java
> +    @Test
이런 경우는 `@ParameterizedTest` 사용하는 것도 좋을 것 같네요 👍🏻

2023-07-30 07:15 UTC, kyY00n commented on backend/src/test/java/zipgo/auth/util/JwtProviderTest.java
> +                .setExpiration(new Date((new Date()).getTime() - 1))
```suggestion
        Date 과거_시간 = new Date((new Date()).getTime() - 1);
        String 만료된_토큰 = Jwts.builder()
                .signWith(hmacShaKeyFor(secretKey.getBytes(UTF_8)), HS256)
                .setSubject(String.valueOf(1L))
                .setExpiration(과거_시간)
```
이러면 가독성이 더 좋아질 것 같아요! 반영은 가비 맘~

2023-07-30 07:15 UTC, kyY00n commented on backend/src/test/java/zipgo/auth/util/JwtProviderTest.java
> +        JwtProvider 유효기간이_지난_jwtProvider = new JwtProvider(
👍🏻👍🏻👍🏻👍🏻

2023-07-30 07:15 UTC, kyY00n commented on backend/src/test/java/zipgo/member/application/MemberCommandServiceTest.java
> +                () ->assertThat(저장된_멤버.getId()).isNotNull()
엇 .. 포맷팅이 안된것같아요!

2023-07-30 07:15 UTC, kyY00n commented on backend/src/test/java/zipgo/member/application/MemberQueryServiceTest.java
> +class MemberQueryServiceTest {
이 클래스는 `MemberQueryServiceMockTest` 로 수정하는 건 어떨까요?

2023-07-30 15:29 UTC, parkmuhyeun reviewed
와따 갈비.. 고생했다 👍🏻👍🏻👍🏻 ㅋㅋㅋ
보는데도 이렇게 오래 걸리는데 구현하는데 얼마나 고민한지 가늠이 안되넹
짱짱

2023-07-30 15:29 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/auth/application/KakaoTokens.java
> +public class KakaoTokens {
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy::class)
사용해서 한번에 바꾸는 건 어떤가용

2023-07-30 15:29 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/auth/application/KakaoTokens.java
> +public class KakaoTokens {
그리고 얘도 dto로 이해했는데 record로 해야되지않나용

2023-07-30 15:29 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/auth/presentation/Auth.java
> +public @interface Auth {
공백

2023-07-30 15:29 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/auth/presentation/AuthController.java
> +@RestController
여기도 피라미드!
(혹시 까먹으실까봐 또 적어드려용)

2023-07-30 15:29 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/auth/presentation/AuthController.java
> +    public ResponseEntity<AuthResponse> getMemberDetail(@Auth AuthDto authDto) {
굿 머어어어얼쥐되면 리팩터링할게

2023-07-30 15:29 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/auth/util/JwtProvider.java
> +        tokenToJws(token);
이 메서드는 아래 메서드를 단순히 호출하는거 같은데 필요가 있을까용

2023-07-30 15:29 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/auth/util/JwtProvider.java
> +            throw new AuthException(e);
AuthException은 같은 경우 터져도 exceptionhandler에 따로 잡히지 않을꺼 같은데 추가해줘야 되지 않을까용

2023-07-30 15:29 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/auth/presentation/AuthInterceptor.java
> +    }
개행

2023-07-30 15:29 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/auth/presentation/JwtArgumentResolver.java
> +    }
개행

2023-07-30 15:29 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/auth/util/JwtProvider.java
> +    }
개행

2023-07-30 15:29 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/member/application/MemberQueryService.java
> +@RequiredArgsConstructor
여기도 피라미드!

2023-07-30 15:29 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/auth/application/AuthServiceTest.java
> +@ExtendWith(MockitoExtension.class)
여기도 피라미드!

2023-07-30 15:29 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/auth/application/KakaoOAuthClientTest.java
> +@ExtendWith(MockitoExtension.class)
피라뮈드

2023-07-30 15:29 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/auth/presentation/BearerTokenExtractorTest.java
> +@SuppressWarnings("NonAsciiCharacters")
피라뮈드

2023-07-30 15:29 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/auth/util/JwtProviderTest.java
> +@SuppressWarnings("NonAsciiCharacters")
피라

2023-07-30 15:29 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/auth/presentation/BearerTokenExtractorTest.java
> +        // expect
expect는 when, then 합쳐진건가용?

2023-07-30 15:29 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/member/application/MemberCommandServiceTest.java
> +class MemberCommandServiceTest {
보통은 @SpringBootTest로 통합테스트하고
필요한 부분만 mock하는거 아니였나용

2023-07-30 15:29 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/member/application/MemberQueryServiceTest.java
> +@ExtendWith(MockitoExtension.class)
ㅍㄹㅁㄷ

2023-07-30 15:29 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/auth/application/AuthServiceTest.java
> +    private static final Member MEMBER_FIXTURE = Member.builder().id(1L).email("zipgo@zipgo.com").name("개비").profileImgUrl("사진").build();
이거랑 MemberFixture에 있는거랑 다른 걸까용

2023-07-30 15:29 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/member/domain/repository/MemberRepositoryTest.java
> +@SuppressWarnings("NonAsciiCharacters")
ㅍㄹ

2023-07-31 05:08 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/presentation/BearerTokenExtractor.java
> +    private static final String BEARER_REGEX = "^Bearer [A-Za-z0-9-_=]+\\.[A-Za-z0-9-_=]+\\.?[A-Za-z0-9-_.+/=]*$";
BEARER_JWT_REGEX로 바꿨어요~!

2023-07-31 05:17 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/application/AuthService.java
> +        }
```java
memberOptional.ifPresent(member -> {
    return jwtProvider.create(String.valueOf(member.getId()));
});

```
로 할 수 있을 것 같은데.. 람다가 특별히 가독성이 좋은 것 같다고 느껴지진 않네요...!

2023-07-31 05:18 UTC, iamjooon2 commented on backend/src/main/java/zipgo/common/config/AppConfig.java
> +public class AppConfig {
Resttemplate 뿐만 아니라 다른 것들도 빈으로 등록할 수 있다고 생각해서 , AppConfig로 이름지었어요

2023-07-31 05:19 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/presentation/AuthController.java
> +    public ResponseEntity<TokenResponse> login(@RequestParam("code") String authCode) {
넵 저희 이런 프로세스에요~

![image](https://github.com/woowacourse-teams/2023-zipgo/assets/73161212/e996adc0-c29e-4861-be66-356cb4ae4e6f)

2023-07-31 06:16 UTC, iamjooon2 commented on backend/src/main/java/zipgo/member/application/MemberCommandService.java
> +@Transactional(readOnly = true)
얍 잇츠 마 미스테잌ㅠ QueryService는 그냥 트랜잭션 드가있슴

2023-07-31 06:36 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/application/KakaoOAuthClient.java
> +        ).getBody();
해당사항 예외 추가했어요!

꼼꼼하게 봐주셔서 고마워요

2023-07-31 06:42 UTC, iamjooon2 commented on backend/src/main/java/zipgo/member/application/MemberQueryService.java
> +    }
카카오 로그인을 할 때, 가져온 이메일을 바탕으로 기가입한 사용자인지 확인하는데요
이때 사용하는 메서드가 이 MemberQueryService.findByEmail 이에요
만일 존재하지 않는 사용자라고 예외를 터트릴 경우, AuthService에서 예외를 잡은 뒤 새로 회원가입을 해줘야 하는데요
굳이 메서드 감싸서 예외처리 해준 다음 예외를 잡아 회원을 만들 필요까진 없다고 생각했어요
물론 기존 메서드 컨벤션과는 달라지는지라, 이야기를 나누고 싶었습니다 🙌
다들 어떻게 생각하시나용 @kyY00n @parkmuhyeun @wonyongChoi05

2023-07-31 06:46 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/application/KakaoOAuthClient.java
> +    HttpHeaders createRequestHeader() {
이부분 테스트코드가 너무 길여져 가독성이 떨여졌는데요
민무와 함께 접근제어자를 없애 프로덕션 코드를 재사용했습니다~!

2023-07-31 06:52 UTC, iamjooon2 commented on backend/src/test/java/zipgo/auth/application/KakaoOAuthClientTest.java
> +                .thenReturn(response);
any()를 쓰고 싶었지만... 
테스트코드 실행할 때 request의 값들을 실제로 사용하더라구요...;
any() 써버리면 메서드 실행과정에서 null체크당해서 테스트가 터져버려서...
그래서 어쩔 수 없이 임의로 request를 다 정의해줄 수 밖에 없었습니다.. (with @parkmuhyeun)

request 만드는 메서드를 분리하는 방향으로 수정해볼게요~

2023-07-31 06:55 UTC, iamjooon2 commented on backend/src/test/java/zipgo/auth/application/KakaoOAuthClientTest.java
> +        when(restTemplate.exchange(KAKAO_USER_INFO_URI, GET, request, KakaoOAuthResponse.class))
저 역시 상동합니다!

메서드 분리하는 방향으로 진행했어요~

2023-07-31 06:55 UTC, iamjooon2 commented on backend/src/test/java/zipgo/auth/util/JwtProviderTest.java
> +    @DisplayName("올바른 토큰 정보로 payload를 조회한다.")
지웠어요...ㅋㅋㅋㅋㅋㅋ

2023-07-31 06:59 UTC, iamjooon2 commented on backend/src/test/java/zipgo/auth/util/JwtProviderTest.java
> +                .setExpiration(new Date((new Date()).getTime() - 1))
지금 다시 코드를 보니 잘 읽히지가 않네요~!

반영했어요~!

2023-07-31 07:03 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/application/KakaoTokens.java
> +public class KakaoTokens {
와 이런 꿀어노테이션 고마워요

2023-07-31 07:05 UTC, iamjooon2 commented on backend/src/test/java/zipgo/auth/presentation/BearerTokenExtractorTest.java
> +        // expect
넵 맞아용~!

페어프로그래밍할때 배워온건데 확실히 유용하더라구요
어떻게 생각하시나용...?

2023-07-31 12:15 UTC, iamjooon2 commented on backend/src/test/java/zipgo/member/application/MemberCommandServiceTest.java
> +class MemberCommandServiceTest {
부트테스트로 바꿔써요~

2023-07-31 12:26 UTC, iamjooon2 commented on backend/src/test/java/zipgo/member/application/MemberQueryServiceTest.java
> +class MemberQueryServiceTest {
사라지고말았어요~

2023-07-31 14:26 UTC, kyY00n commented on backend/src/main/java/zipgo/auth/application/KakaoOAuthClient.java
> +            throw new AuthException.KakaoNotFound("카카오 사용자 정보를 가져오는 중 에러가 발생했습니다");
이건 저도 얼마전에 안 건데, 도움이 될 듯해 공유해요.
예외 전환을 하는 경우, 기존 예외의 정보를 포함한다면 디버깅에 유용하겠죠! 그래서 다음처럼 cause 까지 해서 RuntimeException 을 생성해주는 방법을 사용하기도 한다네용 :D
```suggestion
            throw new AuthException.KakaoNotFound("카카오 사용자 정보를 가져오는 중 에러가 발생했습니다", e);
```
```java
public KakaoNotFound(String message, Throwable cause) {
    super(message, cause);
}
```

2023-07-31 14:29 UTC, kyY00n commented on backend/src/test/java/zipgo/auth/application/KakaoOAuthClientTest.java
> +        HttpEntity<MultiValueMap<String, String>> request = createRequest();
이런 자료형은 var 로 선언히면 가독성이 아주 좋아지겠는데요?
⭐️기능 머지 후⭐️에 적극 리팩토링하시죠!

2023-07-31 15:20 UTC, iamjooon2 commented on backend/src/main/java/zipgo/member/domain/repository/MemberRepository.java
> +                .orElseThrow(IllegalArgumentException::new);
머지 컨플릭트 중 민무의 NotFoundException 발견

2023-07-31 15:23 UTC, iamjooon2 commented on backend/src/test/java/zipgo/auth/presentation/AuthControllerTest.java
> +                        fieldWithPath("tokenResponse[].authResponse[].profileImgUrl").description("사용자 프로필 사진")
머지컨플릭트... 해결완료..

2023-07-31 15:26 UTC, iamjooon2 commented on backend/src/test/java/zipgo/auth/application/KakaoOAuthClientTest.java
> +        HttpEntity<MultiValueMap<String, String>> request = createRequest();
적극 리팩터링 해버렸습니다~!

2023-07-31 15:57 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/member/application/MemberQueryService.java
> +    }
>만일 존재하지 않는 사용자라고 예외를 터트릴 경우, AuthService에서 예외를 잡은 뒤 새로 회원가입을 해줘야 하는데요
굳이 메서드 감싸서 예외처리 해준 다음 예외를 잡아 회원을 만들 필요까진 없다고 생각했어요

이거 무슨 말인지 다시 설명해줄 수 있나용

전 MemberNotFoundException 요거 생각했었슴당

2023-07-31 15:57 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/auth/presentation/BearerTokenExtractorTest.java
> +        // expect
expect나 when, then 둘 중 하나로 통일 하시죵

2023-07-31 16:13 UTC, parkmuhyeun reviewed
docs까지 있어서 테스트코드 짜는게 너무 많죠..?ㅋㅋㅋㅋㅋㅋ
고생했어요. 몇개 간단하게 코멘트 남겼음다.

2023-07-31 16:13 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/common/GlobalExceptionHandler.java
>  public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {
이 클래스 부분 컨플릭트 해결하다가 조금 달라진 거 같네여

우선 Httpstatus static으로 해주세용

2023-07-31 16:13 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/common/GlobalExceptionHandler.java
> +    @ExceptionHandler({MemberException.class})
얘 MemberNotFoundException 잡는거 맞나요?
그렇다면 제일 위에 추가해도 되지 않나요?

2023-07-31 16:13 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/common/config/JwtCredentials.java
> +public class JwtCredentials {
오우 분리 깔끔하네용 👍🏻 👍🏻

2023-07-31 16:13 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/common/config/JwtCredentials.java
> +
공백 하나 삭제!

2023-07-31 16:13 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/acceptance/AcceptanceTest.java
> +@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
extendwith이 미세하게 조금 더 깁니다 ㅋㅋㅋㅋㅋㅋㅋㅋ

2023-07-31 16:13 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/auth/presentation/AuthControllerMockArgumentResolverTest.java
> +@ExtendWith({MockitoExtension.class, RestDocumentationExtension.class})
여기도 ㅋㅋㅋ

2023-07-31 16:57 UTC, iamjooon2 commented on backend/src/main/java/zipgo/member/exception/MemberException.java
> +public class MemberException extends RuntimeException {
컨플릭트 해결 후 정보가 생겼답니다~!

2023-08-01 03:00 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/common/config/AppConfig.java
> +public class AppConfig {
지금은 RestTemplate밖에 없지 않나요? 그리고 예를 들어 뭐가 추가 될 수 있는지도 궁금하네요.. 저는 AppConfig라는 네이밍을 가진 클래스에 RestTemplate(?)도 뭔가 좀 알쏭달쏭하지만 여기서 뭐가 더 추가될 수 있을지 궁금하기도 해서요.

2023-08-01 04:26 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/application/KakaoOAuthClient.java
> +        MultiValueMap<String, String> body = createRequestBodyWithAuthCode(authCode);
MutlivalueMap밖에 못합니다~

2023-08-01 04:27 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/util/JwtProvider.java
> +        tokenToJws(token);
함께 해결했습니다~

2023-08-01 04:27 UTC, iamjooon2 commented on backend/src/main/java/zipgo/member/domain/repository/MemberRepository.java
> +    Optional<Member> findByEmail(String email);
함께 해결완~

2023-08-01 04:39 UTC, parkmuhyeun submitted a review, later dismissed
가즈아ㅏㅏㅏㅏㅏㅏㅏㅏㅏ

2023-08-01 04:47 UTC, wonyongChoi05 approved these changes
굿굿

2023-08-01 05:16 UTC, parkmuhyeun approved these changes
또 가즈아ㅏㅏㅏㅏㅏㅏㅏ

2023-08-01 05:17 UTC, kyY00n approved these changes

2023-08-01 05:20 UTC, merged

2023-08-01 06:20 UTC, iamjooon2 commented on backend/src/main/java/zipgo/auth/util/JwtProvider.java
> +package zipgo.auth.util;
그치만.. 다른 네이밍이 뭐가 있을까요 추천좀..