feat: 리뷰 수정 기능 구현
woowacourse-teams/2023-zipgo pull request #88
Opened 2023-07-29 16:21 UTC by parkmuhyeun

## 📄 Summary
-  close: #64 

## 🙋🏻 More
> 얏호! 이제 하나 남았다~

불편했던 점
- exception에 상태코드가 없으니깐 exception 늘어날 때마다 하나하나 추가해줘야 됨
-> 관리 포인트가 늘어난다는 단점 체감
- pr 날리는 단위를 엄청 잘게 쪼개는 것도 좋지 않겠다.
  - 사이클 빨리 빨리 안 도는거 같아 -> 생산성이 많이 느려지는듯

2023-07-30 05:31 UTC, kyY00n reviewed
무민 코드 잘 봤습니다!
질문이 많아서 죄송하지만... 전 너무 재밌게 읽었어요😼
일단은 어프루브 하지 않는 게 더 좋을 수도 있다는 생각이라,,(어차피 풀릴 것 같아서요ㅋㅋㅋ)
코멘트로 남길게요!

2023-07-30 05:31 UTC, kyY00n commented on backend/src/main/java/zipgo/auth/exception/AuthException.java
> +public class AuthException extends RuntimeException {
예외 클래스에대해 같이 생각해봤으면 하는 게 하나 있어요!
무민이 작성해준 이 클래스를 활용하는 걸 상상해보았어요.
그럼 AuthException을 만들면 비즈니스의 모든 인가 프로세스에서 같은 예외를 사용하게 될텐데, 볼수 있는 메시지가 `권한이 없습니다` 로 동일하면 정확히 어떤 문제인지 파악하기 어려울 수도 있을 것 같다는 생각이 들어요.
저는 도메인 예외(ReviewException) 안에 이너클래스로 Authorization 예외클래스를 별도로 만드는 것이 그런 단점을 극복할 방법이 될 수 있을 것 같아요. 무민 생각도 공유부탁드립니다 :D

2023-07-30 05:31 UTC, kyY00n commented on backend/src/main/java/zipgo/review/application/ReviewService.java
> +        update(memberId, request, review);
```suggestion
        Review review = reviewRepository.getById(reviewId);
        review.validateOwner(memberId);
        update(request, review); //업데이트만 수행
```
제 짐작으로는, Review 안의 여러 항목들을 업데이트하는 로직을 `리뷰 업데이트`로 추상화하기 위해 메서드를 분리한 것 같은데 맞을까요?! 클만약 그렇다고 하면 검증부는 포함하지 않는 것도 좋을 듯 해요.

무민 생각도 동일하다면~ 반영해주시면 될 거같고 아님 생각공유해주시고 넘어가도 좋습니다!

2023-07-30 05:31 UTC, kyY00n commented on backend/src/main/java/zipgo/review/domain/Review.java
> +        }
꼼꼼하시네요 👍🏻

2023-07-30 05:31 UTC, kyY00n commented on backend/src/test/java/zipgo/review/application/ReviewServiceTest.java
> +        Assertions.assertThatThrownBy(() -> reviewService.updateReview(멤버.getId(), 123456789L, 리뷰_수정_요청()))
이건 그냥 제 팁인데요! 저는 검증부 가독성을 높이기 위해 이렇게 변수를 선언해주는 편입니다~
```suggestion
        var 잘못된_리뷰_id = 123456789L;
        Assertions.assertThatThrownBy(() -> reviewService.updateReview(멤버.getId(), 잘못된_리뷰_id, 리뷰_수정_요청()))
```

2023-07-30 05:31 UTC, kyY00n commented on backend/src/test/java/zipgo/review/fixture/ReviewFixture.java
> +    public static UpdateReviewRequest 리뷰_수정_요청() {
우리 팀이 한글로 테스트코드를 잘 작성하고 적응하고 있어서 너무 좋아요!
근데 이 코드 보고 처음으로 염려되는 점이 생겼어요..
한글명으로 메서드를 만들면 다른 팀원이 메서드명을 예측하기 어렵다(?)는 단점이 있는 것 같기도 하네요.. 때로는 메서드명도 영문이 더 직관적인 경우가 생길 것 같아요

```suggestion
    public static UpdateReviewRequest createUpdateReviewRequest() {
```
재사용성 관점에서, 다른 분들의 생각도 궁금하네요..!

2023-07-30 05:31 UTC, kyY00n commented on backend/src/test/java/zipgo/review/presentation/ReviewControllerTest.java
> +    //TODO 갈비꺼 merge 후 고정 상수 리팩터링하기
TODO 요정 무민 🧚🏻‍♀️

2023-07-30 05:31 UTC, kyY00n commented on backend/src/test/java/zipgo/review/presentation/ReviewControllerTest.java
> +                    문서_정보.responseSchema(성공_응답_형식)
👍🏻👍🏻👍🏻👍🏻 가독성 좋구만요 >< 무민 적응 짱

2023-07-30 06:43 UTC, wonyongChoi05 requested changes
구웃~

2023-07-30 06:43 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/domain/Review.java
> +    }
update관련 메소드가 엄청 많아지는데, 하나로 묶을수도 있지 않을까요?

2023-07-30 06:43 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/dto/request/UpdateReviewRequest.java
> +        @Min(1)
Size 어노테이션은 어떤가요?

2023-07-30 06:43 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/presentation/ReviewController.java
> +
실수..?

2023-07-30 15:38 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/auth/exception/AuthException.java
> +public class AuthException extends RuntimeException {
그 비용이랑 모든 도메인마다 exception 생성 비용, 관리비용이랑 트레이드오프를 비교해보면 전 전자를 택할거 같아요

예로 드신경우가 로그로 파악할 때 힘든 경우인거 같은데 정확히 어떤 곳이 문제인지 파악할 필요가 있을지가 궁금하고 어디서 잘못된지는 관련 클래스가 뜨기 때문에 예측이 충분히 가능할 것 같아용.

이것도 월요일에 다들 얘기한번 해보면 좋을 것 같아요

2023-07-30 15:45 UTC, parkmuhyeun commented on backend/src/test/java/zipgo/review/fixture/ReviewFixture.java
> +    public static UpdateReviewRequest 리뷰_수정_요청() {
저도 할 때 헷갈리긴 하더라구용 🥲
근데 사용할 때 XXXFixture. 으로 사용하기 때문에 충분히 커버가능할거 같슴당

2023-07-30 15:47 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/domain/Review.java
> +    }
이거 같이할까 나눌까 고민했었는데 하나로 받으면 재사용관점에서 별로인 것 같아서 쪼갰는데 여러분들은 뭐가 좋아보이시나용

2023-07-30 15:49 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/dto/request/UpdateReviewRequest.java
> +        @Min(1)
size는 문자열이나, 배열크기 아닌가용?

2023-07-30 15:49 UTC, parkmuhyeun commented on backend/src/main/java/zipgo/review/presentation/ReviewController.java
> +
억..ㅋㅋㅋ

2023-07-30 17:12 UTC, wonyongChoi05 commented on backend/src/main/java/zipgo/review/dto/request/UpdateReviewRequest.java
> +        @Min(1)
앗 그랬나요 ㅋㅋㅋㅋㅋ 기억이 잘 안나넹..

2023-07-30 17:13 UTC, wonyongChoi05 approved these changes

2023-07-31 00:35 UTC, iamjooon2 approved these changes

2023-07-31 04:14 UTC, merged