Feature/#61
woowacourse-teams/2023-zipgo pull request #89
Opened 2023-07-30 07:57 UTC by n0eyes

## 📄 Summary
> 

## 🙋🏻 More
>

2023-07-30 13:21 UTC, HyeryongChoi requested changes

2023-07-30 13:21 UTC, HyeryongChoi commented on frontend/src/router/Router.tsx
> +);
```suggestion
const Router = createBrowserRouter([
  {
    path: '/',
    element: <App />,
    errorElement: <div>error</div>,
    children: [
      {
        index: true,
        element: <Landing />,
      },
      {
        path: 'login',
        element: <Login />,
      },
    ],
  },
]);
```

이렇게 바꿔보면 어떨까요?

2023-07-30 13:21 UTC, HyeryongChoi commented on frontend/src/utils/getValidQueries.ts
> +export const getValidQueries = <T extends string>(search: string, keyArr: Readonly<T[]>) =>
일관성있게 `keyArr` -> `QueryKeys` 어떤가요?

https://github.com/woowacourse-teams/2023-zipgo/pull/81#discussion_r1278521962

2023-07-31 04:36 UTC, n0eyes commented on frontend/src/router/Router.tsx
> +);
최선 버전에 맞게 수정하였습니다~!

2023-07-31 05:01 UTC, HyeryongChoi submitted a review, later dismissed
고생하셨습니다👍👍👍

2023-07-31 05:56 UTC, ksone02 commented on frontend/src/pages/Login/Login.tsx
> +            <BannerImg src={ZipgoBanner} />
alt 추가되면 좋을 것 같아요~

2023-07-31 05:56 UTC, ksone02 commented on frontend/src/pages/Login/Login.tsx
> +  color: var(--grey-700, #333d4b);
theme를 활용하지 않은 이유가 있나요??

2023-07-31 05:56 UTC, ksone02 commented on frontend/src/types/auth/remote.ts
> +export interface KAuthError {
"K"가 무슨 뜻인가요??

2023-07-31 05:56 UTC, ksone02 commented on frontend/src/types/common/global.d.ts
> +    hasOwn(o: object, p: PropertyKey): p is keyof typeof o;
👍👍

2023-07-31 05:56 UTC, ksone02 commented on frontend/src/index.tsx
>        retry: 0,
`retry: false` 로도 사용할 수 있어요!
근데 retry를 끈 이유가 있나요?

2023-07-31 06:25 UTC, n0eyes commented on frontend/src/assets/png/kakao_login_large_wide.png
카카오 디자인 가이드에 따라 제공하는 asset를 다운받아 사용했어요!

아직 svg와 png 사용 기준이 명확하지 않아서 그대로 사용했는데
svg로 변경하는게 좋을까요~?

2023-07-31 06:25 UTC, n0eyes commented on frontend/src/pages/Login/Login.tsx
> +            <BannerImg src={ZipgoBanner} />
추가했습니다~

2023-07-31 06:25 UTC, n0eyes commented on frontend/src/pages/Login/Login.tsx
> +  color: var(--grey-700, #333d4b);
일치하는 타이포를 찾지 못했는데.. 혹시 완성된 타이포가 있을까요??

2023-07-31 06:26 UTC, n0eyes commented on frontend/src/types/auth/remote.ts
> +export interface KAuthError {
카카오 문서에서 `api` 종류를 `kauth` 와 `kapi`로 나눠 구분하더라구요
그 양식을 그대로 따라봤습니다!

2023-07-31 06:32 UTC, n0eyes commented on frontend/src/index.tsx
>        retry: 0,
에러 핸들링을 좀 더 엄격하게 하여 다음과 같은 이점을 고려했습니다!

- 예상치 못하게 발생하고 있는 에러 추적
- 추후 에러 바운더리에서 에러 로그 기록시 좀 더 정밀하게 기록 가능

어떻게 생각하시나요~?

2023-07-31 06:51 UTC, ksone02 commented on frontend/src/pages/Login/Login.tsx
> +  color: var(--grey-700, #333d4b);
앗 타이포 말고 color 부분이요! theme.color 를 활용할 수 있을 것 같아서요~

2023-07-31 06:52 UTC, ksone02 commented on frontend/src/assets/png/kakao_login_large_wide.png
아 피그마 디자인과 달라서요! 카카오에서 제공해 주는 걸 사용하셨군요..물론 편하고 좋긴 하겠지만
아무래도 폰트도 다르고 해서 저희 디자인 따라 가는 건 어떤가요?

2023-07-31 06:55 UTC, ksone02 commented on frontend/src/types/auth/remote.ts
> +export interface KAuthError {
코드를 처음 보면 직관적으로 이해하기 쉽지 않을 것 같은데, K -> Kakao로 수정하는 건 어떨까요?

2023-07-31 06:56 UTC, n0eyes commented on frontend/src/assets/png/kakao_login_large_wide.png
아하 디자인을 말씀하셨군요!

제가 알기로 카카오 로그인 버튼은 디자인 가이드를 따라야 하는 것으로 알고 있는데
폰트나 심볼 및 레이블의 간격등을 변경해도 괜찮을까요!?

2023-07-31 06:58 UTC, n0eyes commented on frontend/src/pages/Login/Login.tsx
> +  color: var(--grey-700, #333d4b);
왜 제가 컬러를 생각 못했을까요~
수정했습니다!

2023-07-31 07:08 UTC, ksone02 commented on frontend/src/assets/png/kakao_login_large_wide.png
몇 가지 조건만 만족하면 괜찮다고 하네요! 현재 피그마 버튼 디자인은 카카오 디자인 가이드 조건에 맞추어 살짝 수정해놨습니다!

2023-07-31 07:12 UTC, n0eyes commented on frontend/src/types/auth/remote.ts
> +export interface KAuthError {
넵 좀 더 직관적으로 수정하고
주석을 통해 해당 부분의 카카오 문서 링크 기재하였습니다~

2023-07-31 07:38 UTC, n0eyes commented on frontend/src/assets/png/kakao_login_large_wide.png
감사합니다~

마크업으로 수정했습니다!

2023-07-31 07:39 UTC, ksone02 submitted a review, later dismissed
고생하셨습니다~~

2023-07-31 07:56 UTC, ksone02 approved these changes

2023-07-31 07:56 UTC, HyeryongChoi approved these changes

2023-07-31 07:58 UTC, merged