feat: 라벨 컴포넌트 구현
woowacourse-teams/2023-zipgo pull request #96
Opened 2023-07-31 11:15 UTC by ksone02

## 📄 Summary
> close #95 

라벨 컴포넌트를 구현했습니다.

저희 상황에 맞게 확장성 있게 구현했습니다.
피드백 부탁드려요~

<img width="605" alt="스크린샷 2023-07-31 오후 8 14 58" src="https://github.com/woowacourse-teams/2023-zipgo/assets/72087183/5548679c-91c8-4f96-a050-2269eef49ff0">

## 🙋🏻 More
>

2023-07-31 11:52 UTC, HyeryongChoi approved these changes
수고하셨습니다👍👍👍

2023-07-31 11:56 UTC, HyeryongChoi requested changes

2023-07-31 11:56 UTC, HyeryongChoi commented on frontend/src/components/@common/Label/Label.tsx
> +    clicked ? theme.color.blue : backgroundColor};
blue 컬러 추가해주세요~~~

2023-07-31 12:10 UTC, ksone02 commented on frontend/src/components/@common/Label/Label.tsx
> +    clicked ? theme.color.blue : backgroundColor};
헉 pr에 같이 안 올렸었네요 감사합니다~

2023-07-31 13:51 UTC, HyeryongChoi submitted a review, later dismissed

2023-08-01 16:19 UTC, HyeryongChoi submitted a review, later dismissed

2023-08-02 01:17 UTC, n0eyes approved these changes

2023-08-02 01:17 UTC, n0eyes commented on frontend/src/components/@common/Label/Label.tsx
> +   */
`hasBorder` : `false` 와 `borderColor` : `string` 속성이 동시에 존재할 수 있을 것 같아요~
유니온 타입을 활용하여 안정성을 좀 더 높히면 어떨까요?

2023-08-02 01:17 UTC, n0eyes commented on frontend/src/components/@common/Label/Label.tsx
> +  onClick?: () => void;
`VoidFunction` 활용해도 좋을 것 같아요!

2023-08-02 04:24 UTC, ksone02 commented on frontend/src/components/@common/Label/Label.tsx
> +   */
반영하겠습니다 감사해요~

2023-08-02 04:25 UTC, ksone02 commented on frontend/src/components/@common/Label/Label.tsx
> +  onClick?: () => void;
좋습니다!

2023-08-02 05:11 UTC, n0eyes approved these changes

2023-08-02 05:25 UTC, HyeryongChoi approved these changes

2023-08-02 05:32 UTC, merged